# Abstract Algebras

<i>Version 2</i>

## References

* [Group Explorer](https://nathancarter.github.io/group-explorer/index.html) -- Visualization software for the abstract algebra classroom
* [Groupprops, The Group Properties Wiki (beta)](https://groupprops.subwiki.org/wiki/Main_Page)
* [Klein four-group, V4](https://en.wikipedia.org/wiki/Klein_four-group)
* [Cyclic group](https://en.wikipedia.org/wiki/Cyclic_group)

## Imports and Paths

In [1]:
import algebras as alg
import numpy as np
import json
import os

In [2]:
# Path to this repo
aa_path = os.path.join(os.getenv('PYPROJ'), 'abstract_algebra')

# Path to a directory containing Algebra definitions in JSON
alg_dir = os.path.join(aa_path, "Algebras")

### A Very Simple Group

In [3]:
simp = alg.Group("Simple",
                 "A very simple group",
                 ["1", "-1"],
                 [[0, 1],
                  [1, 0]])

In [4]:
simp

Group('Simple', 'A very simple group', ['1', '-1'], [[0 1]
 [1 0]])

In [5]:
simp.addition_table_with_names()

[['1', '-1'], ['-1', '1']]

In [6]:
simp.abelian()

True

In [7]:
simp.inverse_lookup_dict

{'1': '1', '-1': '-1'}

In [8]:
for elem in simp.element_names:
    print(f"inv({elem}) = {simp.inverse(elem)}")

inv(1) = 1
inv(-1) = -1


In [9]:
simp.pretty_print_addition_table()

   1  -1
  -1   1


### Klein-4 Group

See this [definition at GitHub](https://github.com/nathancarter/group-explorer/blob/master/groups/V_4.group).

In [10]:
v4_json = os.path.join(alg_dir, "v4_klein_4_group.json")

!cat {v4_json}

{"type": "Group",
 "name": "V4",
 "description": "Klein-4 group",
 "element_names": ["e", "h", "v", "hv"],
 "addition_table": [[0, 1, 2, 3],
                    [1, 0, 3, 2],
                    [2, 3, 0, 1],
                    [3, 2, 1, 0]]
}


In [11]:
v4 = alg.Group(v4_json)
v4

Group('V4', 'Klein-4 group', ['e', 'h', 'v', 'hv'], [[0 1 2 3]
 [1 0 3 2]
 [2 3 0 1]
 [3 2 1 0]])

In [12]:
v4.to_dict()

{'type': 'Group',
 'name': 'V4',
 'description': 'Klein-4 group',
 'element_names': ['e', 'h', 'v', 'hv'],
 'addition_table': [[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 0, 1], [3, 2, 1, 0]]}

In [13]:
v4.addition_table_with_names()

[['e', 'h', 'v', 'hv'],
 ['h', 'e', 'hv', 'v'],
 ['v', 'hv', 'e', 'h'],
 ['hv', 'v', 'h', 'e']]

In [14]:
v4.pretty_print_addition_table()

   e   h   v  hv
   h   e  hv   v
   v  hv   e   h
  hv   v   h   e


In [15]:
v4.abelian()

True

In [16]:
v4.associative()

True

The group can also be created at the command line:

In [17]:
v4x = alg.Group('V4x',
                'Klein-4 group',
                ['e',  'h',  'v', 'hv'],
                [[0, 1, 2, 3],
                 [1, 0, 3, 2],
                 [2, 3, 0, 1],
                 [3, 2, 1, 0]]
               )

v4x

Group('V4x', 'Klein-4 group', ['e', 'h', 'v', 'hv'], [[0 1 2 3]
 [1 0 3 2]
 [2 3 0 1]
 [3 2 1 0]])

In [18]:
v4.add('h','v')

'hv'

In [19]:
for elem in v4.element_names:
    print(f"inv({elem}) = {v4.inverse(elem)}")

inv(e) = e
inv(h) = h
inv(v) = v
inv(hv) = hv


In [20]:
print(v4)

<Group: V4, Klein-4 group>


In [21]:
v4json = json.dumps(v4.to_dict())
v4json

'{"type": "Group", "name": "V4", "description": "Klein-4 group", "element_names": ["e", "h", "v", "hv"], "addition_table": [[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 0, 1], [3, 2, 1, 0]]}'

### Cyclic group of order 4

See this [definition at GitHub](https://github.com/nathancarter/group-explorer/blob/master/groups/Z_4.group).

In [22]:
z4 = alg.Group('Z4',
           'Cyclic group of order 4',
           ['e', 'a', 'a^2', 'a^3'],
           [[0, 1, 2, 3],
            [1, 2, 3, 0],
            [2, 3, 0, 1],
            [3, 0, 1, 2]]
          )

In [23]:
z4.addition_table_with_names()

[['e', 'a', 'a^2', 'a^3'],
 ['a', 'a^2', 'a^3', 'e'],
 ['a^2', 'a^3', 'e', 'a'],
 ['a^3', 'e', 'a', 'a^2']]

In [24]:
z4.pretty_print_addition_table()

    e    a  a^2  a^3
    a  a^2  a^3    e
  a^2  a^3    e    a
  a^3    e    a  a^2


In [25]:
print(z4.addition_table)

[[0 1 2 3]
 [1 2 3 0]
 [2 3 0 1]
 [3 0 1 2]]


In [26]:
print(z4)

<Group: Z4, Cyclic group of order 4>


In [27]:
z4.add('a^2','a^2')

'e'

In [28]:
z4.add('a^2', 'a^3')

'a'

In [29]:
for elem in z4.element_names:
    print(f"inv({elem}) = {z4.inverse(elem)}")

inv(e) = e
inv(a) = a^3
inv(a^2) = a^2
inv(a^3) = a


In [30]:
z4.abelian()

True

In [31]:
z4.associative()

True

### Symmetric group on 3 letters

See this [definition at GitHub](https://github.com/nathancarter/group-explorer/blob/master/groups/S_3.group). "Another name for this group is "Dihedral group on 3 vertices."

In [32]:
s3 = alg.Group('S3',
           'Symmetric group on 3 letters',
           ['e', 'r', 'r^2', 'f', 'fr', 'rf'],
           [[0, 1, 2, 3, 4, 5],
            [1, 2, 0, 5, 3, 4],
            [2, 0, 1, 4, 5, 3],
            [3, 4, 5, 0, 1, 2],
            [4, 5, 3, 2, 0, 1],
            [5, 3, 4, 1, 2, 0]]
          )

In [33]:
s3.addition_table_with_names()

[['e', 'r', 'r^2', 'f', 'fr', 'rf'],
 ['r', 'r^2', 'e', 'rf', 'f', 'fr'],
 ['r^2', 'e', 'r', 'fr', 'rf', 'f'],
 ['f', 'fr', 'rf', 'e', 'r', 'r^2'],
 ['fr', 'rf', 'f', 'r^2', 'e', 'r'],
 ['rf', 'f', 'fr', 'r', 'r^2', 'e']]

In [34]:
s3.add('fr', 'r^2')

'f'

In [35]:
s3.add('r^2', 'fr')

'rf'

In [36]:
s3.pretty_print_addition_table()

    e    r  r^2    f   fr   rf
    r  r^2    e   rf    f   fr
  r^2    e    r   fr   rf    f
    f   fr   rf    e    r  r^2
   fr   rf    f  r^2    e    r
   rf    f   fr    r  r^2    e


In [37]:
print(s3)

<Group: S3, Symmetric group on 3 letters>


In [38]:
s3.add('fr', 'r^2')

'f'

In [39]:
s3.abelian()

False

In [40]:
s3.associative()

True

In [41]:
for elem in s3.element_names:
    print(f"inv({elem}) = {s3.inverse(elem)}")

inv(e) = e
inv(r) = r^2
inv(r^2) = r
inv(f) = f
inv(fr) = fr
inv(rf) = rf


In [42]:
s3

Group('S3', 'Symmetric group on 3 letters', ['e', 'r', 'r^2', 'f', 'fr', 'rf'], [[0 1 2 3 4 5]
 [1 2 0 5 3 4]
 [2 0 1 4 5 3]
 [3 4 5 0 1 2]
 [4 5 3 2 0 1]
 [5 3 4 1 2 0]])

### Symmetric Group, S3 (not same as S3, above)

This is the [Symmetric group, S3, as specified at Groupprops](https://groupprops.subwiki.org/wiki/Symmetric_group:S3).

W.r.t., how to interpret the addition table, the following quote helps:

[[from Wikipedia](https://groupprops.subwiki.org/wiki/Symmetric_group:S3)] "We portray elements as permutations on the set \{ 1,2,3 \} using the cycle decomposition. The row element is added on the left and the column element on the right, with the assumption of functions written on the left. This means that the column element is applied first and the row element is applied next."

In [43]:
s3x = alg.Group('S3X',
           'Another version of the symmetric group on 3 letters',
           ['()', '(1,2)', '(2,3)', '(1,3)', '(1,2,3)', '(1,3,2)'],
           [[0, 1, 2, 3, 4, 5],
            [1, 0, 4, 5, 2, 3],
            [2, 5, 0, 4, 3, 1],
            [3, 4, 5, 0, 1, 2],
            [4, 3, 1, 2, 5, 0],
            [5, 2, 3, 1, 0, 4]]
          )

In [44]:
s3x.abelian()

False

In [45]:
s3x.associative()

True

In [46]:
s3x.addition_table_with_names()

[['()', '(1,2)', '(2,3)', '(1,3)', '(1,2,3)', '(1,3,2)'],
 ['(1,2)', '()', '(1,2,3)', '(1,3,2)', '(2,3)', '(1,3)'],
 ['(2,3)', '(1,3,2)', '()', '(1,2,3)', '(1,3)', '(1,2)'],
 ['(1,3)', '(1,2,3)', '(1,3,2)', '()', '(1,2)', '(2,3)'],
 ['(1,2,3)', '(1,3)', '(1,2)', '(2,3)', '(1,3,2)', '()'],
 ['(1,3,2)', '(2,3)', '(1,3)', '(1,2)', '()', '(1,2,3)']]

In [47]:
s3x.pretty_print_addition_table()

       ()    (1,2)    (2,3)    (1,3)  (1,2,3)  (1,3,2)
    (1,2)       ()  (1,2,3)  (1,3,2)    (2,3)    (1,3)
    (2,3)  (1,3,2)       ()  (1,2,3)    (1,3)    (1,2)
    (1,3)  (1,2,3)  (1,3,2)       ()    (1,2)    (2,3)
  (1,2,3)    (1,3)    (1,2)    (2,3)  (1,3,2)       ()
  (1,3,2)    (2,3)    (1,3)    (1,2)       ()  (1,2,3)


In [48]:
s3x.add('(1,2)', '(2,3)')

'(1,2,3)'

In [49]:
for elem in s3x.element_names:
    print(f"inv({elem}) = {s3x.inverse(elem)}")

inv(()) = ()
inv((1,2)) = (1,2)
inv((2,3)) = (2,3)
inv((1,3)) = (1,3)
inv((1,2,3)) = (1,3,2)
inv((1,3,2)) = (1,2,3)


## Z_2 x Z_2 x Z_2

In [50]:
Z2xZ2xZ2 = alg.Group('Z_2 x Z_2 x Z_2',
                 'no description',
                 ['eee', 'aee', 'eae', 'aae', 'eea', 'aea', 'eaa', 'aaa'],
                 [[0, 1, 2, 3, 4, 5, 6, 7],
                  [1, 0, 3, 2, 5, 4, 7, 6],
                  [2, 3, 0, 1, 6, 7, 4, 5],
                  [3, 2, 1, 0, 7, 6, 5, 4],
                  [4, 5, 6, 7, 0, 1, 2, 3],
                  [5, 4, 7, 6, 1, 0, 3, 2],
                  [6, 7, 4, 5, 2, 3, 0, 1],
                  [7, 6, 5, 4, 3, 2, 1, 0]]
                )

In [51]:
Z2xZ2xZ2.abelian()

True

In [52]:
Z2xZ2xZ2.associative()

True

In [53]:
Z2xZ2xZ2.addition_table_with_names()

[['eee', 'aee', 'eae', 'aae', 'eea', 'aea', 'eaa', 'aaa'],
 ['aee', 'eee', 'aae', 'eae', 'aea', 'eea', 'aaa', 'eaa'],
 ['eae', 'aae', 'eee', 'aee', 'eaa', 'aaa', 'eea', 'aea'],
 ['aae', 'eae', 'aee', 'eee', 'aaa', 'eaa', 'aea', 'eea'],
 ['eea', 'aea', 'eaa', 'aaa', 'eee', 'aee', 'eae', 'aae'],
 ['aea', 'eea', 'aaa', 'eaa', 'aee', 'eee', 'aae', 'eae'],
 ['eaa', 'aaa', 'eea', 'aea', 'eae', 'aae', 'eee', 'aee'],
 ['aaa', 'eaa', 'aea', 'eea', 'aae', 'eae', 'aee', 'eee']]

In [54]:
Z2xZ2xZ2.pretty_print_addition_table()

  eee  aee  eae  aae  eea  aea  eaa  aaa
  aee  eee  aae  eae  aea  eea  aaa  eaa
  eae  aae  eee  aee  eaa  aaa  eea  aea
  aae  eae  aee  eee  aaa  eaa  aea  eea
  eea  aea  eaa  aaa  eee  aee  eae  aae
  aea  eea  aaa  eaa  aee  eee  aae  eae
  eaa  aaa  eea  aea  eae  aae  eee  aee
  aaa  eaa  aea  eea  aae  eae  aee  eee


In [55]:
for elem in Z2xZ2xZ2.element_names:
    print(f"inv({elem}) = {Z2xZ2xZ2.inverse(elem)}")

inv(eee) = eee
inv(aee) = aee
inv(eae) = eae
inv(aae) = aae
inv(eea) = eea
inv(aea) = aea
inv(eaa) = eaa
inv(aaa) = aaa


## Direct Products

In [56]:
z2 = alg.Group('Z2',
           'Cyclic group of order 2',
           ['E', 'A'],
           [[0, 1],
            [1, 0]]
          )

z3 = alg.Group('Z3',
           'Cyclic group of order 3',
           ['E', 'A', 'B'],
           [[0, 1, 2],
            [1, 2, 0],
            [2, 0, 1]]
          )

In [57]:
z3_x_z3 = z3 * z3
z3_x_z3

Group('Z3_x_Z3', 'Direct product of Z3 & Z3', ['E,E', 'E,A', 'E,B', 'A,E', 'A,A', 'A,B', 'B,E', 'B,A', 'B,B'], [[0 1 2 3 4 5 6 7 8]
 [1 2 0 4 5 3 7 8 6]
 [2 0 1 5 3 4 8 6 7]
 [3 4 5 6 7 8 0 1 2]
 [4 5 3 7 8 6 1 2 0]
 [5 3 4 8 6 7 2 0 1]
 [6 7 8 0 1 2 3 4 5]
 [7 8 6 1 2 0 4 5 3]
 [8 6 7 2 0 1 5 3 4]])

In [58]:
z3_x_z3.element_names

['E,E', 'E,A', 'E,B', 'A,E', 'A,A', 'A,B', 'B,E', 'B,A', 'B,B']

In [59]:
z3_x_z3.addition_table

array([[0, 1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 0, 4, 5, 3, 7, 8, 6],
       [2, 0, 1, 5, 3, 4, 8, 6, 7],
       [3, 4, 5, 6, 7, 8, 0, 1, 2],
       [4, 5, 3, 7, 8, 6, 1, 2, 0],
       [5, 3, 4, 8, 6, 7, 2, 0, 1],
       [6, 7, 8, 0, 1, 2, 3, 4, 5],
       [7, 8, 6, 1, 2, 0, 4, 5, 3],
       [8, 6, 7, 2, 0, 1, 5, 3, 4]])

In [60]:
z3_x_z3.addition_table_with_names()

[['E,E', 'E,A', 'E,B', 'A,E', 'A,A', 'A,B', 'B,E', 'B,A', 'B,B'],
 ['E,A', 'E,B', 'E,E', 'A,A', 'A,B', 'A,E', 'B,A', 'B,B', 'B,E'],
 ['E,B', 'E,E', 'E,A', 'A,B', 'A,E', 'A,A', 'B,B', 'B,E', 'B,A'],
 ['A,E', 'A,A', 'A,B', 'B,E', 'B,A', 'B,B', 'E,E', 'E,A', 'E,B'],
 ['A,A', 'A,B', 'A,E', 'B,A', 'B,B', 'B,E', 'E,A', 'E,B', 'E,E'],
 ['A,B', 'A,E', 'A,A', 'B,B', 'B,E', 'B,A', 'E,B', 'E,E', 'E,A'],
 ['B,E', 'B,A', 'B,B', 'E,E', 'E,A', 'E,B', 'A,E', 'A,A', 'A,B'],
 ['B,A', 'B,B', 'B,E', 'E,A', 'E,B', 'E,E', 'A,A', 'A,B', 'A,E'],
 ['B,B', 'B,E', 'B,A', 'E,B', 'E,E', 'E,A', 'A,B', 'A,E', 'A,A']]

In [61]:
z3_x_z3.pretty_print_addition_table()

  E,E  E,A  E,B  A,E  A,A  A,B  B,E  B,A  B,B
  E,A  E,B  E,E  A,A  A,B  A,E  B,A  B,B  B,E
  E,B  E,E  E,A  A,B  A,E  A,A  B,B  B,E  B,A
  A,E  A,A  A,B  B,E  B,A  B,B  E,E  E,A  E,B
  A,A  A,B  A,E  B,A  B,B  B,E  E,A  E,B  E,E
  A,B  A,E  A,A  B,B  B,E  B,A  E,B  E,E  E,A
  B,E  B,A  B,B  E,E  E,A  E,B  A,E  A,A  A,B
  B,A  B,B  B,E  E,A  E,B  E,E  A,A  A,B  A,E
  B,B  B,E  B,A  E,B  E,E  E,A  A,B  A,E  A,A


In [62]:
for elem in z3_x_z3.element_names:
    print(f"inv({elem}) = {z3_x_z3.inverse(elem)}")

inv(E,E) = E,E
inv(E,A) = E,B
inv(E,B) = E,A
inv(A,E) = B,E
inv(A,A) = B,B
inv(A,B) = B,A
inv(B,E) = A,E
inv(B,A) = A,B
inv(B,B) = A,A


In [63]:
z3_x_z3.abelian()

True

In [64]:
z3_x_z3.associative()

True

In [65]:
z2_x_z2_x_z2 = z2 * z2 * z2

In [66]:
z2_x_z2_x_z2.element_names

['E,E,E', 'E,E,A', 'E,A,E', 'E,A,A', 'A,E,E', 'A,E,A', 'A,A,E', 'A,A,A']

In [67]:
z2_x_z2_x_z2.addition_table

array([[0, 1, 2, 3, 4, 5, 6, 7],
       [1, 0, 3, 2, 5, 4, 7, 6],
       [2, 3, 0, 1, 6, 7, 4, 5],
       [3, 2, 1, 0, 7, 6, 5, 4],
       [4, 5, 6, 7, 0, 1, 2, 3],
       [5, 4, 7, 6, 1, 0, 3, 2],
       [6, 7, 4, 5, 2, 3, 0, 1],
       [7, 6, 5, 4, 3, 2, 1, 0]])

In [68]:
for elem in z2_x_z2_x_z2.element_names:
    print(f"inv({elem}) = {z2_x_z2_x_z2.inverse(elem)}")

inv(E,E,E) = E,E,E
inv(E,E,A) = E,E,A
inv(E,A,E) = E,A,E
inv(E,A,A) = E,A,A
inv(A,E,E) = A,E,E
inv(A,E,A) = A,E,A
inv(A,A,E) = A,A,E
inv(A,A,A) = A,A,A


## Tesseract group

This group has 384 elements and was converted to JSON from [this definition](https://github.com/nathancarter/group-explorer/blob/master/groups/Tesseract.group).

In [69]:
tesseract_path = os.path.join(alg_dir, "tesseract.json")
tesseract = alg.Group(tesseract_path)
print(tesseract)

<Group: Tesseract, The symmetries of the hypercube>


In [70]:
tesseract.abelian()

False

In [71]:
#tesseract.associative() # True

In [72]:
len(tesseract.element_names)

384

Here are the first n elements:

In [73]:
n = 25
tesseract.element_names[:n]

['e',
 'a',
 'b',
 'ba',
 'bb',
 'bba',
 'ab',
 'aba',
 'bab',
 'baba',
 'bbab',
 'abababba',
 'abb',
 'abba',
 'babb',
 'abababbab',
 'ababa',
 'abab',
 'abbab',
 'acabababbac',
 'babbab',
 'ababbab',
 'ababb',
 'ababba',
 'c']

In [74]:
tesseract.add('abab', 'baba')

'babbab'

## Scratch Work

In [75]:
z3_x_z3

Group('Z3_x_Z3', 'Direct product of Z3 & Z3', ['E,E', 'E,A', 'E,B', 'A,E', 'A,A', 'A,B', 'B,E', 'B,A', 'B,B'], [[0 1 2 3 4 5 6 7 8]
 [1 2 0 4 5 3 7 8 6]
 [2 0 1 5 3 4 8 6 7]
 [3 4 5 6 7 8 0 1 2]
 [4 5 3 7 8 6 1 2 0]
 [5 3 4 8 6 7 2 0 1]
 [6 7 8 0 1 2 3 4 5]
 [7 8 6 1 2 0 4 5 3]
 [8 6 7 2 0 1 5 3 4]])

In [76]:
z3_x_z3.element_names

['E,E', 'E,A', 'E,B', 'A,E', 'A,A', 'A,B', 'B,E', 'B,A', 'B,B']

In [77]:
z3

Group('Z3', 'Cyclic group of order 3', ['E', 'A', 'B'], [[0 1 2]
 [1 2 0]
 [2 0 1]])

In [78]:
s3

Group('S3', 'Symmetric group on 3 letters', ['e', 'r', 'r^2', 'f', 'fr', 'rf'], [[0 1 2 3 4 5]
 [1 2 0 5 3 4]
 [2 0 1 4 5 3]
 [3 4 5 0 1 2]
 [4 5 3 2 0 1]
 [5 3 4 1 2 0]])

In [79]:
for elem in s3.element_names:
    print(f"inv({elem}) = {s3.inverse(elem)}")

inv(e) = e
inv(r) = r^2
inv(r^2) = r
inv(f) = f
inv(fr) = fr
inv(rf) = rf


In [80]:
s3.set_direct_product_delimiter(':')

In [81]:
foo = s3 * z3
foo

Group('S3_x_Z3', 'Direct product of S3 & Z3', ['e:E', 'e:A', 'e:B', 'r:E', 'r:A', 'r:B', 'r^2:E', 'r^2:A', 'r^2:B', 'f:E', 'f:A', 'f:B', 'fr:E', 'fr:A', 'fr:B', 'rf:E', 'rf:A', 'rf:B'], [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
 [ 1  2  0  4  5  3  7  8  6 10 11  9 13 14 12 16 17 15]
 [ 2  0  1  5  3  4  8  6  7 11  9 10 14 12 13 17 15 16]
 [ 3  4  5  6  7  8  0  1  2 15 16 17  9 10 11 12 13 14]
 [ 4  5  3  7  8  6  1  2  0 16 17 15 10 11  9 13 14 12]
 [ 5  3  4  8  6  7  2  0  1 17 15 16 11  9 10 14 12 13]
 [ 6  7  8  0  1  2  3  4  5 12 13 14 15 16 17  9 10 11]
 [ 7  8  6  1  2  0  4  5  3 13 14 12 16 17 15 10 11  9]
 [ 8  6  7  2  0  1  5  3  4 14 12 13 17 15 16 11  9 10]
 [ 9 10 11 12 13 14 15 16 17  0  1  2  3  4  5  6  7  8]
 [10 11  9 13 14 12 16 17 15  1  2  0  4  5  3  7  8  6]
 [11  9 10 14 12 13 17 15 16  2  0  1  5  3  4  8  6  7]
 [12 13 14 15 16 17  9 10 11  6  7  8  0  1  2  3  4  5]
 [13 14 12 16 17 15 10 11  9  7  8  6  1  2  0  4  5  3]
 [14 12 13 17 15

In [82]:
foo.abelian()

False

In [83]:
foo.pretty_print_addition_table(delimiter='')

   e:E   e:A   e:B   r:E   r:A   r:B r^2:E r^2:A r^2:B   f:E   f:A   f:B  fr:E  fr:A  fr:B  rf:E  rf:A  rf:B
   e:A   e:B   e:E   r:A   r:B   r:E r^2:A r^2:B r^2:E   f:A   f:B   f:E  fr:A  fr:B  fr:E  rf:A  rf:B  rf:E
   e:B   e:E   e:A   r:B   r:E   r:A r^2:B r^2:E r^2:A   f:B   f:E   f:A  fr:B  fr:E  fr:A  rf:B  rf:E  rf:A
   r:E   r:A   r:B r^2:E r^2:A r^2:B   e:E   e:A   e:B  rf:E  rf:A  rf:B   f:E   f:A   f:B  fr:E  fr:A  fr:B
   r:A   r:B   r:E r^2:A r^2:B r^2:E   e:A   e:B   e:E  rf:A  rf:B  rf:E   f:A   f:B   f:E  fr:A  fr:B  fr:E
   r:B   r:E   r:A r^2:B r^2:E r^2:A   e:B   e:E   e:A  rf:B  rf:E  rf:A   f:B   f:E   f:A  fr:B  fr:E  fr:A
 r^2:E r^2:A r^2:B   e:E   e:A   e:B   r:E   r:A   r:B  fr:E  fr:A  fr:B  rf:E  rf:A  rf:B   f:E   f:A   f:B
 r^2:A r^2:B r^2:E   e:A   e:B   e:E   r:A   r:B   r:E  fr:A  fr:B  fr:E  rf:A  rf:B  rf:E   f:A   f:B   f:E
 r^2:B r^2:E r^2:A   e:B   e:E   e:A   r:B   r:E   r:A  fr:B  fr:E  fr:A  rf:B  rf:E  rf:A   f:B   f:E   f:A
   f:E   f:A   f:B 

In [84]:
s3.addition_table

array([[0, 1, 2, 3, 4, 5],
       [1, 2, 0, 5, 3, 4],
       [2, 0, 1, 4, 5, 3],
       [3, 4, 5, 0, 1, 2],
       [4, 5, 3, 2, 0, 1],
       [5, 3, 4, 1, 2, 0]])

In [85]:
s3.table_column(0)

AttributeError: 'Group' object has no attribute 'table_column'

In [ ]:
s3.table_column(0)

In [ ]:
s3.table_column(2)

In [ ]:
def get_table_column(table, n):
    return [row[n] for row in table]

In [ ]:
s3.check_addition_table()

In [ ]:
tesseract.check_addition_table()

In [ ]:
len(tesseract.element_names)

In [ ]:
arr = [[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 0, 1], [3, 2, 1, 0]]

In [ ]:
np_arr = np.array(arr, dtype=np.int64)

In [ ]:
np_arr

In [ ]:
2**32