# Abstract Algebras

<i>Version 2</i>

## References

* [Group Explorer](https://nathancarter.github.io/group-explorer/index.html) -- Visualization software for the abstract algebra classroom
* [Groupprops, The Group Properties Wiki (beta)](https://groupprops.subwiki.org/wiki/Main_Page)
* [Klein four-group, V4](https://en.wikipedia.org/wiki/Klein_four-group)
* [Cyclic group](https://en.wikipedia.org/wiki/Cyclic_group)

## Imports and Paths

In [1]:
import algebras as alg
import numpy as np
import json
import os

In [2]:
# Path to this repo
aa_path = os.path.join(os.getenv('PYPROJ'), 'abstract_algebra')

# Path to a directory containing Algebra definitions in JSON
alg_dir = os.path.join(aa_path, "Algebras")

### A Very Simple Group

In [3]:
simp = alg.Group("Simple",
                 "A very simple group",
                 ["1", "-1"],
                 [[0, 1],
                  [1, 0]])

In [4]:
simp

Group('Simple', 'A very simple group', ['1', '-1'], [[0 1]
 [1 0]])

In [9]:
simp.addition_table_with_names()

[['1', '-1'], ['-1', '1']]

In [10]:
simp.abelian()

True

### Klein-4 Group

See this [definition at GitHub](https://github.com/nathancarter/group-explorer/blob/master/groups/V_4.group).

In [11]:
v4_json = os.path.join(alg_dir, "v4_klein_4_group.json")

!cat {v4_json}

{"type": "Group",
 "name": "V4",
 "description": "Klein-4 group",
 "element_names": ["e", "h", "v", "hv"],
 "addition_table": [[0, 1, 2, 3],
                    [1, 0, 3, 2],
                    [2, 3, 0, 1],
                    [3, 2, 1, 0]]
}


In [12]:
v4 = alg.Group(v4_json)
v4

Group('V4', 'Klein-4 group', ['e', 'h', 'v', 'hv'], [[0 1 2 3]
 [1 0 3 2]
 [2 3 0 1]
 [3 2 1 0]])

In [13]:
v4.to_dict()

{'type': 'Group',
 'name': 'V4',
 'description': 'Klein-4 group',
 'element_names': ['e', 'h', 'v', 'hv'],
 'addition_table': array([[0, 1, 2, 3],
        [1, 0, 3, 2],
        [2, 3, 0, 1],
        [3, 2, 1, 0]])}

In [14]:
v4.addition_table_with_names()

[['e', 'h', 'v', 'hv'],
 ['h', 'e', 'hv', 'v'],
 ['v', 'hv', 'e', 'h'],
 ['hv', 'v', 'h', 'e']]

In [15]:
v4.abelian()

True

In [16]:
v4.associative()

True

The group can also be created at the command line:

In [17]:
v4x = alg.Group('V4x',
                'Klein-4 group',
                ['e',  'h',  'v', 'hv'],
                [[0, 1, 2, 3],
                 [1, 0, 3, 2],
                 [2, 3, 0, 1],
                 [3, 2, 1, 0]]
               )

v4x

Group('V4x', 'Klein-4 group', ['e', 'h', 'v', 'hv'], [[0 1 2 3]
 [1 0 3 2]
 [2 3 0 1]
 [3 2 1 0]])

In [18]:
v4.add('h','v')

'hv'

In [19]:
for elem in v4.element_names:
    print(f"inv({elem}) = {v4.inverse(elem)}")

AttributeError: 'numpy.ndarray' object has no attribute 'index'

In [ ]:
print(v4)

In [ ]:
v4json = json.dumps(v4.to_dict())
v4json

### Cyclic group of order 4

See this [definition at GitHub](https://github.com/nathancarter/group-explorer/blob/master/groups/Z_4.group).

In [ ]:
z4 = alg.Group('Z4',
           'Cyclic group of order 4',
           ['e', 'a', 'a^2', 'a^3'],
           [[0, 1, 2, 3],
            [1, 2, 3, 0],
            [2, 3, 0, 1],
            [3, 0, 1, 2]]
          )

In [ ]:
z4.addition_table_with_names()

In [ ]:
print(z4)

In [ ]:
z4.add('a^2','a^2')

In [ ]:
z4.add('a^2', 'a^3')

In [ ]:
for elem in z4.element_names:
    print(f"inv({elem}) = {z4.inverse(elem)}")

In [ ]:
z4.abelian()

In [ ]:
z4.associative()

### Symmetric group on 3 letters

See this [definition at GitHub](https://github.com/nathancarter/group-explorer/blob/master/groups/S_3.group). "Another name for this group is "Dihedral group on 3 vertices."

In [ ]:
s3 = alg.Group('S3',
           'Symmetric group on 3 letters',
           ['e', 'r', 'r^2', 'f', 'fr', 'rf'],
           [[0, 1, 2, 3, 4, 5],
            [1, 2, 0, 5, 3, 4],
            [2, 0, 1, 4, 5, 3],
            [3, 4, 5, 0, 1, 2],
            [4, 5, 3, 2, 0, 1],
            [5, 3, 4, 1, 2, 0]]
          )

In [ ]:
s3.addition_table_with_names()

In [ ]:
print(s3)

In [ ]:
s3.add('fr', 'r^2')

In [ ]:
s3.abelian()

In [ ]:
s3.associative()

In [ ]:
for elem in s3.element_names:
    print(f"inv({elem}) = {s3.inverse(elem)}")

In [ ]:
s3

### Symmetric Group, S3 (not same as S3, above)

This is the [Symmetric group, S3, as specified at Groupprops](https://groupprops.subwiki.org/wiki/Symmetric_group:S3).

W.r.t., how to interpret the addition table, the following quote helps:

[[from Wikipedia](https://groupprops.subwiki.org/wiki/Symmetric_group:S3)] "We portray elements as permutations on the set \{ 1,2,3 \} using the cycle decomposition. The row element is added on the left and the column element on the right, with the assumption of functions written on the left. This means that the column element is applied first and the row element is applied next."

In [ ]:
s3x = alg.Group('S3X',
           'Another version of the symmetric group on 3 letters',
           ['()', '(1,2)', '(2,3)', '(1,3)', '(1,2,3)', '(1,3,2)'],
           [[0, 1, 2, 3, 4, 5],
            [1, 0, 4, 5, 2, 3],
            [2, 5, 0, 4, 3, 1],
            [3, 4, 5, 0, 1, 2],
            [4, 3, 1, 2, 5, 0],
            [5, 2, 3, 1, 0, 4]]
          )

In [ ]:
s3x.abelian()

In [ ]:
s3x.associative()

In [ ]:
s3x.addition_table_with_names()

In [ ]:
s3x.add('(1,2)', '(2,3)')

In [ ]:
for elem in s3x.element_names:
    print(f"inv({elem}) = {s3x.inverse(elem)}")

## Z_2 x Z_2 x Z_2

In [ ]:
Z2xZ2xZ2 = alg.Group('Z_2 x Z_2 x Z_2',
                 'no description',
                 ['eee', 'aee', 'eae', 'aae', 'eea', 'aea', 'eaa', 'aaa'],
                 [[0, 1, 2, 3, 4, 5, 6, 7],
                  [1, 0, 3, 2, 5, 4, 7, 6],
                  [2, 3, 0, 1, 6, 7, 4, 5],
                  [3, 2, 1, 0, 7, 6, 5, 4],
                  [4, 5, 6, 7, 0, 1, 2, 3],
                  [5, 4, 7, 6, 1, 0, 3, 2],
                  [6, 7, 4, 5, 2, 3, 0, 1],
                  [7, 6, 5, 4, 3, 2, 1, 0]]
                )

In [ ]:
Z2xZ2xZ2.abelian()

In [ ]:
Z2xZ2xZ2.associative()

In [ ]:
Z2xZ2xZ2.addition_table_with_names()

In [ ]:
for elem in Z2xZ2xZ2.element_names:
    print(f"inv({elem}) = {Z2xZ2xZ2.inverse(elem)}")

## Direct Products

In [ ]:
z2 = alg.Group('Z2',
           'Cyclic group of order 2',
           ['E', 'A'],
           [[0, 1],
            [1, 0]]
          )

z3 = alg.Group('Z3',
           'Cyclic group of order 3',
           ['E', 'A', 'B'],
           [[0, 1, 2],
            [1, 2, 0],
            [2, 0, 1]]
          )

In [ ]:
z3_x_z3 = z3 * z3
z3_x_z3

In [ ]:
z3_x_z3.element_names

In [ ]:
z3_x_z3.addition_table

In [ ]:
for elem in z3_x_z3.element_names:
    print(f"inv({elem}) = {z3_x_z3.inverse(elem)}")

In [ ]:
z3_x_z3.abelian()

In [ ]:
z3_x_z3.associative()

In [ ]:
z2_x_z2_x_z2 = z2 * z2 * z2

In [ ]:
z2_x_z2_x_z2.element_names

In [ ]:
z2_x_z2_x_z2.addition_table

In [ ]:
for elem in z2_x_z2_x_z2.element_names:
    print(f"inv({elem}) = {z2_x_z2_x_z2.inverse(elem)}")

## Tesseract group

This group has 384 elements and was converted to JSON from [this definition](https://github.com/nathancarter/group-explorer/blob/master/groups/Tesseract.group).

In [ ]:
tesseract_path = os.path.join(alg_dir, "tesseract.json")
tesseract = alg.Group(tesseract_path)
print(tesseract)

In [ ]:
tesseract.abelian()

In [ ]:
#tesseract.associative() # True

In [ ]:
len(tesseract.element_names)

Here are the first n elements:

In [ ]:
n = 25
tesseract.element_names[:n]

In [ ]:
tesseract.add('abab', 'baba')

## Scratch Work

In [ ]:
z3_x_z3

In [ ]:
z3_x_z3.element_names

In [ ]:
z3

In [ ]:
s3

In [ ]:
z3.set_direct_product_delimiter(':')

In [ ]:
foo = s3 * z3
foo

In [ ]:
foo.abelian()

In [ ]:
s3.addition_table

In [ ]:
s3.table_column(0)

In [ ]:
s3.table_column(0)

In [ ]:
s3.table_column(2)

In [ ]:
def get_table_column(table, n):
    return [row[n] for row in table]

In [ ]:
s3.check_addition_table()

In [ ]:
tesseract.check_addition_table()

In [ ]:
len(tesseract.element_names)

In [ ]:
arr = [[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 0, 1], [3, 2, 1, 0]]

In [ ]:
np_arr = np.array(arr, dtype=np.int64)

In [ ]:
np_arr

In [ ]:
2**32