# Example Groups

I'm using this notebook to implement example groups using the JSON format defined here.

Many of these groups were obtained from [Group Explorer](https://nathancarter.github.io/group-explorer/index.html): <i>"Visualization software for the abstract algebra classroom".</i>

In [1]:
import algebras as alg
import json
import os
import numpy as np

In [2]:
import itertools as it

In [3]:
# Path to this repo
aa_path = os.path.join(os.getenv('PYPROJ'), 'abstract_algebra')

# Path to a directory containing Algebra definitions in JSON
alg_dir = os.path.join(aa_path, "Algebras")

## S3 -- Symmetric Group on 3 Letters

In [4]:
s3_path = os.path.join(alg_dir, "s3_symmetric_group_on_3_letters.json")
!cat {s3_path}

{"type": "Group",
 "name": "S3",
 "description": "Symmetric group on 3 letters",
 "element_names": ["e", "r", "r^2", "f", "fr", "rf"],
 "mult_table": [[0, 1, 2, 3, 4, 5],
                [1, 2, 0, 5, 3, 4],
                [2, 0, 1, 4, 5, 3],
                [3, 4, 5, 0, 1, 2],
                [4, 5, 3, 2, 0, 1],
                [5, 3, 4, 1, 2, 0]]
}


In [5]:
s3 = alg.Group(s3_path)
s3.print_info()


Group : S3 : Symmetric group on 3 letters
  Element Names: ['e', 'r', 'r^2', 'f', 'fr', 'rf']
  Is Abelian? False
  Inverses:  (** - indicates that it is its own inverse)
    inv(e) = e   **
    inv(r) = r^2 
    inv(r^2) = r 
    inv(f) = f   **
    inv(fr) = fr   **
    inv(rf) = rf   **
  Is associative? True
  Cayley Table:
      e    r  r^2    f   fr   rf
      r  r^2    e   rf    f   fr
    r^2    e    r   fr   rf    f
      f   fr   rf    e    r  r^2
     fr   rf    f  r^2    e    r
     rf    f   fr    r  r^2    e


## Z2 (Cyclic Group of Order 2) with Direct Products: Z2_x_Z2 and Z2_x_Z2_x_Z2

In [6]:
z2 = alg.generate_cyclic_group(2)

z2xz2 = z2 * z2
z2xz2xz2 = z2 * z2 * z2

z2.print_info()
z2xz2.print_info()
z2xz2xz2.print_info()


Group : Z2 : Cyclic group of order 2
  Element Names: ['e', 'a']
  Is Abelian? True
  Inverses:  (** - indicates that it is its own inverse)
    inv(e) = e   **
    inv(a) = a   **
  Is associative? True
  Cayley Table:
    e  a
    a  e

Group : Z2_x_Z2 : Direct product of Z2 & Z2
  Element Names: ['e:e', 'e:a', 'a:e', 'a:a']
  Is Abelian? True
  Inverses:  (** - indicates that it is its own inverse)
    inv(e:e) = e:e   **
    inv(e:a) = e:a   **
    inv(a:e) = a:e   **
    inv(a:a) = a:a   **
  Is associative? True
  Cayley Table:
    e:e  e:a  a:e  a:a
    e:a  e:e  a:a  a:e
    a:e  a:a  e:e  e:a
    a:a  a:e  e:a  e:e

Group : Z2_x_Z2_x_Z2 : Direct product of Z2_x_Z2 & Z2
  Element Names: ['e:e:e', 'e:e:a', 'e:a:e', 'e:a:a', 'a:e:e', 'a:e:a', 'a:a:e', 'a:a:a']
  Is Abelian? True
  Inverses:  (** - indicates that it is its own inverse)
    inv(e:e:e) = e:e:e   **
    inv(e:e:a) = e:e:a   **
    inv(e:a:e) = e:a:e   **
    inv(e:a:a) = e:a:a   **
    inv(a:e:e) = a:e:e   **
    in

In [7]:
z2.proper_subgroups()

[]

In [8]:
z2xz2.proper_subgroups()

[Group('Z2_x_Z2_subgroup_0', 'Subgroup of: Direct product of Z2 & Z2', ['e:e', 'a:a'], [[0 1]
  [1 0]]) ,
 Group('Z2_x_Z2_subgroup_1', 'Subgroup of: Direct product of Z2 & Z2', ['e:e', 'a:e'], [[0 1]
  [1 0]]) ,
 Group('Z2_x_Z2_subgroup_2', 'Subgroup of: Direct product of Z2 & Z2', ['e:e', 'e:a'], [[0 1]
  [1 0]]) ]

In [9]:
z2xz2xz2_subgroups = z2xz2xz2.proper_subgroups()

In [10]:
len(z2xz2xz2_subgroups)

14

In [11]:
[g.order() for g in z2xz2xz2_subgroups]

[4, 4, 2, 2, 4, 2, 4, 2, 4, 2, 4, 4, 2, 2]

In [12]:
z2xz2xz2_subgroups

[Group('Z2_x_Z2_x_Z2_subgroup_0', 'Subgroup of: Direct product of Z2_x_Z2 & Z2', ['e:e:e', 'e:e:a', 'a:a:e', 'a:a:a'], [[0 1 2 3]
  [1 0 3 2]
  [2 3 0 1]
  [3 2 1 0]]) ,
 Group('Z2_x_Z2_x_Z2_subgroup_1', 'Subgroup of: Direct product of Z2_x_Z2 & Z2', ['e:e:e', 'e:a:a', 'a:e:a', 'a:a:e'], [[0 1 2 3]
  [1 0 3 2]
  [2 3 0 1]
  [3 2 1 0]]) ,
 Group('Z2_x_Z2_x_Z2_subgroup_2', 'Subgroup of: Direct product of Z2_x_Z2 & Z2', ['e:e:e', 'e:a:a'], [[0 1]
  [1 0]]) ,
 Group('Z2_x_Z2_x_Z2_subgroup_3', 'Subgroup of: Direct product of Z2_x_Z2 & Z2', ['e:e:e', 'a:a:e'], [[0 1]
  [1 0]]) ,
 Group('Z2_x_Z2_x_Z2_subgroup_4', 'Subgroup of: Direct product of Z2_x_Z2 & Z2', ['e:e:e', 'e:e:a', 'a:e:e', 'a:e:a'], [[0 1 2 3]
  [1 0 3 2]
  [2 3 0 1]
  [3 2 1 0]]) ,
 Group('Z2_x_Z2_x_Z2_subgroup_5', 'Subgroup of: Direct product of Z2_x_Z2 & Z2', ['e:e:e', 'e:a:e'], [[0 1]
  [1 0]]) ,
 Group('Z2_x_Z2_x_Z2_subgroup_6', 'Subgroup of: Direct product of Z2_x_Z2 & Z2', ['e:e:e', 'e:a:e', 'a:e:a', 'a:a:a'], [[0 1 2 3]


## Dihedral Group of Order 6

[See Wikipedia](https://en.wikipedia.org/wiki/Dihedral_group_of_order_6)

In [13]:
d3_path = os.path.join(alg_dir, "d3_dihedral_group_of_order_6.json")

!cat {d3_path}

{"type": "Group",
 "name": "D3",
 "description": "https://en.wikipedia.org/wiki/Dihedral_group_of_order_6",
 "element_names": ["e", "a", "b", "aba", "ab", "ba"],
 "mult_table": [[0, 1, 2, 3, 4, 5],
                [1, 0, 4, 5, 2, 3],
                [2, 5, 0, 4, 3, 1],
                [3, 4, 5, 0, 1, 2],
                [4, 3, 1, 2, 5, 0],
                [5, 2, 3, 1, 0, 4]]
}

In [14]:
d3 = alg.Group(d3_path)

d3.print_info()


Group : D3 : https://en.wikipedia.org/wiki/Dihedral_group_of_order_6
  Element Names: ['e', 'a', 'b', 'aba', 'ab', 'ba']
  Is Abelian? False
  Inverses:  (** - indicates that it is its own inverse)
    inv(e) = e   **
    inv(a) = a   **
    inv(b) = b   **
    inv(aba) = aba   **
    inv(ab) = ba 
    inv(ba) = ab 
  Is associative? True
  Cayley Table:
      e    a    b  aba   ab   ba
      a    e   ab   ba    b  aba
      b   ba    e   ab  aba    a
    aba   ab   ba    e    a    b
     ab  aba    a    b   ba    e
     ba    b  aba    a    e   ab


In [15]:
d3.proper_subgroups()

[Group('D3_subgroup_0', 'Subgroup of: https://en.wikipedia.org/wiki/Dihedral_group_of_order_6', ['e', 'a'], [[0 1]
  [1 0]]) ,
 Group('D3_subgroup_1', 'Subgroup of: https://en.wikipedia.org/wiki/Dihedral_group_of_order_6', ['e', 'b'], [[0 1]
  [1 0]]) ,
 Group('D3_subgroup_2', 'Subgroup of: https://en.wikipedia.org/wiki/Dihedral_group_of_order_6', ['e', 'aba'], [[0 1]
  [1 0]]) ,
 Group('D3_subgroup_3', 'Subgroup of: https://en.wikipedia.org/wiki/Dihedral_group_of_order_6', ['e', 'ab', 'ba'], [[0 1 2]
  [1 2 0]
  [2 0 1]]) ]

# More Groups...

## A4 -- Alternating Group on 4 Letters

In [16]:
a4_path = os.path.join(alg_dir, "a4_alternating_group_on_4_letters.json")
!cat {a4_path}

{"type": "Group",
 "name": "A_4",
 "description": "Alternating group on 4 letters (AKA Tetrahedral group)",
 "element_names": ["()", "(1 3 2)", "(1 2 3)", "(0 1)(2 3)", "(0 1 2)", "(0 1 3)", "(0 3 1)",
                   "(0 3 2)", "(0 3)(1 2)", "(0 2 3)", "(0 2 1)", "(0 2)(1 3)"],
 "mult_table": [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
                [1, 2, 0, 6, 7, 8, 10, 11, 9, 5, 3, 4],
                [2, 0, 1, 10, 11, 9, 3, 4, 5, 8, 6, 7],
                [3, 4, 5, 0, 1, 2, 9, 10, 11, 6, 7, 8],
                [4, 5, 3, 9, 10, 11, 7, 8, 6, 2, 0, 1],
                [5, 3, 4, 7, 8, 6, 0, 1, 2, 11, 9, 10],
                [6, 7, 8, 1, 2, 0, 5, 3, 4, 10, 11, 9],
                [7, 8, 6, 5, 3, 4, 11, 9, 10, 0, 1, 2],
                [8, 6, 7, 11, 9, 10, 1, 2, 0, 4, 5, 3],
                [9, 10, 11, 4, 5, 3, 2, 0, 1, 7, 8, 6],
                [10, 11, 9, 2, 0, 1, 8, 6, 7, 3, 4, 5],
                [11, 9, 10, 8, 6, 7, 4, 5, 3, 1, 2, 0]]
}


In [17]:
a4 = alg.Group(a4_path)

a4.print_info()


Group : A_4 : Alternating group on 4 letters (AKA Tetrahedral group)
  Element Names: ['()', '(1 3 2)', '(1 2 3)', '(0 1)(2 3)', '(0 1 2)', '(0 1 3)', '(0 3 1)', '(0 3 2)', '(0 3)(1 2)', '(0 2 3)', '(0 2 1)', '(0 2)(1 3)']
  Is Abelian? False
  Inverses:  (** - indicates that it is its own inverse)
    inv(()) = ()   **
    inv((1 3 2)) = (1 2 3) 
    inv((1 2 3)) = (1 3 2) 
    inv((0 1)(2 3)) = (0 1)(2 3)   **
    inv((0 1 2)) = (0 2 1) 
    inv((0 1 3)) = (0 3 1) 
    inv((0 3 1)) = (0 1 3) 
    inv((0 3 2)) = (0 2 3) 
    inv((0 3)(1 2)) = (0 3)(1 2)   **
    inv((0 2 3)) = (0 3 2) 
    inv((0 2 1)) = (0 1 2) 
    inv((0 2)(1 3)) = (0 2)(1 3)   **
  Is associative? True
  Cayley Table:
            ()     (1 3 2)     (1 2 3)  (0 1)(2 3)     (0 1 2)     (0 1 3)     (0 3 1)     (0 3 2)  (0 3)(1 2)     (0 2 3)     (0 2 1)  (0 2)(1 3)
       (1 3 2)     (1 2 3)          ()     (0 3 1)     (0 3 2)  (0 3)(1 2)     (0 2 1)  (0 2)(1 3)     (0 2 3)     (0 1 3)  (0 1)(2 3)     (0 1 2)
      

In [18]:
a4.proper_subgroups()

[Group('A_4_subgroup_0', 'Subgroup of: Alternating group on 4 letters (AKA Tetrahedral group)', ['()', '(0 1 2)', '(0 2 1)'], [[0 1 2]
  [1 2 0]
  [2 0 1]]) ,
 Group('A_4_subgroup_1', 'Subgroup of: Alternating group on 4 letters (AKA Tetrahedral group)', ['()', '(0 3 2)', '(0 2 3)'], [[0 1 2]
  [1 2 0]
  [2 0 1]]) ,
 Group('A_4_subgroup_2', 'Subgroup of: Alternating group on 4 letters (AKA Tetrahedral group)', ['()', '(0 2)(1 3)'], [[0 1]
  [1 0]]) ,
 Group('A_4_subgroup_3', 'Subgroup of: Alternating group on 4 letters (AKA Tetrahedral group)', ['()', '(0 1)(2 3)', '(0 3)(1 2)', '(0 2)(1 3)'], [[0 1 2 3]
  [1 0 3 2]
  [2 3 0 1]
  [3 2 1 0]]) ,
 Group('A_4_subgroup_4', 'Subgroup of: Alternating group on 4 letters (AKA Tetrahedral group)', ['()', '(0 1 3)', '(0 3 1)'], [[0 1 2]
  [1 2 0]
  [2 0 1]]) ,
 Group('A_4_subgroup_5', 'Subgroup of: Alternating group on 4 letters (AKA Tetrahedral group)', ['()', '(0 3)(1 2)'], [[0 1]
  [1 0]]) ,
 Group('A_4_subgroup_6', 'Subgroup of: Alternating g

## D4 -- Dihedral Group on Four Vertices

In [19]:
d4_path = os.path.join(alg_dir, "d4_dihedral_group_on_4_vertices.json")
!cat {d4_path}

{"type": "Group",
 "name": "D_4",
 "description": "Dihedral group on four vertices",
 "element_names": ["e", "r", "r^2", "r^3", "f", "fr", "r^2f", "rf"],
 "alt_elem_names": ["()", "(0 1 2 3)", "(0 2)(1 3)", "(0 3 2 1)",
                    "(0 1)(2 3)", "(1 3)", "(0 3)(1 2)", "(0 2)"],
 "mult_table": [[0, 1, 2, 3, 4, 5, 6, 7],
                [1, 2, 3, 0, 7, 4, 5, 6],
                [2, 3, 0, 1, 6, 7, 4, 5],
                [3, 0, 1, 2, 5, 6, 7, 4],
                [4, 5, 6, 7, 0, 1, 2, 3],
                [5, 6, 7, 4, 3, 0, 1, 2],
                [6, 7, 4, 5, 2, 3, 0, 1],
                [7, 4, 5, 6, 1, 2, 3, 0]]
}

In [20]:
d4 = alg.Group(d4_path)
d4.print_info()


Group : D_4 : Dihedral group on four vertices
  Element Names: ['e', 'r', 'r^2', 'r^3', 'f', 'fr', 'r^2f', 'rf']
  Is Abelian? False
  Inverses:  (** - indicates that it is its own inverse)
    inv(e) = e   **
    inv(r) = r^3 
    inv(r^2) = r^2   **
    inv(r^3) = r 
    inv(f) = f   **
    inv(fr) = fr   **
    inv(r^2f) = r^2f   **
    inv(rf) = rf   **
  Is associative? True
  Cayley Table:
       e     r   r^2   r^3     f    fr  r^2f    rf
       r   r^2   r^3     e    rf     f    fr  r^2f
     r^2   r^3     e     r  r^2f    rf     f    fr
     r^3     e     r   r^2    fr  r^2f    rf     f
       f    fr  r^2f    rf     e     r   r^2   r^3
      fr  r^2f    rf     f   r^3     e     r   r^2
    r^2f    rf     f    fr   r^2   r^3     e     r
      rf     f    fr  r^2f     r   r^2   r^3     e


In [21]:
d4.proper_subgroups()

[Group('D_4_subgroup_0', 'Subgroup of: Dihedral group on four vertices', ['e', 'r^2', 'f', 'r^2f'], [[0 1 2 3]
  [1 0 3 2]
  [2 3 0 1]
  [3 2 1 0]]) ,
 Group('D_4_subgroup_1', 'Subgroup of: Dihedral group on four vertices', ['e', 'r^2f'], [[0 1]
  [1 0]]) ,
 Group('D_4_subgroup_2', 'Subgroup of: Dihedral group on four vertices', ['e', 'r', 'r^2', 'r^3'], [[0 1 2 3]
  [1 2 3 0]
  [2 3 0 1]
  [3 0 1 2]]) ,
 Group('D_4_subgroup_3', 'Subgroup of: Dihedral group on four vertices', ['e', 'fr'], [[0 1]
  [1 0]]) ,
 Group('D_4_subgroup_4', 'Subgroup of: Dihedral group on four vertices', ['e', 'r^2', 'fr', 'rf'], [[0 1 2 3]
  [1 0 3 2]
  [2 3 0 1]
  [3 2 1 0]]) ,
 Group('D_4_subgroup_5', 'Subgroup of: Dihedral group on four vertices', ['e', 'r^2'], [[0 1]
  [1 0]]) ,
 Group('D_4_subgroup_6', 'Subgroup of: Dihedral group on four vertices', ['e', 'f'], [[0 1]
  [1 0]]) ,
 Group('D_4_subgroup_7', 'Subgroup of: Dihedral group on four vertices', ['e', 'rf'], [[0 1]
  [1 0]]) ]