# New Object Hierarchy

Version 2

In [1]:
from finite_algebras import *
from table_utils import *

### Magma Examples

#### Rock-Paper-Scisors Magma

This magma is obviously commutative, but not associative.

See https://en.wikipedia.org/wiki/Commutative_magma

* $M = \langle \{r,p,s\}, \cdot \rangle$
* For all $x, y \in M$, if $x$ *beats* $y$, then $x \cdot y = y \cdot x = x$
* Also, for all $x \in M$, $xx = x$

In [2]:
rps = Magma(['r', 'p', 's'], [[0, 1, 0], [1, 1, 2], [0, 2, 2]])
rps

Magma(
['r', 'p', 's'],
[[0, 1, 0], [1, 1, 2], [0, 2, 2]]
)

The following demonstrates that the rps magma is non-associative:

In [3]:
ps = rps.op('p', 's')
rp = rps.op('r', 'p')

r_ps = rps.op('r', ps)
rp_s = rps.op(rp, 's')

print(f"    r(ps) = r{ps} = {r_ps}, \nbut (rp)s = {rp}s = {rp_s}")

    r(ps) = rs = r, 
but (rp)s = ps = s


For other magma examples, [see this discussion](https://math.stackexchange.com/questions/779507/can-you-give-me-some-concrete-examples-of-magmas).  Also, [see this paper on groupiods](https://arxiv.org/ftp/math/papers/0304/0304490.pdf).

#### Smarandache Groupoid

This is Example 1.4.1 in the paper referenced, above.

In [4]:
ex141_tbl = [[0, 3, 0, 3, 0, 3], [1, 4, 1, 4, 1, 4], [2, 5, 2, 5, 2, 5],
             [3, 0, 3, 0, 3, 0], [4, 1, 4, 1, 4, 1], [5, 2, 5, 2, 5, 2]]

In [5]:
ex141_magma = Magma(['a', 'b', 'c', 'd', 'e', 'f'], ex141_tbl)
ex141_magma

Magma(
['a', 'b', 'c', 'd', 'e', 'f'],
[[0, 3, 0, 3, 0, 3], [1, 4, 1, 4, 1, 4], [2, 5, 2, 5, 2, 5], [3, 0, 3, 0, 3, 0], [4, 1, 4, 1, 4, 1], [5, 2, 5, 2, 5, 2]]
)

### Testing Magma Methods

#### Table and Element Accessors

In [6]:
rps.table

array([[0, 1, 0],
       [1, 1, 2],
       [0, 2, 2]])

In [7]:
rps.elements

['r', 'p', 's']

In [8]:
rps.table_with_names()

[['r', 'p', 'r'], ['p', 'p', 's'], ['r', 's', 's']]

#### Magma as an Iterator and Container of Elements

In [9]:
[el for el in rps]

['r', 'p', 's']

In [10]:
'r' in rps

True

#### Replacing ("Setting") Element Names

In [11]:
full_names = ['rock', 'paper', 'scissors']
rps.set_elements(full_names)

Magma(
['rock', 'paper', 'scissors'],
[[0, 1, 0], [1, 1, 2], [0, 2, 2]]
)

In [12]:
orig_elems = ['r', 'p', 's']
mapping = dict(zip(rps.elements, orig_elems))
print(mapping)
rps.set_elements(orig_elems)

{'rock': 'r', 'paper': 'p', 'scissors': 's'}


Magma(
['r', 'p', 's'],
[[0, 1, 0], [1, 1, 2], [0, 2, 2]]
)

### Testing Table Utilities

In [13]:
# not assoc; is comm; no identities -- the RPS magma table, above
tbl1 = [[0, 1, 0], [1, 1, 2], [0, 2, 2]]

# is assoc; not comm; has identity (0) --- the S3 group table
tbl2 = [[0, 1, 2, 3, 4, 5], [1, 2, 0, 5, 3, 4], [2, 0, 1, 4, 5, 3],
        [3, 4, 5, 0, 1, 2], [4, 5, 3, 2, 0, 1], [5, 3, 4, 1, 2, 0]]

# is assoc; is comm; has identity (0) --- the Z4 group table
tbl3 = [[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]]

# is assoc; is comm; has identity (0) --- powerset(3) group table
tbl4 = [[0, 1, 2, 3, 4, 5, 6, 7], [1, 0, 4, 5, 2, 3, 7, 6], [2, 4, 0, 6, 1, 7, 3, 5],
        [3, 5, 6, 0, 7, 1, 2, 4], [4, 2, 1, 7, 0, 6, 5, 3], [5, 3, 7, 1, 6, 0, 4, 2],
        [6, 7, 3, 2, 5, 4, 0, 1], [7, 6, 5, 4, 3, 2, 1, 0]]

# is assoc; is not comm; no left id; has right id --- Smarandache Groupoid (see above)
tbl5 = ex141_tbl

test_tables = [tbl1, tbl2, tbl3, tbl4, tbl5]

In [14]:
print("   Table  Associative?  Commutative?  Left Id?  Right Id?  Identity?")
print('-' * 75)
for tbl in test_tables:
    i = test_tables.index(tbl) + 1
    is_assoc = str(is_associative(tbl))
    is_comm = str(is_commutative(tbl))
    lft_id = str(has_left_identity(tbl))
    rgt_id = str(has_right_identity(tbl))
    ident = str(has_identity(tbl))
    print(f"{i :>{6}} {is_assoc :>{11}} {is_comm :>{12}} {lft_id :>{12}} {rgt_id :>{9}} {ident :>{10}}")

   Table  Associative?  Commutative?  Left Id?  Right Id?  Identity?
---------------------------------------------------------------------------
     1       False         True         None      None       None
     2        True        False            0         0          0
     3        True         True            0         0          0
     4        True         True            0         0          0
     5        True        False         None         0       None


In [15]:
np.array(tbl5)

array([[0, 3, 0, 3, 0, 3],
       [1, 4, 1, 4, 1, 4],
       [2, 5, 2, 5, 2, 5],
       [3, 0, 3, 0, 3, 0],
       [4, 1, 4, 1, 4, 1],
       [5, 2, 5, 2, 5, 2]])

In [32]:
table = np.array(tbl5)
id = 0
row_indices, col_indices = np.where(table == id)
list(zip(row_indices, col_indices))

[(0, 0), (0, 2), (0, 4), (3, 1), (3, 3), (3, 5)]

From the list of pairs, above, we see the following:
* 0 is a left-inverse of 3 other elements: 0, 2, & 4
* 3 is also a left-inverse of 3 other elements: 1, 3, & 5
* 3 also has 3 right-inverses: 1, 3, & 5

In [47]:
table = np.array(tbl5)
id = 0
row_indices, col_indices = np.where(table == id)
print(set(row_indices) == set(col_indices))
print(len(set(row_indices)) == len(table))

False
False


In [18]:
np.array(tbl2)

array([[0, 1, 2, 3, 4, 5],
       [1, 2, 0, 5, 3, 4],
       [2, 0, 1, 4, 5, 3],
       [3, 4, 5, 0, 1, 2],
       [4, 5, 3, 2, 0, 1],
       [5, 3, 4, 1, 2, 0]])

In [17]:
table = np.array(tbl2)
id = 0
row_indices, col_indices = np.where(table == id)
foo = zip(row_indices, col_indices)
list(foo)

[(0, 0), (1, 2), (2, 1), (3, 3), (4, 4), (5, 5)]

In [42]:
table = np.array(tbl2)
id = 0
row_indices, col_indices = np.where(table == id)
print(set(row_indices) == set(col_indices))
print(len(row_indices) == len(table))

True
True


## Semigroup

A semigroup is an associative magma.

In [ ]:
is_table_associative(rps.table)

The Semigroup constructor will fail if the table does not support associativity:

In [ ]:
try:
    Semigroup(['r', 'p', 's'], [[0, 1, 0], [1, 1, 2], [0, 2, 2]])
except:
    print("Something went wrong")

### See p. 67 in Pinter for a possible example

## Monoid

A monoid is a semigroup with an identity element.

**NEED TESTS AND EXAMPLES HERE**

## Group

A group is a monoid where every element has an inverse.

TBD