# Regular Representation

This section describes the method, ``regular_representation``, which is defined in the ``Monoid`` class, so it also holds for all classes that inherit from ``Monoid``, that is, ``Group``, ``Ring``, and ``Field``.

With respect to Rings and Fields, though, the regular representation only applies to the additive abelian Group of the Ring or Field.

## References

* Georgi, Howard (2018), <i>"Lie algebras in particle physics: from isospin to unified theories"</i>, CRC Press, [Open Access](https://www.taylorfrancis.com/books/oa-mono/10.1201/9780429499210/lie-algebras-particle-physics-howard-georgi?context=ubx&refId=1530fefc-3778-48ae-99ec-cba2935af2fb)
* Huang, Jiaqi (2012), <i>"Lie Groups and their applications to Particle Physics: A Tutorial for Undergraduate Physics Majors"</i>, [arXiv:2012.00834v1](https://arxiv.org/abs/2012.00834)

## Introduction

The following definition was adapted from [Georgi, 2018].

A <i>representation</i> of a group, $G = \langle A, \circ \rangle$, is a mapping, $V$, of the elements of $G$ onto a set of linear operators with the following properties:
* $V(e) = \hat{1}$, where $e$ is the group's identity element and $\hat{1}$ is the identity operator in the space on which the linear operators act
* $V(a_i) \cdot V(a_j) = V(a_i \circ a_j)$ for all $a_i, a_j \in A$. That is, the group multiplication law, "$\circ$", is mapped onto the matrix multiplication law, "$\cdot$".

The <i>regular representation</i> of a group is a mapping of each group element to an $nxn$ matrix. In this case, $\hat{1}$ is the $nxn$ identity matrix.

Most often, the term <i>regular representation</i> applies to groups, but the definition of a regular representation and the algorithm, to be provided below, doesn't preclude monoids from having regular representations also. The definition & algorithm require an algebra that has an identity element, but not necessarily inverses.

## Algorithm

The following algorithm for computing a regular representation was adapted from [Huang, 2012].

Let $G = \langle A, \circ \rangle$, be a group, where $A = \{a_0, a_1, \dots , a_{n - 1}\}$ is the set of the group's elements, and $\circ$ is its binary operator.

Also, let $B = \{\hat{b}_0, \hat{b}_1, \dots , \hat{b}_{n-1} \}$ be the following set of $nx1$ vectors:

$\hat{b}_0 = \begin{bmatrix}
1 \\
0 \\
0 \\
\vdots \\
0 \end{bmatrix},
\hat{b}_1 = \begin{bmatrix}
0 \\
1 \\
0 \\
\vdots \\
0 \end{bmatrix},
\dots,
\hat{b}_{n-1} = \begin{bmatrix}
0 \\
0 \\
0 \\
\vdots \\
1 \end{bmatrix}$

Define the a bijection between $A$ and $B$ as follows: $V(a_i) = \hat{b}_i$ for $i = 0, \dots , n - 1$.

Let $\cdot$ denote matrix-vector multiplication, and define the $nxn$ matrix,

$C_k = (c^k_{ij})_{i,j=0,\dots,n-1}$

where $c^k_{ij} = \hat{b}_i^T \cdot V(a_k \circ V^{-1}(\hat{b}_j))$



Then $M = \{C_0, C_1, \dots , C_{n - 1}\}$ is the <b>regular representation</b> of the group $G$, where the mapping between group elements and operators is $a_i \leftrightarrow C_i$ for $i = 0, \dots , n - 1$.

## Example: Cyclic Group, $Z_4$

In this example, we'll derive the regular representation of the cyclic group, $Z_4$, with elements, $A = \left\{ e, a, a^2, a^3 \right\}$.

In [1]:
import finite_algebras as alg

Z4 = alg.generate_cyclic_group(4)
Z4.about(use_table_names=True)


** Group **
Name: Z4
Instance ID: 4472505168
Description: Autogenerated cyclic Group of order 4
Order: 4
Identity: e
Commutative? Yes
Cyclic?: Yes
  Generators: ['a', 'a^3']
Elements:
   Index   Name   Inverse  Order
      0       e       e       1
      1       a     a^3       4
      2     a^2     a^2       2
      3     a^3       a       4
Cayley Table (showing names):
[['e', 'a', 'a^2', 'a^3'],
 ['a', 'a^2', 'a^3', 'e'],
 ['a^2', 'a^3', 'e', 'a'],
 ['a^3', 'e', 'a', 'a^2']]


``regular_representation`` returns the following four items:

1. A dictionary mapping each group element to its corresponding matrix
1. A dictionary mapping each matrix (in tuple of tuples form) to its corresponding group element
1. A function that takes a group element and returns the corresponding matrix
1. A function that takes a matrix and returns the corresponding group element

Now, here's the computation of the regular representation of $Z_4$:

In [2]:
elem_to_array_mapping, array_to_elem_mapping, elem_to_array_fnc, array_to_elem_fnc = Z4.regular_representation()

The following code depicts the element-to-array mapping:

In [3]:
for elem in Z4:
    print(elem)
    print(elem_to_array_mapping[elem])
    print()

e
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

a
[[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]

a^2
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]

a^3
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]



Here is the array-to-element mapping.

<b>NOTE</b>: Dictionary keys must be immutable. But NumPy arrays are mutable. So, the method, ``regular_representation``, transforms NumPy arrays to tuples of tuples, which <u>are</u> immutable, and then uses them as dictionary keys. The tuple of tuples are, essentially, sparse matrix representations, and this transformation works for both NumPy dense arrays or SciPy sparse arrays.

In [4]:
array_to_elem_mapping

{((0, 0), (1, 1), (2, 2), (3, 3)): 'e',
 ((0, 3), (1, 0), (2, 1), (3, 2)): 'a',
 ((0, 2), (1, 3), (2, 0), (3, 1)): 'a^2',
 ((0, 1), (1, 2), (2, 3), (3, 0)): 'a^3'}

Here is an example function call using the element to array function:

In [5]:
a3_array = elem_to_array_fnc('a^3')
a3_array

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.]])

And, here's an example of the array-to-element function that goes in the reverse direction:

In [6]:
array_to_elem_fnc(a3_array)

'a^3'

## Verification

The method, ``verify_regular_representation``, verifies that the two bulleted conditions in the Introduction section, above, hold true for a given regular representation.

It requires the two functions output by the regular representation method: element-to-array & array-to-element, in that order.

In [7]:
Z4.verify_regular_representation(elem_to_array_fnc, array_to_elem_fnc)

True

## Example: Klein-4 Group, $V_4$


In this example, we'll derive the regular representation of the Klein-4 group, $Z_4$, with elements, $A = \left\{ e, h, v, r \right\}$.

First, retrieve $V_4$ from the built-in examples:

In [8]:
import os
aa_path = os.path.join(os.getenv("PYPROJ"), "abstract_algebra")
alg_dir = os.path.join(aa_path, "Algebras")

ex = alg.Examples(alg_dir)

                           Example Algebras
----------------------------------------------------------------------
  17 example algebras are available.
  Use "Examples[INDEX]" to retrieve a specific example,
  where INDEX is the first number on each line below:
----------------------------------------------------------------------
0: A4 -- Alternating group on 4 letters (AKA Tetrahedral group)
1: D3 -- https://en.wikipedia.org/wiki/Dihedral_group_of_order_6
2: D4 -- Dihedral group on four vertices
3: Pinter29 -- Non-abelian group, p.29, 'A Book of Abstract Algebra' by Charles C. Pinter
4: RPS -- Rock, Paper, Scissors Magma
5: S3 -- Symmetric group on 3 letters
6: S3X -- Another version of the symmetric group on 3 letters
7: V4 -- Klein-4 group
8: Z4 -- Cyclic group of order 4
9: F4 -- Field with 4 elements (from Wikipedia)
10: mag_id -- Magma with Identity
11: Example 1.4.1 -- See: Groupoids and Smarandache Groupoids by W. B. Vasantha Kandasamy
12: Ex6 -- Example 6: http://www-groups.m

### $V_4$ the Klein-4 group

In [9]:
V4 = ex[7]
V4.about()


** Group **
Name: V4
Instance ID: 4482154640
Description: Klein-4 group
Order: 4
Identity: e
Commutative? Yes
Cyclic?: No
Elements:
   Index   Name   Inverse  Order
      0       e       e       1
      1       h       h       2
      2       v       v       2
      3       r       r       2
Cayley Table (showing indices):
[[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 0, 1], [3, 2, 1, 0]]


In [10]:
elem_to_array_mapping, X, Y, Z = V4.regular_representation()

In [11]:
V4.verify_regular_representation(Y, Z)

True

In [12]:
elem_to_array_mapping

{'e': array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]),
 'h': array([[0., 1., 0., 0.],
        [1., 0., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.]]),
 'v': array([[0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.]]),
 'r': array([[0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [1., 0., 0., 0.]])}

## Example: A Monoid

In [13]:
M6 = alg.generate_commutative_monoid(6)
M6.about()


** Monoid **
Name: M6
Instance ID: 4482036496
Description: Autogenerated commutative Monoid of order 6
Order: 6
Identity: a1
Associative? Yes
Commutative? Yes
Cyclic?: No
Elements: ['a0', 'a1', 'a2', 'a3', 'a4', 'a5']
Has Inverses? No
Cayley Table (showing indices):
[[0, 0, 0, 0, 0, 0],
 [0, 1, 2, 3, 4, 5],
 [0, 2, 4, 0, 2, 4],
 [0, 3, 0, 3, 0, 3],
 [0, 4, 2, 0, 4, 2],
 [0, 5, 4, 3, 2, 1]]


In [14]:
elem_to_array_mapping, X, Y, Z = M6.regular_representation()

In [15]:
M6.verify_regular_representation(Y, Z)

True

In [16]:
elem_to_array_mapping

{'a0': array([[1., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]),
 'a1': array([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]]),
 'a2': array([[1., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0.]]),
 'a3': array([[1., 0., 1., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 1., 0., 1.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]),
 'a4': array([[1., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0.],
        [0

## Optional Sparse Matrix Output

The following updated implementation includes a sparse matrix option.

By default, the matrices output by the reguarl representation method are dense arrays. SciPy sparse arrays can be output instead, by setting the input variable, <i>sparse</i>, to one of the following seven strings: "BSR", "COO", "CSC", "CSR", "DIA", "DOK", or "LIL". Each one of the seven strings corresponds to one of the seven classes of sparse array supported by SciPy.

## Example: Cyclic Group, $Z_4$, with "CSC" Sparse Matrix Output

CSC = Compressed Sparse Column, one of the seven sparse matrix formats supported by SciPy.

In [17]:
elem_to_array_mapping, array_to_elem_mapping, elem_to_array_fnc, array_to_elem_fnc = Z4.regular_representation("CSC")

In [18]:
elem_to_array_mapping

{'e': <4x4 sparse array of type '<class 'numpy.int64'>'
 	with 4 stored elements in Compressed Sparse Column format>,
 'a': <4x4 sparse array of type '<class 'numpy.int64'>'
 	with 4 stored elements in Compressed Sparse Column format>,
 'a^2': <4x4 sparse array of type '<class 'numpy.int64'>'
 	with 4 stored elements in Compressed Sparse Column format>,
 'a^3': <4x4 sparse array of type '<class 'numpy.int64'>'
 	with 4 stored elements in Compressed Sparse Column format>}

In [19]:
for elem in Z4:
    print(elem)
    print(elem_to_array_mapping[elem])
    print()

e
  (0, 0)	1
  (1, 1)	1
  (2, 2)	1
  (3, 3)	1

a
  (1, 0)	1
  (2, 1)	1
  (3, 2)	1
  (0, 3)	1

a^2
  (2, 0)	1
  (3, 1)	1
  (0, 2)	1
  (1, 3)	1

a^3
  (3, 0)	1
  (0, 1)	1
  (1, 2)	1
  (2, 3)	1



In [20]:
array_to_elem_mapping

{((0, 0), (1, 1), (2, 2), (3, 3)): 'e',
 ((0, 3), (1, 0), (2, 1), (3, 2)): 'a',
 ((0, 2), (1, 3), (2, 0), (3, 1)): 'a^2',
 ((0, 1), (1, 2), (2, 3), (3, 0)): 'a^3'}

In [21]:
a3_array = elem_to_array_fnc('a^3')
print(a3_array)

  (3, 0)	1
  (0, 1)	1
  (1, 2)	1
  (2, 3)	1


In [22]:
array_to_elem_fnc(a3_array)

'a^3'