# Regular Representation

Most often, the term <i>regular representation</i> applies to Groups, but it can also be applied to Monoids.

In [1]:
import os
aa_path = os.path.join(os.getenv("PYPROJ"), "abstract_algebra")
alg_dir = os.path.join(aa_path, "Algebras")

import finite_algebras as alg

## References

* Georgi, Howard (2018), <i>"Lie algebras in particle physics: from isospin to unified theories"</i>, CRC Press, [Open Access](https://www.taylorfrancis.com/books/oa-mono/10.1201/9780429499210/lie-algebras-particle-physics-howard-georgi?context=ubx&refId=1530fefc-3778-48ae-99ec-cba2935af2fb)
* Huang, Jiaqi (2012), <i>"Lie Groups and their applications to Particle Physics: A Tutorial for Undergraduate Physics Majors"</i>, [arXiv:2012.00834v1](https://arxiv.org/abs/2012.00834)

## Introduction

The following definition was adapted from the definition in [Georgi, 2018].

A <i>representation</i> of a group, $G = \langle A, \circ \rangle$, is a mapping, $V$, of the elements of $G$ onto a set of linear operators with the following properties:
* $V(e) = \hat{1}$, where $e$ is the group's identity element and $\hat{1}$ is the identity operator in the space on which the linear operators act
* $V(a_i) \cdot V(a_j) = V(a_i \circ a_j)$ for all $a_i, a_j \in A$. That is, the group multiplication law, "$\circ$", is mapped onto the linear multiplication law, "$\cdot$".

The <i>regular representation</i> of a group is a mapping of each group element to an $nxn$ matrix. In this case, $\hat{1}$ is the $nxn$ identity matrix.

For example, the regular representation of the cyclic group, $Z_4$, with elements, $A = \left\{ R_0, R_{90}, R_{180}, R_{270} \right\}$, consists of the mapping shown below, as a Python dictionary.

In [4]:
z4 = alg.generate_cyclic_group(4)
z4.about()


** Group **
Name: Z4
Instance ID: 4483376656
Description: Autogenerated cyclic Group of order 4
Order: 4
Identity: e
Commutative? Yes
Cyclic?: Yes
  Generators: ['a', 'a^3']
Elements:
   Index   Name   Inverse  Order
      0       e       e       1
      1       a     a^3       4
      2     a^2     a^2       2
      3     a^3       a       4
Cayley Table (showing indices):
[[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]]


In [7]:
z4_to_rr_mapping, rr_to_z4_mapping, elem_to_arr_fnc, arr_to_elem_fnc = z4.regular_representation()

for elem in z4:
    print(elem)
    print(z4_to_rr_mapping[elem])
    print()

e
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

a
[[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]

a^2
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]

a^3
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]



In [3]:
import numpy as np  # Use NumPy to represent matrices & vectors

z4_reg_rep = {
    'R0': np.array([[1, 0, 0, 0],
                    [0, 1, 0, 0],
                    [0, 0, 1, 0],
                    [0, 0, 0, 1]]),
    'R90': np.array([[0, 0, 0, 1],
                     [1, 0, 0, 0],
                     [0, 1, 0, 0],
                     [0, 0, 1, 0]]),
    'R180': np.array([[0, 0, 1, 0],
                      [0, 0, 0, 1],
                      [1, 0, 0, 0],
                      [0, 1, 0, 0]]),
    'R270': np.array([[0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1],
                      [1, 0, 0, 0]])
}

### Note on Monoids

The definition of a regular representation, given above, and the algorithm provided, below, doesn't preclude Monoids from having regular representations. The definition & algorithm require an algebra that has an identity element, but not necessarily inverses, that is a monoid. The discussion to follow will use groups as examples, but toward the end, some monoid examples will also be included.

## Algorithm

The following description of the algorithm for computing a regular representation was adapted from [Huang, 2012].

Let $G = \langle A, \circ \rangle$, be a group, where $A = \{a_0, a_1, \dots , a_{n - 1}\}$ is the set of the group's elements, and $\circ$ is its binary operator.

Also, let $B = \{\hat{b}_0, \hat{b}_1, \dots , \hat{b}_{n-1} \}$ be the following set of $nx1$ vectors:

$\hat{b}_0 = \begin{bmatrix}
1 \\
0 \\
0 \\
\vdots \\
0 \end{bmatrix},
\hat{b}_1 = \begin{bmatrix}
0 \\
1 \\
0 \\
\vdots \\
0 \end{bmatrix},
\dots,
\hat{b}_{n-1} = \begin{bmatrix}
0 \\
0 \\
0 \\
\vdots \\
1 \end{bmatrix}$

Define the a bijection between $A$ and $B$ as follows: $V(a_i) = \hat{b}_i$ for $i = 0, \dots , n - 1$.

Let $\cdot$ denote matrix-vector multiplication, and define the $nxn$ matrix,

$C_k = (c^k_{ij})_{i,j=0,\dots,n-1}$

where $c^k_{ij} = \hat{b}_i^T \cdot V(a_k \circ V^{-1}(\hat{b}_j))$



Then $M = \{C_0, C_1, \dots , C_{n - 1}\}$ is the <b>regular representation</b> of the group $G$, where the mapping between group elements and operators is $a_i \leftrightarrow C_i$ for $i = 0, \dots , n - 1$.

The purpose of the remainder of this notebook is to develop an implementation, within the module <b>finite_algebras</b>, that produces the mapping, $a_i \leftrightarrow C_i$, from a given group, $G$.

## A Small Test Group

In [3]:
import finite_algebras as alg

In [4]:
grp = alg.make_finite_algebra(
    'Z4',
    'Cyclic group of order 4',
    ['R0', 'R90', 'R180', 'R270'],
    [[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]]
)

grp.about()  # Displays information about the group


** Group **
Name: Z4
Instance ID: 4635460880
Description: Cyclic group of order 4
Order: 4
Identity: R0
Commutative? Yes
Cyclic?: Yes
  Generators: ['R270', 'R90']
Elements:
   Index   Name   Inverse  Order
      0      R0      R0       1
      1     R90    R270       4
      2    R180    R180       2
      3    R270     R90       4
Cayley Table (showing indices):
[[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]]


For convenience, the set of group elements will be denoted by $A$, and its order by $N$.

In [5]:
A = grp.elements
N = grp.order

## The Bijection between Group Elements and Vectors

First create a dictionary that maps each of the group's elements in $A$ to the $nx1$ vectors in $B$.

In [6]:
id = np.eye(N, dtype=int)  # The NxN identity matrix
B = [id[:,[i]] for i in range(N)]  # A list of the columns of the identity matrix
mapping = dict(zip(A, B))
mapping

{'R0': array([[1],
        [0],
        [0],
        [0]]),
 'R90': array([[0],
        [1],
        [0],
        [0]]),
 'R180': array([[0],
        [0],
        [1],
        [0]]),
 'R270': array([[0],
        [0],
        [0],
        [1]])}

The dictionary, above, maps group elements to "vectors" (NumPy arrays). To complete the bijection, we need another dictionary that goes in the reverse direction, that is, "vectors" to group elements. However, dictionary keys must be immutable, and NumPy arrays are mutable, so the code, below, transforms NumPy arrays to tuples, which <i>are</i> immutable, and can be used as dictionary keys.

In [7]:
def to_tuple(vec):
    '''Turns a column vector into a tuple, for use as a dictionary key.'''
    return tuple(map(lambda x: x[0], list(vec)))

inv_mapping = {to_tuple(val): key for key, val in mapping.items()}
inv_mapping

{(1, 0, 0, 0): 'R0',
 (0, 1, 0, 0): 'R90',
 (0, 0, 1, 0): 'R180',
 (0, 0, 0, 1): 'R270'}

Now define the bijection. That is, $V$, and its inverse, $V^{-1}$.

In [8]:
def V(elem):
    '''Given a group element, return the corresponding vector.'''
    return mapping[elem]

def Vinv(vec):
    '''Given a vector, return the corresponding element.'''
    return inv_mapping[to_tuple(vec)]

# Tests/Examples:
elem = A[1]
vec = V(elem)
elem2 = Vinv(vec)
print(elem)
print(vec)
print(elem2)

R90
[[0]
 [1]
 [0]
 [0]]
R90


## The Regular Representation Matrices

Now, the regular represention matrices can be derived using the formula presented in the Algorithm section, above,

$C_k = (c^k_{ij})_{i,j=0,\dots,n-1}$ where $c^k_{ij} = \hat{b}_i^T \cdot V(a_k \circ V^{-1}(\hat{b}_j))$

This is computed as follows:

In [9]:
reg_rep = dict()

for k in range(N):
    c_k = np.zeros((N, N))
    for i in range(N):
        for j in range(N):
            c_k[i][j] = np.dot(B[i].transpose(), V(grp.op(A[k], Vinv(B[j]))))
    reg_rep[A[k]] = c_k

reg_rep

{'R0': array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]),
 'R90': array([[0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]),
 'R180': array([[0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.]]),
 'R270': array([[0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.]])}

### Check Answer

Test to see if each matrix, computed for <b>reg_rep</b>, equals its counterpart in <b>z4_reg_rep</b>, defined in the Introduction section, above.

In [10]:
all([np.array_equal(reg_rep[elem], z4_reg_rep[elem]) for elem in grp.elements])

True

## Putting it All Together

Here is the desired implementation.

In [11]:
def regular_representation(grp):
    '''Given a group, this function returns three things: (1) A dictionary that maps each group
    element to its corresponding regular representation, (2) A function that maps a group element
    to its corresponding regular representation matrix, and (3) Another function that maps in the
    opposite direction, from regular represenation matrix to group element.'''
    
    A = grp.elements
    N = grp.order
    
    # Create a list of n nx1 orthogonal unit vectors
    id = np.eye(N, dtype=int)  # The nxn identity matrix
    B = [id[:,[i]] for i in range(N)]  # A list of the columns of the identity matrix
    
    # map group elements to vectors
    mapping = dict(zip(A, B))

    def V(elem):
        return mapping[elem]

    # Turn a column vector into a tuple, for use as a dict key
    def vector_to_tuple(vec):
        return tuple(map(lambda x: x[0], list(vec)))
    
    # map vectors to group elements
    inv_mapping = {vector_to_tuple(val): key for key, val in mapping.items()}
    
    def Vinv(vec):
        return inv_mapping[vector_to_tuple(vec)]
    
    # Derive the n nxn matrices of the regular representation
    reg_rep = dict()
    for k in range(N):
        c_k = np.zeros((N, N))
        for i in range(N):
            for j in range(N):
                c_k[i][j] = np.dot(B[i].transpose(), V(grp.op(A[k], Vinv(B[j]))))
        reg_rep[A[k]] = c_k
        
    def to_reg_rep(elem):
        '''Given a group element, return the corresponding regular representation matrix.'''
        return reg_rep[elem]
    
    def array_2d_to_tuple(arr):
        '''Turn a 2D nd.array into a tuple of tuples, for use as a dictionary key'''
        # return tuple(map(lambda x: tuple(x), np.ndarray.tolist(arr)))
        return tuple(zip(*arr.nonzero()))
    
    inv_mapping_2d = {array_2d_to_tuple(arr): key for key, arr in reg_rep.items()}
    
    def to_group_element(arr):
        '''Given a regular representation matrix, return the corresponding group element.'''
        return inv_mapping_2d[array_2d_to_tuple(arr)]
    
    def verify_regular_representation(reg_rep, grp):
        '''Verifies that rr(a) x rr(b) == rr(a * b), for all elements a & b of the group,
        where rr is the regular representation (maps group elements to reg reps), x is matrix
        multiplication, and * is the group operation.'''
        return all([np.array_equal(np.dot(to_reg_rep(a), to_reg_rep(b)), to_reg_rep(grp.op(a, b)))
                    for a in grp
                    for b in grp])
    
    if not verify_regular_representation(reg_rep, grp):
        raise AssertionError("Verification of Regular Represention failed")
        
    return reg_rep, to_reg_rep, to_group_element        

### Test/Example

A test and some printouts to see how it all works:

In [12]:
reg_rep, grp_to_rr, rr_to_grp = regular_representation(grp)

In [13]:
print(reg_rep)

{'R0': array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]]), 'R90': array([[0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]]), 'R180': array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]]), 'R270': array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.]])}


In [14]:
for elem in grp:
    print(elem)
    rr = grp_to_rr(elem)
    print(rr)
    print(rr_to_grp(rr))
    print('')

R0
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
R0

R90
[[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
R90

R180
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]
R180

R270
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]
R270



## More Tests / Examples

In [15]:
import os
aa_path = os.path.join(os.getenv("PYPROJ"), "abstract_algebra")
alg_dir = os.path.join(aa_path, "Algebras")

ex = alg.Examples(alg_dir)

                           Example Algebras
----------------------------------------------------------------------
  17 example algebras are available.
  Use "Examples[INDEX]" to retrieve a specific example,
  where INDEX is the first number on each line below:
----------------------------------------------------------------------
0: A4 -- Alternating group on 4 letters (AKA Tetrahedral group)
1: D3 -- https://en.wikipedia.org/wiki/Dihedral_group_of_order_6
2: D4 -- Dihedral group on four vertices
3: Pinter29 -- Non-abelian group, p.29, 'A Book of Abstract Algebra' by Charles C. Pinter
4: RPS -- Rock, Paper, Scissors Magma
5: S3 -- Symmetric group on 3 letters
6: S3X -- Another version of the symmetric group on 3 letters
7: V4 -- Klein-4 group
8: Z4 -- Cyclic group of order 4
9: F4 -- Field with 4 elements (from Wikipedia)
10: mag_id -- Magma with Identity
11: Example 1.4.1 -- See: Groupoids and Smarandache Groupoids by W. B. Vasantha Kandasamy
12: Ex6 -- Example 6: http://www-groups.m

### $S_3$ the symmetric group on 3 letters

In [16]:
s3 = ex[5]
s3.about()


** Group **
Name: S3
Instance ID: 4835882000
Description: Symmetric group on 3 letters
Order: 6
Identity: e
Commutative? No
Cyclic?: No
Elements:
   Index   Name   Inverse  Order
      0       e       e       1
      1       r     r^2       3
      2     r^2       r       3
      3       f       f       2
      4      fr      fr       2
      5      rf      rf       2
Cayley Table (showing indices):
[[0, 1, 2, 3, 4, 5],
 [1, 2, 0, 5, 3, 4],
 [2, 0, 1, 4, 5, 3],
 [3, 4, 5, 0, 1, 2],
 [4, 5, 3, 2, 0, 1],
 [5, 3, 4, 1, 2, 0]]


In [17]:
s3_reg_rep, s3_to_rr, rr_to_s3 = regular_representation(s3)

In [18]:
s3_reg_rep

{'e': array([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]]),
 'r': array([[0., 0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0., 0.]]),
 'r^2': array([[0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.]]),
 'f': array([[0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.]]),
 'fr': array([[0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [1.,

In [19]:
for elem in s3:
    print(elem)
    rr = s3_to_rr(elem)
    print(rr)
    print(rr_to_s3(rr))
    print('')

e
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
e

r
[[0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]]
r

r^2
[[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]
r^2

f
[[0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
f

fr
[[0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]]
fr

rf
[[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
rf



### $v_4$ the Klein-4 group

In [20]:
v4 = ex[7]
v4.about()


** Group **
Name: V4
Instance ID: 4634863696
Description: Klein-4 group
Order: 4
Identity: e
Commutative? Yes
Cyclic?: No
Elements:
   Index   Name   Inverse  Order
      0       e       e       1
      1       h       h       2
      2       v       v       2
      3       r       r       2
Cayley Table (showing indices):
[[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 0, 1], [3, 2, 1, 0]]


In [21]:
v4_reg_rep, v4_to_rr, rr_to_v4 = regular_representation(v4)

In [22]:
v4_reg_rep

{'e': array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]),
 'h': array([[0., 1., 0., 0.],
        [1., 0., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.]]),
 'v': array([[0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.]]),
 'r': array([[0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [1., 0., 0., 0.]])}

In [23]:
for elem in v4:
    print(elem)
    rr = v4_to_rr(elem)
    print(rr)
    print(rr_to_v4(rr))
    print('')

e
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
e

h
[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]
h

v
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]
v

r
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]
r



## Monoids Work as Well

In [24]:
m4 = alg.generate_commutative_monoid(4)
m4.about()


** Monoid **
Name: M4
Instance ID: 4841300816
Description: Autogenerated commutative Monoid of order 4
Order: 4
Identity: a1
Associative? Yes
Commutative? Yes
Cyclic?: No
Elements: ['a0', 'a1', 'a2', 'a3']
Has Inverses? No
Cayley Table (showing indices):
[[0, 0, 0, 0], [0, 1, 2, 3], [0, 2, 0, 2], [0, 3, 2, 1]]


In [25]:
m4_reg_rep, m4_to_rr, rr_to_m4 = regular_representation(m4)

In [26]:
m4_reg_rep

{'a0': array([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 'a1': array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]),
 'a2': array([[1., 0., 1., 0.],
        [0., 0., 0., 0.],
        [0., 1., 0., 1.],
        [0., 0., 0., 0.]]),
 'a3': array([[1., 0., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.]])}

In [27]:
m5 = alg.generate_commutative_monoid(5)
m5.about()


** Monoid **
Name: M5
Instance ID: 4841307600
Description: Autogenerated commutative Monoid of order 5
Order: 5
Identity: a1
Associative? Yes
Commutative? Yes
Cyclic?: No
Elements: ['a0', 'a1', 'a2', 'a3', 'a4']
Has Inverses? No
Cayley Table (showing indices):
[[0, 0, 0, 0, 0],
 [0, 1, 2, 3, 4],
 [0, 2, 4, 1, 3],
 [0, 3, 1, 4, 2],
 [0, 4, 3, 2, 1]]


In [28]:
m5_reg_rep, m5_to_rr, rr_to_m5 = regular_representation(m5)

In [29]:
m5_reg_rep

{'a0': array([[1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 'a1': array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]),
 'a2': array([[1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 1., 0., 0.]]),
 'a3': array([[1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.]]),
 'a4': array([[1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.]])}

## Conversion to Sparse Matrices

The module, [scipy.sparse](https://docs.scipy.org/doc/scipy/reference/sparse.html#), supports 7 different sparse matrix formats. The examples, below, use each one of the 7 to convert an existing regular representation mapping to one that contains sparse matrices.

In [30]:
import scipy.sparse as sp

sparse_matrix_converters = [sp.bsr_array, sp.coo_array, sp.csc_array, sp.csr_array,
                            sp.dia_array, sp.dok_array, sp.lil_array]

sparse_array_classes = {"BSR": sp.bsr_array,
                        "COO": sp.coo_array,
                        "CSC": sp.csc_array,
                        "CSR": sp.csr_array,
                        "DIA": sp.dia_array,
                        "DOK": sp.dok_array,
                        "LIL": sp.lil_array}


def sparse_matrix(regrep, converter):
    '''Convert a given regular representation to sparse matrix format'''
    return {key: converter(val, dtype=int) for key, val in regrep.items()}

In [31]:
for converter in sparse_matrix_converters:

    sp_rr = sparse_matrix(reg_rep, converter)
    
    print("\n-----------------------")
    print(f"{converter}\n")

    # This printout provides a view into the sparse matrix representation used
    for key in sp_rr:
        print(f"{key}:\n{sp_rr[key]}\n")

    # Example that turns a sparse matrix into a tuple
    R90 = sp_rr['R90']
    print(tuple(zip(*R90.nonzero())))

    print(f"\n{sp_rr}")


-----------------------
<class 'scipy.sparse._bsr.bsr_array'>

R0:
  (0, 0)	1
  (1, 1)	1
  (2, 2)	1
  (3, 3)	1

R90:
  (0, 3)	1
  (1, 0)	1
  (2, 1)	1
  (3, 2)	1

R180:
  (0, 2)	1
  (1, 3)	1
  (2, 0)	1
  (3, 1)	1

R270:
  (0, 1)	1
  (1, 2)	1
  (2, 3)	1
  (3, 0)	1

((0, 3), (1, 0), (2, 1), (3, 2))

{'R0': <4x4 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements (blocksize = 1x1) in Block Sparse Row format>, 'R90': <4x4 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements (blocksize = 1x1) in Block Sparse Row format>, 'R180': <4x4 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements (blocksize = 1x1) in Block Sparse Row format>, 'R270': <4x4 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements (blocksize = 1x1) in Block Sparse Row format>}

-----------------------
<class 'scipy.sparse._coo.coo_array'>

R0:
  (0, 0)	1
  (1, 1)	1
  (2, 2)	1
  (3, 3)	1

R90:
  (0, 3)	1
  (1, 0)	1
  (2, 1)	1
  (3, 2)	1

R180:
  (0, 2)	1
  (

## Adding the Sparse Option

The following updated implementation includes a sparse matrix option.

In [32]:
import scipy.sparse as sp

def regular_representation_2(grp, sparse=False):
    '''Given a group, this function returns four things: (1) A dictionary that maps each group
    element to its corresponding regular representation, (2) A (reverse) dictionary that maps each
    regular representation (in the form of a tuple of tuples) back to its corresponding group element,
    (3) A function that maps a group element to its corresponding regular representation matrix, and
    (4) Another function that maps in the opposite direction, from regular represenation matrix to
    group element. By default, the matrices are dense arrays. SciPy sparse arrays can be output instead,
    by setting the input variable, "sparse", to one of the following seven strings: "BSR", "COO", "CSC",
    "CSR", "DIA", "DOK", or "LIL". Each of the seven strings corresponds to one of the seven classes of
    sparse array supported by SciPy.
    '''
    
    A = grp.elements
    N = grp.order
    
    # Create a list of N Nx1 orthogonal unit vectors
    id = np.eye(N, dtype=int)  # The NxN identity matrix
    B = [id[:,[i]] for i in range(N)]  # A list of columns extracted from the identity matrix
    
    # Create a dictionary that maps group elements to the column vectors created above.
    mapping = dict(zip(A, B))

    # Create a function that takes a group element and returns the corresponding Nx1
    # orthogonal unit vector.
    def V(elem):
        return mapping[elem]

    # Turn a column vector into a tuple, for use as a dict key
    def vector_to_tuple(vec):
        return tuple(map(lambda x: x[0], list(vec)))
    
    # map vectors to group elements
    inv_mapping = {vector_to_tuple(val): key for key, val in mapping.items()}

    # Given one of the Nx1 orthogonal unit vectors, return the corresponding group element
    def Vinv(vec):
        return inv_mapping[vector_to_tuple(vec)]

    # The seven SciPy sparse array class constructors
    sparse_array_classes = {
        "BSR": sp.bsr_array,
        "COO": sp.coo_array,
        "CSC": sp.csc_array,
        "CSR": sp.csr_array,
        "DIA": sp.dia_array,
        "DOK": sp.dok_array,
        "LIL": sp.lil_array}
    
    # Create a dictionary that maps each group element to its corresponding
    # regular representation (NxN) matrix.
    reg_rep = dict()
    for k in range(N):
        c_k = np.zeros((N, N))
        for i in range(N):
            for j in range(N):
                c_k[i][j] = np.dot(B[i].transpose(), V(grp.op(A[k], Vinv(B[j]))))
        if sparse in sparse_array_classes:
            reg_rep[A[k]] = sparse_array_classes[sparse](c_k, dtype=int)
        else:
            reg_rep[A[k]] = c_k
        
    # Create a function that takes a group element and returns the corresponding regular
    # representation matrix, using the dictionary created above.
    def element_to_array(elem):
        return reg_rep[elem]
    
    # Create a function that turns a 2-dimensional nd.array into a tuple of tuples,
    # for use as a dictionary key. This works for both dense and sparse arrays.
    def array_to_tuple(arr):
        return tuple(zip(*arr.nonzero()))

    # Create a reverse dictionary that maps each regular representation matrix (in tuple form)
    # to its corresponding group element.
    inv_reg_rep = {array_to_tuple(arr): key for key, arr in reg_rep.items()}
    
    # Create a function that takes a regular representation matrix and returns the corresponding
    # group element, using the reverse dictionary created above.
    def array_to_element(arr):
        return inv_reg_rep[array_to_tuple(arr)]
    
    return reg_rep, inv_reg_rep, element_to_array, array_to_element    

In [33]:
def verify_regular_representation(elem_to_arr, grp):
    '''Verifies that rr(a) x rr(b) == rr(a * b), for all elements a & b of the group,
    where rr is the regular representation (maps group elements to reg reps), x is matrix
    multiplication, and * is the group operation.'''
    return all([np.array_equal(np.dot(elem_to_arr(a), elem_to_arr(b)), elem_to_arr(grp.op(a, b)))
                for a in grp
                for b in grp])

In [34]:
s3_reg_rep_x, s3_reg_rep_inv_x, s3_to_rr_x, rr_to_s3_x = regular_representation_2(s3) # sparse='CSC')

In [35]:
s3_reg_rep_x

{'e': array([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]]),
 'r': array([[0., 0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0., 0.]]),
 'r^2': array([[0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.]]),
 'f': array([[0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.]]),
 'fr': array([[0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [1.,

In [36]:
s3_reg_rep_inv_x

{((0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)): 'e',
 ((0, 2), (1, 0), (2, 1), (3, 4), (4, 5), (5, 3)): 'r',
 ((0, 1), (1, 2), (2, 0), (3, 5), (4, 3), (5, 4)): 'r^2',
 ((0, 3), (1, 4), (2, 5), (3, 0), (4, 1), (5, 2)): 'f',
 ((0, 4), (1, 5), (2, 3), (3, 2), (4, 0), (5, 1)): 'fr',
 ((0, 5), (1, 3), (2, 4), (3, 1), (4, 2), (5, 0)): 'rf'}

In [37]:
foo = s3_to_rr_x('f')
print(foo)

[[0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [38]:
rr_to_s3_x(foo)

'f'

In [39]:
verify_regular_representation(s3_to_rr_x, s3)

True