## Example in Pinter (Chapter 3)

This is an example of a group from Pinter's book, at the end of chapter 3.

In [1]:
import numpy as np
import finite_algebras as falg

In [2]:
I = np.array([[1, 0],
              [0, 1]],
             dtype=int)

A = np.array([[0, 1],
              [1, 0]],
             dtype=int)

B = np.array([[ 0,  1],
              [-1, -1]],
             dtype=int)

C = np.array([[-1, -1],
              [ 0,  1]],
             dtype=int)

D = np.array([[-1, -1],
              [ 1,  0]],
             dtype=int)

K = np.array([[ 1,  0],
              [-1, -1]],
             dtype=int)

The Python *dictionary*, ``elem_dict``, below, maps element names (str) to elements (NumPy arrays).

In [3]:
elem_dict = {'I': I, 'A': A, 'B': B, 'C': C, 'D': D, 'K': K}

for name in elem_dict:
    print(f"\n{name!r}: ")
    print(elem_dict[name])


'I': 
[[1 0]
 [0 1]]

'A': 
[[0 1]
 [1 0]]

'B': 
[[ 0  1]
 [-1 -1]]

'C': 
[[-1 -1]
 [ 0  1]]

'D': 
[[-1 -1]
 [ 1  0]]

'K': 
[[ 1  0]
 [-1 -1]]


The function, ``generate_algebra_from_element_dict`` will generate the closure of a dictionary of elements, such as those created above, and then return the *finite algebra* defined by the closure.

Here is the inline documentation of the function:

In [4]:
help(falg.generate_algebra_from_element_dict)

Help on function generate_algebra_from_element_dict in module finite_algebras:

generate_algebra_from_element_dict(
    gen_elem_dict,
    bin_op,
    elem_eq,
    make_key,
    make_elem_key,
    name='Whatever',
    description='Created from a set of generators',
    max_iter=100
)
    Return an algebra, an element mapping, and iteration counter, given...

    (1) gen_elem_dict: a dictionary of generator elements, where the keys
    are unique string names of the elements, and the values are the actual element
    objects (e.g., numbers, matrices, etc.),

    (2) bin_op: a binary operation that combines the two element values into a new value,

    (3) elem_eq: a binary operation that returns True if the two element values are equal,

    (4) make_key: a function that takes a generator element and returns an immutable object
        to be used as a dictionary key.

    (5) make_elem_name: a function of three arguments, where the first two arguments
        are assumed to be element k

In [5]:
pinter_group, pinter_elem_mapping, iterations = \
    falg.generate_algebra_from_element_dict(
        elem_dict,  # The dictionary of four starting matrices
        lambda x, y: x @ y,  # Matrix multiplication (NumPy)
        lambda x, y: np.array_equal(x, y),  # Matrices equal? (NumPy)
        lambda x: falg.np_arr_to_tuple(x),  # Matrix to immutable tuple (for reverse dict keys)
        lambda x, y, z: x + y,  # Combine the two keys (str) into one; ignore z
        "PinterEx",  # Name of algebra to be produced
        "Group example in Pinter, chapter 3")  # Description of algebra

In [6]:
print(f"Number of iterations: {iterations}")

Number of iterations: 0


If the number of iterations is 0, then the elements passed in via ``elem_dict`` were already closed.

In [7]:
pinter_group.about(use_table_names=True)


** Group **
Name: PinterEx
Instance ID: 4781022848
Description: Group example in Pinter, chapter 3
Order: 6
Identity: 'I'
Commutative? No
Cyclic?: No
Elements:
   Index   Name   Inverse  Order
      0     'I'     'I'       1
      1     'A'     'A'       2
      2     'B'     'D'       3
      3     'C'     'C'       2
      4     'D'     'B'       3
      5     'K'     'K'       2
Cayley Table (showing names):
[['I', 'A', 'B', 'C', 'D', 'K'],
 ['A', 'I', 'C', 'B', 'K', 'D'],
 ['B', 'K', 'D', 'A', 'I', 'C'],
 ['C', 'D', 'K', 'I', 'A', 'B'],
 ['D', 'C', 'I', 'K', 'B', 'A'],
 ['K', 'B', 'A', 'D', 'C', 'I']]


'<Group:PinterEx, ID:4781022848>'

Out of curiosity, what subgroups exist for this group?

In [8]:
subs = falg.about_subalgebras(pinter_group)


Subalgebras of <Group:PinterEx, ID:4781022848>
  There are 2 unique proper subalgebras, up to isomorphism, out of 4 total subalgebras.
  as shown by the partitions below:

3 Isomorphic Commutative Groups of order 2 with identity 'I':
      Group: PinterEx_subalgebra_0: ('I', 'A')
      Group: PinterEx_subalgebra_1: ('I', 'C')
      Group: PinterEx_subalgebra_2: ('I', 'K')

1 Commutative Normal Group of order 3 with identity 'I':
      Group: PinterEx_subalgebra_3: ('I', 'B', 'D')



Looking at the results above, it looks like we might be able to generate the same (up to isomorphism) group from just the three elements: {B, D, K}

So, let's try that.

In [9]:
small_elem_dict = {'B': B, 'D': D, 'K': K}
small_elem_dict

{'B': array([[ 0,  1],
        [-1, -1]]),
 'D': array([[-1, -1],
        [ 1,  0]]),
 'K': array([[ 1,  0],
        [-1, -1]])}

In [10]:
pinter_group_2, pinter_elem_mapping_2, iterations_2 = \
    falg.generate_algebra_from_element_dict(
        small_elem_dict,  # just the elements {B, D, K}
        lambda x, y: x @ y,
        lambda x, y: np.array_equal(x, y),
        lambda x: falg.np_arr_to_tuple(x),
        lambda x, y, z: x + y,
        "PinterEx2",
        "Group example in Pinter, generated from just {B, D, K}")

We get 6 elements in the closure, as expected.

In [11]:
pinter_elem_mapping_2

for name in pinter_elem_mapping_2:
    print(f"\n{name!r}: ")
    print(pinter_elem_mapping_2[name])


'B': 
[[ 0  1]
 [-1 -1]]

'D': 
[[-1 -1]
 [ 1  0]]

'K': 
[[ 1  0]
 [-1 -1]]

'BD': 
[[1 0]
 [0 1]]

'BK': 
[[-1 -1]
 [ 0  1]]

'DK': 
[[0 1]
 [1 0]]


And, here's the group generated by the closure.

In [12]:
pinter_group_2.about(use_table_names=True)


** Group **
Name: PinterEx2
Instance ID: 4780813360
Description: Group example in Pinter, generated from just {B, D, K}
Order: 6
Identity: 'BD'
Commutative? No
Cyclic?: No
Elements:
   Index   Name   Inverse  Order
      0     'B'     'D'       3
      1     'D'     'B'       3
      2     'K'     'K'       2
      3    'BD'    'BD'       1
      4    'BK'    'BK'       2
      5    'DK'    'DK'       2
Cayley Table (showing names):
[['D', 'BD', 'BK', 'B', 'DK', 'K'],
 ['BD', 'B', 'DK', 'D', 'K', 'BK'],
 ['DK', 'BK', 'BD', 'K', 'D', 'B'],
 ['B', 'D', 'K', 'BD', 'BK', 'DK'],
 ['K', 'DK', 'B', 'BK', 'BD', 'D'],
 ['BK', 'K', 'D', 'DK', 'B', 'BD']]


'<Group:PinterEx2, ID:4780813360>'

Let's check that the generated group is isomorphic to the original group.

In [13]:
pinter_iso = pinter_group.isomorphic(pinter_group_2)
pinter_iso

{'I': 'BD', 'A': 'K', 'B': 'B', 'C': 'DK', 'D': 'D', 'K': 'BK'}

The group method, ``isomorphic``, finds and returns the first isomorphism that works. If others, exist, they are not returned.

The isomorphism, returned above, is not what I might have guessed it would be, so let's check it, below.

In [14]:
is_iso = True  # Assume the isomorphism above is correct

for a1 in pinter_iso:    # For an element, a1, fron the original group
    b1 = pinter_iso[a1]  # and it's corresponding element, b1, in the generated group
    for a2 in pinter_iso:    # ditto...
        b2 = pinter_iso[a2]  # ditto...
        a1_x_a2  = pinter_group.op(a1, a2)  # Product of elements in original group
        a1_x_a2_mapped = pinter_iso[a1_x_a2]  # Map product to generated group
        b1_x_b2 = pinter_group_2.op(b1, b2)  # Product of elements in generated group
        if a1_x_a2_mapped == b1_x_b2:  # For an isomorphism, this should always be True
            pass
        else:
            is_iso = False  # Set False if the isomorphism is NOT correct

print(f"{is_iso = }")

is_iso = True
