# Scratchwork

This notebook is only used for trying out ideas.

In [1]:
import algebras as alg
import json
import os
import numpy as np
import itertools as it
from pprint import pprint

from itertools import combinations, permutations, product

In [2]:
# Path to this repo
aa_path = os.path.join(os.getenv('PYPROJ'), 'abstract_algebra')

# Path to a directory containing Algebra definitions in JSON
alg_dir = os.path.join(aa_path, "Algebras")

## Groups for Testing

### D4 - Dihedral Group on 4 Vertices

In [3]:
d4_path = os.path.join(alg_dir, "d4_dihedral_group_on_4_vertices.json")
!cat {d4_path}

{"type": "Group",
 "name": "D_4",
 "description": "Dihedral group on four vertices",
 "element_names": ["e", "r", "r^2", "r^3", "f", "fr", "r^2f", "rf"],
 "alt_elem_names": ["()", "(0 1 2 3)", "(0 2)(1 3)", "(0 3 2 1)",
                    "(0 1)(2 3)", "(1 3)", "(0 3)(1 2)", "(0 2)"],
 "mult_table": [[0, 1, 2, 3, 4, 5, 6, 7],
                [1, 2, 3, 0, 7, 4, 5, 6],
                [2, 3, 0, 1, 6, 7, 4, 5],
                [3, 0, 1, 2, 5, 6, 7, 4],
                [4, 5, 6, 7, 0, 1, 2, 3],
                [5, 6, 7, 4, 3, 0, 1, 2],
                [6, 7, 4, 5, 2, 3, 0, 1],
                [7, 4, 5, 6, 1, 2, 3, 0]]
}

In [4]:
d4 = alg.Group(d4_path)
d4.print_info()


Group : D_4 : Dihedral group on four vertices
  Element Names: ['e', 'r', 'r^2', 'r^3', 'f', 'fr', 'r^2f', 'rf']
  Is Abelian? False
  Inverses:  (** - indicates that it is its own inverse)
    inv(e) = e   **
    inv(r) = r^3 
    inv(r^2) = r^2   **
    inv(r^3) = r 
    inv(f) = f   **
    inv(fr) = fr   **
    inv(r^2f) = r^2f   **
    inv(rf) = rf   **
Element Orders:
{1: ['e'], 2: ['r^2', 'f', 'fr', 'r^2f', 'rf'], 4: ['r', 'r^3']}
  Is associative? True
  Cayley Table:
[['e', 'r', 'r^2', 'r^3', 'f', 'fr', 'r^2f', 'rf'],
 ['r', 'r^2', 'r^3', 'e', 'rf', 'f', 'fr', 'r^2f'],
 ['r^2', 'r^3', 'e', 'r', 'r^2f', 'rf', 'f', 'fr'],
 ['r^3', 'e', 'r', 'r^2', 'fr', 'r^2f', 'rf', 'f'],
 ['f', 'fr', 'r^2f', 'rf', 'e', 'r', 'r^2', 'r^3'],
 ['fr', 'r^2f', 'rf', 'f', 'r^3', 'e', 'r', 'r^2'],
 ['r^2f', 'rf', 'f', 'fr', 'r^2', 'r^3', 'e', 'r'],
 ['rf', 'f', 'fr', 'r^2f', 'r', 'r^2', 'r^3', 'e']]


### V4 - Klein 4 Group

In [5]:
v4_path = os.path.join(alg_dir, "v4_klein_4_group.json")
!cat {v4_path}

{"type": "Group",
 "name": "V4",
 "description": "Klein-4 group",
 "element_names": ["e", "h", "v", "hv"],
 "mult_table": [[0, 1, 2, 3],
                [1, 0, 3, 2],
                [2, 3, 0, 1],
                [3, 2, 1, 0]]
}


In [6]:
v4 = alg.Group(v4_path)
v4.print_info()


Group : V4 : Klein-4 group
  Element Names: ['e', 'h', 'v', 'hv']
  Is Abelian? True
  Inverses:  (** - indicates that it is its own inverse)
    inv(e) = e   **
    inv(h) = h   **
    inv(v) = v   **
    inv(hv) = hv   **
Element Orders:
{1: ['e'], 2: ['h', 'v', 'hv']}
  Is associative? True
  Cayley Table:
[['e', 'h', 'v', 'hv'],
 ['h', 'e', 'hv', 'v'],
 ['v', 'hv', 'e', 'h'],
 ['hv', 'v', 'h', 'e']]


## Changing the Order of Elements

<b>Observation</b>: If the group is abelian, then changing the order of the elements does <b>not</b> affect the order of the indices in the <i>mult_table</i>.  <b>Why?</b>

In [7]:
# new_elem_order = v4.element_names
# new_v4_elem_order = ['e', 'v', 'h', 'hv']
new_v4_elem_order = ["e", "hv", "h", "v"]

In [8]:
#table_from_reordered_elements(v4, new_v4_elem_order)
v4_reordered = v4.reorder_elements(new_v4_elem_order)
v4_reordered

Group('V4_REORDERED',
'Klein-4 group (elements reordered)',
['e', 'hv', 'h', 'v'],
[[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 0, 1], [3, 2, 1, 0]]) 

In [9]:
pprint(v4_reordered.mult_table_with_names())

[['e', 'hv', 'h', 'v'],
 ['hv', 'e', 'v', 'h'],
 ['h', 'v', 'e', 'hv'],
 ['v', 'h', 'hv', 'e']]


In [10]:
v4_reordered.mult_table

array([[0, 1, 2, 3],
       [1, 0, 3, 2],
       [2, 3, 0, 1],
       [3, 2, 1, 0]])

In [11]:
pprint(v4.mult_table_with_names())

[['e', 'h', 'v', 'hv'],
 ['h', 'e', 'hv', 'v'],
 ['v', 'hv', 'e', 'h'],
 ['hv', 'v', 'h', 'e']]


In [12]:
v4.mult_table

array([[0, 1, 2, 3],
       [1, 0, 3, 2],
       [2, 3, 0, 1],
       [3, 2, 1, 0]])

In [13]:
new_d4_elem_order = ["e", "r", "r^2", "f", "r^3", "fr", "r^2f", "rf"]

In [14]:
d4_reordered = d4.reorder_elements(new_d4_elem_order)
d4_reordered

Group('D_4_REORDERED',
'Dihedral group on four vertices (elements reordered)',
['e', 'r', 'r^2', 'f', 'r^3', 'fr', 'r^2f', 'rf'],
[[0, 1, 2, 3, 4, 5, 6, 7], [1, 2, 4, 7, 0, 3, 5, 6], [2, 4, 0, 6, 1, 7, 3, 5], [3, 5, 6, 0, 7, 1, 2, 4], [4, 0, 1, 5, 2, 6, 7, 3], [5, 6, 7, 4, 3, 0, 1, 2], [6, 7, 3, 2, 5, 4, 0, 1], [7, 3, 5, 1, 6, 2, 4, 0]]) 

In [15]:
d4_reordered.mult_table

array([[0, 1, 2, 3, 4, 5, 6, 7],
       [1, 2, 4, 7, 0, 3, 5, 6],
       [2, 4, 0, 6, 1, 7, 3, 5],
       [3, 5, 6, 0, 7, 1, 2, 4],
       [4, 0, 1, 5, 2, 6, 7, 3],
       [5, 6, 7, 4, 3, 0, 1, 2],
       [6, 7, 3, 2, 5, 4, 0, 1],
       [7, 3, 5, 1, 6, 2, 4, 0]])

In [16]:
d4.mult_table

array([[0, 1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 0, 7, 4, 5, 6],
       [2, 3, 0, 1, 6, 7, 4, 5],
       [3, 0, 1, 2, 5, 6, 7, 4],
       [4, 5, 6, 7, 0, 1, 2, 3],
       [5, 6, 7, 4, 3, 0, 1, 2],
       [6, 7, 4, 5, 2, 3, 0, 1],
       [7, 4, 5, 6, 1, 2, 3, 0]])

In [17]:
d4.element_orders()

{'e': 1, 'r': 4, 'r^2': 2, 'r^3': 4, 'f': 2, 'fr': 2, 'r^2f': 2, 'rf': 2}

In [18]:
d4_reordered.element_orders()

{'e': 1, 'r': 4, 'r^2': 2, 'f': 2, 'r^3': 4, 'fr': 2, 'r^2f': 2, 'rf': 2}

## Generating Possible Multiplication Tables

In [19]:
foo = alg.generate_all_group_tables(4)
foo

[([0, 1, 2, 3], (1, 0, 3, 2), (2, 3, 0, 1), (3, 2, 1, 0)),
 ([0, 1, 2, 3], (1, 0, 3, 2), (2, 3, 1, 0), (3, 2, 0, 1)),
 ([0, 1, 2, 3], (1, 2, 3, 0), (2, 3, 0, 1), (3, 0, 1, 2)),
 ([0, 1, 2, 3], (1, 3, 0, 2), (2, 0, 3, 1), (3, 2, 1, 0))]

In [20]:
for t in foo:
    pprint(np.array(t))

array([[0, 1, 2, 3],
       [1, 0, 3, 2],
       [2, 3, 0, 1],
       [3, 2, 1, 0]])
array([[0, 1, 2, 3],
       [1, 0, 3, 2],
       [2, 3, 1, 0],
       [3, 2, 0, 1]])
array([[0, 1, 2, 3],
       [1, 2, 3, 0],
       [2, 3, 0, 1],
       [3, 0, 1, 2]])
array([[0, 1, 2, 3],
       [1, 3, 0, 2],
       [2, 0, 3, 1],
       [3, 2, 1, 0]])


In [21]:
foobar = alg.tables_to_groups(foo)
#for fb in foobar:
#    fb.pprint()

g0 = foobar[0]
g1 = foobar[1]
g2 = foobar[2]
g3 = foobar[3]

In [22]:
[g for g in foobar if g.associative()]

[Group('G0',
 'Group 0 of order 4',
 ['e0', 'a01', 'a02', 'a03'],
 [[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 0, 1], [3, 2, 1, 0]]) ,
 Group('G1',
 'Group 1 of order 4',
 ['e1', 'a11', 'a12', 'a13'],
 [[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 1, 0], [3, 2, 0, 1]]) ,
 Group('G2',
 'Group 2 of order 4',
 ['e2', 'a21', 'a22', 'a23'],
 [[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]]) ,
 Group('G3',
 'Group 3 of order 4',
 ['e3', 'a31', 'a32', 'a33'],
 [[0, 1, 2, 3], [1, 3, 0, 2], [2, 0, 3, 1], [3, 2, 1, 0]]) ]

## G0

In [23]:
g0

Group('G0',
'Group 0 of order 4',
['e0', 'a01', 'a02', 'a03'],
[[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 0, 1], [3, 2, 1, 0]]) 

## G1

In [24]:
g1  # Same as v4 and z2_x_z2, below

Group('G1',
'Group 1 of order 4',
['e1', 'a11', 'a12', 'a13'],
[[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 1, 0], [3, 2, 0, 1]]) 

In [25]:
v4.pprint()

Group('V4',
'Klein-4 group',
['e', 'h', 'v', 'hv'],
[[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 0, 1], [3, 2, 1, 0]]
)


In [26]:
z2 = alg.generate_cyclic_group(2)
#z2.pprint()

z2_x_z2 = z2 * z2
z2_x_z2.pprint()

Group('Z2_x_Z2',
'Direct product of Z2 & Z2',
['e:e', 'e:a', 'a:e', 'a:a'],
[[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 0, 1], [3, 2, 1, 0]]
)


## G2

In [27]:
g2  # Same as z4, below

Group('G2',
'Group 2 of order 4',
['e2', 'a21', 'a22', 'a23'],
[[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]]) 

In [28]:
z4 = alg.generate_cyclic_group(4)
z4

Group('Z4',
'Cyclic group of order 4',
['e', 'a', 'a^2', 'a^3'],
[[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]]) 

## G3

In [29]:
g3

Group('G3',
'Group 3 of order 4',
['e3', 'a31', 'a32', 'a33'],
[[0, 1, 2, 3], [1, 3, 0, 2], [2, 0, 3, 1], [3, 2, 1, 0]]) 

## Groups of Prime Order

In [30]:
order = 5

In [31]:
cyclic_group = alg.generate_cyclic_group(order)

In [32]:
cyclic_group.pprint()

Group('Z5',
'Cyclic group of order 5',
['e', 'a', 'a^2', 'a^3', 'a^4'],
[[0, 1, 2, 3, 4],
 [1, 2, 3, 4, 0],
 [2, 3, 4, 0, 1],
 [3, 4, 0, 1, 2],
 [4, 0, 1, 2, 3]]
)


In [33]:
all_tables = alg.generate_all_group_tables(order)
len(all_tables)

56

In [34]:
all_groups = alg.tables_to_groups(all_tables)
for grp in all_groups:
    grp.pprint()

Group('G0',
'Group 0 of order 5',
['e0', 'a01', 'a02', 'a03', 'a04'],
[[0, 1, 2, 3, 4],
 [1, 0, 3, 4, 2],
 [2, 3, 4, 0, 1],
 [3, 4, 1, 2, 0],
 [4, 2, 0, 1, 3]]
)
Group('G1',
'Group 1 of order 5',
['e1', 'a11', 'a12', 'a13', 'a14'],
[[0, 1, 2, 3, 4],
 [1, 0, 3, 4, 2],
 [2, 3, 4, 1, 0],
 [3, 4, 0, 2, 1],
 [4, 2, 1, 0, 3]]
)
Group('G2',
'Group 2 of order 5',
['e2', 'a21', 'a22', 'a23', 'a24'],
[[0, 1, 2, 3, 4],
 [1, 0, 3, 4, 2],
 [2, 4, 0, 1, 3],
 [3, 2, 4, 0, 1],
 [4, 3, 1, 2, 0]]
)
Group('G3',
'Group 3 of order 5',
['e3', 'a31', 'a32', 'a33', 'a34'],
[[0, 1, 2, 3, 4],
 [1, 0, 3, 4, 2],
 [2, 4, 1, 0, 3],
 [3, 2, 4, 1, 0],
 [4, 3, 0, 2, 1]]
)
Group('G4',
'Group 4 of order 5',
['e4', 'a41', 'a42', 'a43', 'a44'],
[[0, 1, 2, 3, 4],
 [1, 0, 4, 2, 3],
 [2, 3, 0, 4, 1],
 [3, 4, 1, 0, 2],
 [4, 2, 3, 1, 0]]
)
Group('G5',
'Group 5 of order 5',
['e5', 'a51', 'a52', 'a53', 'a54'],
[[0, 1, 2, 3, 4],
 [1, 0, 4, 2, 3],
 [2, 3, 1, 4, 0],
 [3, 4, 0, 1, 2],
 [4, 2, 3, 0, 1]]
)
Group('G6',
'Group 6 of orde

In [35]:
[g for g in all_groups if g.abelian()]

[Group('G14',
 'Group 14 of order 5',
 ['e14', 'a141', 'a142', 'a143', 'a144'],
 [[0, 1, 2, 3, 4], [1, 2, 3, 4, 0], [2, 3, 4, 0, 1], [3, 4, 0, 1, 2], [4, 0, 1, 2, 3]]) ,
 Group('G23',
 'Group 23 of order 5',
 ['e23', 'a231', 'a232', 'a233', 'a234'],
 [[0, 1, 2, 3, 4], [1, 2, 4, 0, 3], [2, 4, 3, 1, 0], [3, 0, 1, 4, 2], [4, 3, 0, 2, 1]]) ,
 Group('G24',
 'Group 24 of order 5',
 ['e24', 'a241', 'a242', 'a243', 'a244'],
 [[0, 1, 2, 3, 4], [1, 3, 0, 4, 2], [2, 0, 4, 1, 3], [3, 4, 1, 2, 0], [4, 2, 3, 0, 1]]) ,
 Group('G38',
 'Group 38 of order 5',
 ['e38', 'a381', 'a382', 'a383', 'a384'],
 [[0, 1, 2, 3, 4], [1, 3, 4, 2, 0], [2, 4, 1, 0, 3], [3, 2, 0, 4, 1], [4, 0, 3, 1, 2]]) ,
 Group('G40',
 'Group 40 of order 5',
 ['e40', 'a401', 'a402', 'a403', 'a404'],
 [[0, 1, 2, 3, 4], [1, 4, 0, 2, 3], [2, 0, 3, 4, 1], [3, 2, 4, 1, 0], [4, 3, 1, 0, 2]]) ,
 Group('G50',
 'Group 50 of order 5',
 ['e50', 'a501', 'a502', 'a503', 'a504'],
 [[0, 1, 2, 3, 4], [1, 4, 3, 0, 2], [2, 3, 1, 4, 0], [3, 0, 4, 2, 1], 

## Mapping a Group to another Group

In [36]:
elems0 = ['e0', 'a01', 'a02', 'a03']
elems1 = ['e1', 'a11', 'a12', 'a13']

In [37]:
print(z4.element_names)
print(g2.element_names)
#z4_g2_mappings = element_mappings(z4, g2)
z4_g2_mappings = z4.element_mappings(g2)
z4_g2_mappings

['e', 'a', 'a^2', 'a^3']
['e2', 'a21', 'a22', 'a23']


[{'a': 'a21', 'a^2': 'a22', 'a^3': 'a23', 'e': 'e2'},
 {'a': 'a21', 'a^2': 'a23', 'a^3': 'a22', 'e': 'e2'},
 {'a': 'a22', 'a^2': 'a21', 'a^3': 'a23', 'e': 'e2'},
 {'a': 'a22', 'a^2': 'a23', 'a^3': 'a21', 'e': 'e2'},
 {'a': 'a23', 'a^2': 'a21', 'a^3': 'a22', 'e': 'e2'},
 {'a': 'a23', 'a^2': 'a22', 'a^3': 'a21', 'e': 'e2'}]

In [38]:
m0 = z4_g2_mappings[0]
# all([ m0[z4.mult(x, y)] == g2.mult(m0[x], m0[y]) for x in z4.element_names for y in z4.element_names ])

In [39]:
# isomorphic_mapping(m0, z4, g2)
z4.isomorphic_mapping(g2, m0)

True

In [40]:
# Try it the other way around
# g2_z2_mappings = element_mappings(g2, z4)
g2_z2_mappings = g2.element_mappings(z4)
m0x = g2_z2_mappings[0]
# isomorphic_mapping(m0x, g2, z4)
g2.isomorphic_mapping(z4, m0x)

True

In [41]:
z4.isomorphic(g2)

{'a': 'a21', 'a^2': 'a22', 'a^3': 'a23', 'e': 'e2'}

In [42]:
g2.isomorphic(z4)

{'a21': 'a', 'a22': 'a^2', 'a23': 'a^3', 'e2': 'e'}

In [43]:
foobar

[Group('G0',
 'Group 0 of order 4',
 ['e0', 'a01', 'a02', 'a03'],
 [[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 0, 1], [3, 2, 1, 0]]) ,
 Group('G1',
 'Group 1 of order 4',
 ['e1', 'a11', 'a12', 'a13'],
 [[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 1, 0], [3, 2, 0, 1]]) ,
 Group('G2',
 'Group 2 of order 4',
 ['e2', 'a21', 'a22', 'a23'],
 [[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]]) ,
 Group('G3',
 'Group 3 of order 4',
 ['e3', 'a31', 'a32', 'a33'],
 [[0, 1, 2, 3], [1, 3, 0, 2], [2, 0, 3, 1], [3, 2, 1, 0]]) ]

In [44]:
for combo in combinations(foobar,2):
    mp = combo[0].isomorphic(combo[1])
    if mp:
        print(combo[0].name, combo[1].name, mp)

G1 G2 {'a11': 'a22', 'a12': 'a21', 'a13': 'a23', 'e1': 'e2'}
G1 G3 {'a11': 'a33', 'a12': 'a31', 'a13': 'a32', 'e1': 'e3'}
G2 G3 {'a21': 'a31', 'a22': 'a33', 'a23': 'a32', 'e2': 'e3'}


### U(5) = {1, 2, 3, 4} under multiplication modulo 5

See Ref: "Subgroups of Order 4 (PDF)"

In [ ]:
order = 4

In [57]:
[[((a * b) % order) for b in range(1, order)] for a in range(1, order)]

[[1, 2, 3, 4], [2, 4, 1, 3], [3, 1, 4, 2], [4, 3, 2, 1]]

In [58]:
def group_generate_1(order, identity_name="e", elem_name="a", name=None, description=None):
    """Returns a Group with the input order, where 'order' is a positive integer."""
    if name:
        nm = name
    else:
        nm = "Z" + str(order)
    if description:
        desc = description
    else:
        desc = f"Group of order {order}"
    elements = [identity_name, elem_name] + [f"{elem_name}" + str(i) for i in range(2, order)]
    table = [[((a * b) % (order + 1)) for b in range(1, order + 1)] for a in range(1, order + 1)]
    return alg.Group(nm, desc, elements, table)

In [59]:
group_generate_1(4)

ValueError: A row 0 does not contain the correct values