# Scratchwork

This notebook is only used for trying out ideas.

In [1]:
import algebras as alg
import json
import os
import numpy as np
import itertools as it
# from pprint import pprint
import pprint as pp

# from itertools import combinations, permutations, product
import itertools as it

In [2]:
# Path to this repo
aa_path = os.path.join(os.getenv('PYPROJ'), 'abstract_algebra')

# Path to a directory containing Algebra definitions in JSON
alg_dir = os.path.join(aa_path, "Algebras")

## Groups for Testing

### D4 - Dihedral Group on 4 Vertices

In [3]:
d4_path = os.path.join(alg_dir, "d4_dihedral_group_on_4_vertices.json")
!cat {d4_path}

{"type": "Group",
 "name": "D_4",
 "description": "Dihedral group on four vertices",
 "element_names": ["e", "r", "r^2", "r^3", "f", "fr", "r^2f", "rf"],
 "alt_elem_names": ["()", "(0 1 2 3)", "(0 2)(1 3)", "(0 3 2 1)",
                    "(0 1)(2 3)", "(1 3)", "(0 3)(1 2)", "(0 2)"],
 "mult_table": [[0, 1, 2, 3, 4, 5, 6, 7],
                [1, 2, 3, 0, 7, 4, 5, 6],
                [2, 3, 0, 1, 6, 7, 4, 5],
                [3, 0, 1, 2, 5, 6, 7, 4],
                [4, 5, 6, 7, 0, 1, 2, 3],
                [5, 6, 7, 4, 3, 0, 1, 2],
                [6, 7, 4, 5, 2, 3, 0, 1],
                [7, 4, 5, 6, 1, 2, 3, 0]]
}

In [4]:
d4 = alg.Group(d4_path)
d4.print_info()


Group : D_4 : Dihedral group on four vertices
  Element Names: ['e', 'r', 'r^2', 'r^3', 'f', 'fr', 'r^2f', 'rf']
  Is Abelian? False
  Inverses:  (** - indicates that it is its own inverse)
    inv(e) = e   **
    inv(r) = r^3 
    inv(r^2) = r^2   **
    inv(r^3) = r 
    inv(f) = f   **
    inv(fr) = fr   **
    inv(r^2f) = r^2f   **
    inv(rf) = rf   **
Element Orders:
{1: ['e'], 2: ['r^2', 'f', 'fr', 'r^2f', 'rf'], 4: ['r', 'r^3']}
  Is associative? True
  Cayley Table:
[['e', 'r', 'r^2', 'r^3', 'f', 'fr', 'r^2f', 'rf'],
 ['r', 'r^2', 'r^3', 'e', 'rf', 'f', 'fr', 'r^2f'],
 ['r^2', 'r^3', 'e', 'r', 'r^2f', 'rf', 'f', 'fr'],
 ['r^3', 'e', 'r', 'r^2', 'fr', 'r^2f', 'rf', 'f'],
 ['f', 'fr', 'r^2f', 'rf', 'e', 'r', 'r^2', 'r^3'],
 ['fr', 'r^2f', 'rf', 'f', 'r^3', 'e', 'r', 'r^2'],
 ['r^2f', 'rf', 'f', 'fr', 'r^2', 'r^3', 'e', 'r'],
 ['rf', 'f', 'fr', 'r^2f', 'r', 'r^2', 'r^3', 'e']]


### V4 - Klein 4 Group

In [5]:
v4_path = os.path.join(alg_dir, "v4_klein_4_group.json")
!cat {v4_path}

{"type": "Group",
 "name": "V4",
 "description": "Klein-4 group",
 "element_names": ["e", "h", "v", "hv"],
 "mult_table": [[0, 1, 2, 3],
                [1, 0, 3, 2],
                [2, 3, 0, 1],
                [3, 2, 1, 0]]
}


In [6]:
v4 = alg.Group(v4_path)
v4.print_info()


Group : V4 : Klein-4 group
  Element Names: ['e', 'h', 'v', 'hv']
  Is Abelian? True
  Inverses:  (** - indicates that it is its own inverse)
    inv(e) = e   **
    inv(h) = h   **
    inv(v) = v   **
    inv(hv) = hv   **
Element Orders:
{1: ['e'], 2: ['h', 'v', 'hv']}
  Is associative? True
  Cayley Table:
[['e', 'h', 'v', 'hv'],
 ['h', 'e', 'hv', 'v'],
 ['v', 'hv', 'e', 'h'],
 ['hv', 'v', 'h', 'e']]


In [7]:
z2 = alg.generate_cyclic_group(2)
z2

Group('Z2',
'Autogenerated cyclic group of order 2',
['e', 'a'],
[[0, 1], [1, 0]]) 

In [8]:
z2_x_z2 = z2 * z2
z2_x_z2

Group('Z2_x_Z2',
'Direct product of Z2 & Z2',
['e:e', 'e:a', 'a:e', 'a:a'],
[[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 0, 1], [3, 2, 1, 0]]) 

In [9]:
z4 = alg.generate_cyclic_group(4)
z4

Group('Z4',
'Autogenerated cyclic group of order 4',
['e', 'a', 'a^2', 'a^3'],
[[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]]) 

## Changing the Order of Elements

<b>Observation</b>: If the group is abelian, then changing the order of the elements does <b>not</b> affect the order of the indices in the <i>mult_table</i>.  <b>Why?</b>

In [10]:
# new_elem_order = v4.element_names
# new_v4_elem_order = ['e', 'v', 'h', 'hv']
new_v4_elem_order = ["e", "hv", "h", "v"]

In [11]:
#table_from_reordered_elements(v4, new_v4_elem_order)
v4_reordered = v4.reorder_elements(new_v4_elem_order)
v4_reordered

Group('V4_REORDERED',
'Klein-4 group (elements reordered)',
['e', 'hv', 'h', 'v'],
[[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 0, 1], [3, 2, 1, 0]]) 

In [12]:
pp.pprint(v4_reordered.mult_table_with_names())

[['e', 'hv', 'h', 'v'],
 ['hv', 'e', 'v', 'h'],
 ['h', 'v', 'e', 'hv'],
 ['v', 'h', 'hv', 'e']]


In [13]:
v4_reordered.mult_table

array([[0, 1, 2, 3],
       [1, 0, 3, 2],
       [2, 3, 0, 1],
       [3, 2, 1, 0]])

In [14]:
pp.pprint(v4.mult_table_with_names())

[['e', 'h', 'v', 'hv'],
 ['h', 'e', 'hv', 'v'],
 ['v', 'hv', 'e', 'h'],
 ['hv', 'v', 'h', 'e']]


In [15]:
v4.mult_table

array([[0, 1, 2, 3],
       [1, 0, 3, 2],
       [2, 3, 0, 1],
       [3, 2, 1, 0]])

In [16]:
new_d4_elem_order = ["e", "r", "r^2", "f", "r^3", "fr", "r^2f", "rf"]

In [17]:
d4_reordered = d4.reorder_elements(new_d4_elem_order)
d4_reordered

Group('D_4_REORDERED',
'Dihedral group on four vertices (elements reordered)',
['e', 'r', 'r^2', 'f', 'r^3', 'fr', 'r^2f', 'rf'],
[[0, 1, 2, 3, 4, 5, 6, 7], [1, 2, 4, 7, 0, 3, 5, 6], [2, 4, 0, 6, 1, 7, 3, 5], [3, 5, 6, 0, 7, 1, 2, 4], [4, 0, 1, 5, 2, 6, 7, 3], [5, 6, 7, 4, 3, 0, 1, 2], [6, 7, 3, 2, 5, 4, 0, 1], [7, 3, 5, 1, 6, 2, 4, 0]]) 

In [18]:
d4_reordered.mult_table

array([[0, 1, 2, 3, 4, 5, 6, 7],
       [1, 2, 4, 7, 0, 3, 5, 6],
       [2, 4, 0, 6, 1, 7, 3, 5],
       [3, 5, 6, 0, 7, 1, 2, 4],
       [4, 0, 1, 5, 2, 6, 7, 3],
       [5, 6, 7, 4, 3, 0, 1, 2],
       [6, 7, 3, 2, 5, 4, 0, 1],
       [7, 3, 5, 1, 6, 2, 4, 0]])

In [19]:
d4.mult_table

array([[0, 1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 0, 7, 4, 5, 6],
       [2, 3, 0, 1, 6, 7, 4, 5],
       [3, 0, 1, 2, 5, 6, 7, 4],
       [4, 5, 6, 7, 0, 1, 2, 3],
       [5, 6, 7, 4, 3, 0, 1, 2],
       [6, 7, 4, 5, 2, 3, 0, 1],
       [7, 4, 5, 6, 1, 2, 3, 0]])

In [20]:
d4.element_orders()

{'e': 1, 'r': 4, 'r^2': 2, 'r^3': 4, 'f': 2, 'fr': 2, 'r^2f': 2, 'rf': 2}

In [21]:
d4_reordered.element_orders()

{'e': 1, 'r': 4, 'r^2': 2, 'f': 2, 'r^3': 4, 'fr': 2, 'r^2f': 2, 'rf': 2}

## Generating Possible Multiplication Tables

In [22]:
tables4 = alg.generate_all_group_tables(4)
tables4

[([0, 1, 2, 3], (1, 0, 3, 2), (2, 3, 0, 1), (3, 2, 1, 0)),
 ([0, 1, 2, 3], (1, 0, 3, 2), (2, 3, 1, 0), (3, 2, 0, 1)),
 ([0, 1, 2, 3], (1, 2, 3, 0), (2, 3, 0, 1), (3, 0, 1, 2)),
 ([0, 1, 2, 3], (1, 3, 0, 2), (2, 0, 3, 1), (3, 2, 1, 0))]

In [23]:
for t in tables4:
    pp.pprint(np.array(t))

array([[0, 1, 2, 3],
       [1, 0, 3, 2],
       [2, 3, 0, 1],
       [3, 2, 1, 0]])
array([[0, 1, 2, 3],
       [1, 0, 3, 2],
       [2, 3, 1, 0],
       [3, 2, 0, 1]])
array([[0, 1, 2, 3],
       [1, 2, 3, 0],
       [2, 3, 0, 1],
       [3, 0, 1, 2]])
array([[0, 1, 2, 3],
       [1, 3, 0, 2],
       [2, 0, 3, 1],
       [3, 2, 1, 0]])


In [24]:
groups4 = alg.tables_to_groups(tables4)
for g in groups4:
    g.pprint()

Group('G0',
'Group 0 of order 4',
['e0', 'a0_1', 'a0_2', 'a0_3'],
[[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 0, 1], [3, 2, 1, 0]]
)
Group('G1',
'Group 1 of order 4',
['e1', 'a1_1', 'a1_2', 'a1_3'],
[[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 1, 0], [3, 2, 0, 1]]
)
Group('G2',
'Group 2 of order 4',
['e2', 'a2_1', 'a2_2', 'a2_3'],
[[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]]
)
Group('G3',
'Group 3 of order 4',
['e3', 'a3_1', 'a3_2', 'a3_3'],
[[0, 1, 2, 3], [1, 3, 0, 2], [2, 0, 3, 1], [3, 2, 1, 0]]
)


In [25]:
g0 = groups4[0]
g1 = groups4[1]
g2 = groups4[2]
g3 = groups4[3]

Below, it can be seen that...

* <b>g0</b> is isomorphic to, v4, the Klein-4 group (and to the direct product, z2 * z2)
* <b>g1, g2, & g3</b> are isomorphic to each other and to, z4, the cyclic group of order 4

### G0

In [26]:
g0  # Isomorphic to v4 and z2_x_z2

Group('G0',
'Group 0 of order 4',
['e0', 'a0_1', 'a0_2', 'a0_3'],
[[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 0, 1], [3, 2, 1, 0]]) 

In [27]:
v4.pprint()

Group('V4',
'Klein-4 group',
['e', 'h', 'v', 'hv'],
[[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 0, 1], [3, 2, 1, 0]]
)


In [28]:
g0.isomorphic(v4)

{'a0_1': 'h', 'a0_2': 'v', 'a0_3': 'hv', 'e0': 'e'}

In [29]:
g0.isomorphic(z2_x_z2)

{'a0_1': 'e:a', 'a0_2': 'a:e', 'a0_3': 'a:a', 'e0': 'e:e'}

In [30]:
v4.isomorphic(z2_x_z2)

{'h': 'e:a', 'v': 'a:e', 'hv': 'a:a', 'e': 'e:e'}

### G1

In [31]:
g1

Group('G1',
'Group 1 of order 4',
['e1', 'a1_1', 'a1_2', 'a1_3'],
[[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 1, 0], [3, 2, 0, 1]]) 

In [32]:
g1.isomorphic(g0)

False

### G2

In [33]:
g2  # Same as z4, below

Group('G2',
'Group 2 of order 4',
['e2', 'a2_1', 'a2_2', 'a2_3'],
[[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]]) 

In [34]:
g2.isomorphic(z4)

{'a2_1': 'a', 'a2_2': 'a^2', 'a2_3': 'a^3', 'e2': 'e'}

In [35]:
g2.isomorphic(g0)

False

In [36]:
g2.isomorphic(g1)

{'a2_1': 'a1_2', 'a2_2': 'a1_1', 'a2_3': 'a1_3', 'e2': 'e1'}

### G3

In [37]:
g3

Group('G3',
'Group 3 of order 4',
['e3', 'a3_1', 'a3_2', 'a3_3'],
[[0, 1, 2, 3], [1, 3, 0, 2], [2, 0, 3, 1], [3, 2, 1, 0]]) 

In [38]:
g3.isomorphic(g0)

False

In [39]:
g3.isomorphic(g1)

{'a3_1': 'a1_2', 'a3_2': 'a1_3', 'a3_3': 'a1_1', 'e3': 'e1'}

In [40]:
g3.isomorphic(g2)

{'a3_1': 'a2_1', 'a3_2': 'a2_3', 'a3_3': 'a2_2', 'e3': 'e2'}

### A Group of Prime Order

In [41]:
order = 5

In [42]:
z5 = alg.generate_cyclic_group(order)

In [43]:
z5.pprint()

Group('Z5',
'Autogenerated cyclic group of order 5',
['e', 'a', 'a^2', 'a^3', 'a^4'],
[[0, 1, 2, 3, 4],
 [1, 2, 3, 4, 0],
 [2, 3, 4, 0, 1],
 [3, 4, 0, 1, 2],
 [4, 0, 1, 2, 3]]
)


In [44]:
%time tables5 = alg.generate_all_group_tables(order)
len(tables5)

CPU times: user 230 ms, sys: 2.64 ms, total: 233 ms
Wall time: 231 ms


6

In [45]:
list(it.product('abcde', 'abcde'))

[('a', 'a'),
 ('a', 'b'),
 ('a', 'c'),
 ('a', 'd'),
 ('a', 'e'),
 ('b', 'a'),
 ('b', 'b'),
 ('b', 'c'),
 ('b', 'd'),
 ('b', 'e'),
 ('c', 'a'),
 ('c', 'b'),
 ('c', 'c'),
 ('c', 'd'),
 ('c', 'e'),
 ('d', 'a'),
 ('d', 'b'),
 ('d', 'c'),
 ('d', 'd'),
 ('d', 'e'),
 ('e', 'a'),
 ('e', 'b'),
 ('e', 'c'),
 ('e', 'd'),
 ('e', 'e')]

In [46]:
groups5 = alg.tables_to_groups(tables5)
for grp in groups5:
    grp.pprint()

Group('G0',
'Group 0 of order 5',
['e0', 'a0_1', 'a0_2', 'a0_3', 'a0_4'],
[[0, 1, 2, 3, 4],
 [1, 2, 3, 4, 0],
 [2, 3, 4, 0, 1],
 [3, 4, 0, 1, 2],
 [4, 0, 1, 2, 3]]
)
Group('G1',
'Group 1 of order 5',
['e1', 'a1_1', 'a1_2', 'a1_3', 'a1_4'],
[[0, 1, 2, 3, 4],
 [1, 2, 4, 0, 3],
 [2, 4, 3, 1, 0],
 [3, 0, 1, 4, 2],
 [4, 3, 0, 2, 1]]
)
Group('G2',
'Group 2 of order 5',
['e2', 'a2_1', 'a2_2', 'a2_3', 'a2_4'],
[[0, 1, 2, 3, 4],
 [1, 3, 0, 4, 2],
 [2, 0, 4, 1, 3],
 [3, 4, 1, 2, 0],
 [4, 2, 3, 0, 1]]
)
Group('G3',
'Group 3 of order 5',
['e3', 'a3_1', 'a3_2', 'a3_3', 'a3_4'],
[[0, 1, 2, 3, 4],
 [1, 3, 4, 2, 0],
 [2, 4, 1, 0, 3],
 [3, 2, 0, 4, 1],
 [4, 0, 3, 1, 2]]
)
Group('G4',
'Group 4 of order 5',
['e4', 'a4_1', 'a4_2', 'a4_3', 'a4_4'],
[[0, 1, 2, 3, 4],
 [1, 4, 0, 2, 3],
 [2, 0, 3, 4, 1],
 [3, 2, 4, 1, 0],
 [4, 3, 1, 0, 2]]
)
Group('G5',
'Group 5 of order 5',
['e5', 'a5_1', 'a5_2', 'a5_3', 'a5_4'],
[[0, 1, 2, 3, 4],
 [1, 4, 3, 0, 2],
 [2, 3, 1, 4, 0],
 [3, 0, 4, 2, 1],
 [4, 2, 0, 1, 3]]
)


In [47]:
# No two tables in groups5 are the same:

np_tables5 = [g.mult_table for g in groups5]

for combo in it.combinations(groups5, 2):
    if combo[0] == combo[1]:
        print(combo[0])

In [48]:
# And yet, six of the groups are abelian:

abelian_tables5 = [g for g in groups5 if g.abelian()]
abelian_tables5

[Group('G0',
 'Group 0 of order 5',
 ['e0', 'a0_1', 'a0_2', 'a0_3', 'a0_4'],
 [[0, 1, 2, 3, 4], [1, 2, 3, 4, 0], [2, 3, 4, 0, 1], [3, 4, 0, 1, 2], [4, 0, 1, 2, 3]]) ,
 Group('G1',
 'Group 1 of order 5',
 ['e1', 'a1_1', 'a1_2', 'a1_3', 'a1_4'],
 [[0, 1, 2, 3, 4], [1, 2, 4, 0, 3], [2, 4, 3, 1, 0], [3, 0, 1, 4, 2], [4, 3, 0, 2, 1]]) ,
 Group('G2',
 'Group 2 of order 5',
 ['e2', 'a2_1', 'a2_2', 'a2_3', 'a2_4'],
 [[0, 1, 2, 3, 4], [1, 3, 0, 4, 2], [2, 0, 4, 1, 3], [3, 4, 1, 2, 0], [4, 2, 3, 0, 1]]) ,
 Group('G3',
 'Group 3 of order 5',
 ['e3', 'a3_1', 'a3_2', 'a3_3', 'a3_4'],
 [[0, 1, 2, 3, 4], [1, 3, 4, 2, 0], [2, 4, 1, 0, 3], [3, 2, 0, 4, 1], [4, 0, 3, 1, 2]]) ,
 Group('G4',
 'Group 4 of order 5',
 ['e4', 'a4_1', 'a4_2', 'a4_3', 'a4_4'],
 [[0, 1, 2, 3, 4], [1, 4, 0, 2, 3], [2, 0, 3, 4, 1], [3, 2, 4, 1, 0], [4, 3, 1, 0, 2]]) ,
 Group('G5',
 'Group 5 of order 5',
 ['e5', 'a5_1', 'a5_2', 'a5_3', 'a5_4'],
 [[0, 1, 2, 3, 4], [1, 4, 3, 0, 2], [2, 3, 1, 4, 0], [3, 0, 4, 2, 1], [4, 2, 0, 1, 3]]) 

In [49]:
tbl0 = tables5[0]
print(tbl0)

([0, 1, 2, 3, 4], (1, 2, 3, 4, 0), (2, 3, 4, 0, 1), (3, 4, 0, 1, 2), (4, 0, 1, 2, 3))


In [50]:
alg.associative_table(tbl0)

True

In [51]:
alg.generate_all_group_tables(4)

[([0, 1, 2, 3], (1, 0, 3, 2), (2, 3, 0, 1), (3, 2, 1, 0)),
 ([0, 1, 2, 3], (1, 0, 3, 2), (2, 3, 1, 0), (3, 2, 0, 1)),
 ([0, 1, 2, 3], (1, 2, 3, 0), (2, 3, 0, 1), (3, 0, 1, 2)),
 ([0, 1, 2, 3], (1, 3, 0, 2), (2, 0, 3, 1), (3, 2, 1, 0))]

### All Tables of Order 6 (WARNING: Long Compute Time)

<b>IMPORTANT NOTE:</b>The computation of all group tables of order 6 currently takes between 4.5 & 6 hours, so the resuls have been saved in a file, tables5.py.  The file, groups5.py, was also saved.

In [52]:
%run -i '../misc/tables6.py'

In [53]:
tables6
len(tables6)

80

In [54]:
groups6 = alg.tables_to_groups(tables6)
groups6

[Group('G0',
 'Group 0 of order 6',
 ['e0', 'a0_1', 'a0_2', 'a0_3', 'a0_4', 'a0_5'],
 [[0, 1, 2, 3, 4, 5], [1, 0, 3, 2, 5, 4], [2, 3, 4, 5, 0, 1], [3, 2, 5, 4, 1, 0], [4, 5, 0, 1, 2, 3], [5, 4, 1, 0, 3, 2]]) ,
 Group('G1',
 'Group 1 of order 6',
 ['e1', 'a1_1', 'a1_2', 'a1_3', 'a1_4', 'a1_5'],
 [[0, 1, 2, 3, 4, 5], [1, 0, 3, 2, 5, 4], [2, 3, 4, 5, 1, 0], [3, 2, 5, 4, 0, 1], [4, 5, 1, 0, 3, 2], [5, 4, 0, 1, 2, 3]]) ,
 Group('G2',
 'Group 2 of order 6',
 ['e2', 'a2_1', 'a2_2', 'a2_3', 'a2_4', 'a2_5'],
 [[0, 1, 2, 3, 4, 5], [1, 0, 3, 2, 5, 4], [2, 3, 5, 4, 0, 1], [3, 2, 4, 5, 1, 0], [4, 5, 0, 1, 3, 2], [5, 4, 1, 0, 2, 3]]) ,
 Group('G3',
 'Group 3 of order 6',
 ['e3', 'a3_1', 'a3_2', 'a3_3', 'a3_4', 'a3_5'],
 [[0, 1, 2, 3, 4, 5], [1, 0, 3, 2, 5, 4], [2, 3, 5, 4, 1, 0], [3, 2, 4, 5, 0, 1], [4, 5, 1, 0, 2, 3], [5, 4, 0, 1, 3, 2]]) ,
 Group('G4',
 'Group 4 of order 6',
 ['e4', 'a4_1', 'a4_2', 'a4_3', 'a4_4', 'a4_5'],
 [[0, 1, 2, 3, 4, 5], [1, 0, 3, 2, 5, 4], [2, 4, 0, 5, 1, 3], [3, 5, 1, 4, 

In [55]:
not_abelian6 = [g.name for g in groups6 if not g.abelian()]
print(not_abelian6)

['G4', 'G5', 'G6', 'G7', 'G8', 'G9', 'G14', 'G15', 'G16', 'G17', 'G18', 'G19', 'G27', 'G28', 'G43', 'G46', 'G58', 'G61', 'G73', 'G76']


In [56]:
iso_to_g4 = [g for g in groups6 if groups6[4].isomorphic(g)]
len(iso_to_g4)

20

In [57]:
iso_to_g0 = [g for g in groups6 if groups6[0].isomorphic(g)]
len(iso_to_g0)

60

In [58]:
g6_0 = groups6[0]  # abelian
g6_4 = groups6[4]  # not abelian

In [59]:
g6_0.pprint()

Group('G0',
'Group 0 of order 6',
['e0', 'a0_1', 'a0_2', 'a0_3', 'a0_4', 'a0_5'],
[[0, 1, 2, 3, 4, 5],
 [1, 0, 3, 2, 5, 4],
 [2, 3, 4, 5, 0, 1],
 [3, 2, 5, 4, 1, 0],
 [4, 5, 0, 1, 2, 3],
 [5, 4, 1, 0, 3, 2]]
)


In [60]:
g6_4.pprint()

Group('G4',
'Group 4 of order 6',
['e4', 'a4_1', 'a4_2', 'a4_3', 'a4_4', 'a4_5'],
[[0, 1, 2, 3, 4, 5],
 [1, 0, 3, 2, 5, 4],
 [2, 4, 0, 5, 1, 3],
 [3, 5, 1, 4, 0, 2],
 [4, 2, 5, 0, 3, 1],
 [5, 3, 4, 1, 2, 0]]
)


In [61]:
g6_0.proper_subgroups()

[Group('G0_subgroup_0',
 'Subgroup of: Group 0 of order 6',
 ['e0', 'a0_2', 'a0_4'],
 [[0, 1, 2], [1, 2, 0], [2, 0, 1]]) ,
 Group('G0_subgroup_1',
 'Subgroup of: Group 0 of order 6',
 ['e0', 'a0_1'],
 [[0, 1], [1, 0]]) ]

In [62]:
g6_4.proper_subgroups()

[Group('G4_subgroup_0',
 'Subgroup of: Group 4 of order 6',
 ['e4', 'a4_3', 'a4_4'],
 [[0, 1, 2], [1, 2, 0], [2, 0, 1]]) ,
 Group('G4_subgroup_1',
 'Subgroup of: Group 4 of order 6',
 ['e4', 'a4_1'],
 [[0, 1], [1, 0]]) ,
 Group('G4_subgroup_2',
 'Subgroup of: Group 4 of order 6',
 ['e4', 'a4_2'],
 [[0, 1], [1, 0]]) ,
 Group('G4_subgroup_3',
 'Subgroup of: Group 4 of order 6',
 ['e4', 'a4_5'],
 [[0, 1], [1, 0]]) ]

## Turn isomorphisms into permutations

In [63]:
groups4

[Group('G0',
 'Group 0 of order 4',
 ['e0', 'a0_1', 'a0_2', 'a0_3'],
 [[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 0, 1], [3, 2, 1, 0]]) ,
 Group('G1',
 'Group 1 of order 4',
 ['e1', 'a1_1', 'a1_2', 'a1_3'],
 [[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 1, 0], [3, 2, 0, 1]]) ,
 Group('G2',
 'Group 2 of order 4',
 ['e2', 'a2_1', 'a2_2', 'a2_3'],
 [[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]]) ,
 Group('G3',
 'Group 3 of order 4',
 ['e3', 'a3_1', 'a3_2', 'a3_3'],
 [[0, 1, 2, 3], [1, 3, 0, 2], [2, 0, 3, 1], [3, 2, 1, 0]]) ]

In [64]:
for combo in it.combinations(groups4,2):
    mp = combo[0].isomorphic(combo[1])
    print(combo[0].name, combo[1].name, mp)

G0 G1 False
G0 G2 False
G0 G3 False
G1 G2 {'a1_1': 'a2_2', 'a1_2': 'a2_1', 'a1_3': 'a2_3', 'e1': 'e2'}
G1 G3 {'a1_1': 'a3_3', 'a1_2': 'a3_1', 'a1_3': 'a3_2', 'e1': 'e3'}
G2 G3 {'a2_1': 'a3_1', 'a2_2': 'a3_3', 'a2_3': 'a3_2', 'e2': 'e3'}


In [65]:
z4_iso_groups4 = [z4.isomorphic(grp) for grp in groups4[1:]]
z4_iso_groups4

[{'a': 'a1_2', 'a^2': 'a1_1', 'a^3': 'a1_3', 'e': 'e1'},
 {'a': 'a2_1', 'a^2': 'a2_2', 'a^3': 'a2_3', 'e': 'e2'},
 {'a': 'a3_1', 'a^2': 'a3_3', 'a^3': 'a3_2', 'e': 'e3'}]

In [66]:
# Get values from the iso mapping in the same order as the elements in z4

test_iso = z4_iso_groups4[0]
#[test_iso[elem] for elem in z4.element_names]
[test_iso[elem] for elem in z4]

['e1', 'a1_2', 'a1_1', 'a1_3']

In [67]:
alg.get_int_forms(z4, z4_iso_groups4)

[213, 123, 132]

In [68]:
g1_iso_groups4 = [g1.isomorphic(grp) for grp in groups4[1:]]
g1_iso_groups4

int_forms_4 = alg.get_int_forms(g1, g1_iso_groups4)
int_forms_4

[123, 213, 312]

In [69]:
def int_form_to_tuple(int_form):
    """Example:
    >>> int_form_to_tuple(123)
    '(1, 2, 3)'
    """
    return str(tuple([int(x) for x in list(str(int_form))]))

In [70]:
int_form_to_tuple(123)

'(1, 2, 3)'

In [71]:
int_forms_4_ext = [int_form_to_tuple(x) for x in int_forms_4]
int_forms_4_ext

['(1, 2, 3)', '(2, 1, 3)', '(3, 1, 2)']

In [72]:
s3 = alg.generate_symmetric_group(3, base=1)
print(s3.element_names)

['(1, 2, 3)', '(1, 3, 2)', '(2, 1, 3)', '(2, 3, 1)', '(3, 1, 2)', '(3, 2, 1)']


In [73]:
s3.closure(int_forms_4_ext)

['(1, 2, 3)', '(2, 1, 3)', '(3, 2, 1)', '(1, 3, 2)', '(3, 1, 2)', '(2, 3, 1)']

In [74]:
z5

Group('Z5',
'Autogenerated cyclic group of order 5',
['e', 'a', 'a^2', 'a^3', 'a^4'],
[[0, 1, 2, 3, 4], [1, 2, 3, 4, 0], [2, 3, 4, 0, 1], [3, 4, 0, 1, 2], [4, 0, 1, 2, 3]]) 

In [75]:
groups5

[Group('G0',
 'Group 0 of order 5',
 ['e0', 'a0_1', 'a0_2', 'a0_3', 'a0_4'],
 [[0, 1, 2, 3, 4], [1, 2, 3, 4, 0], [2, 3, 4, 0, 1], [3, 4, 0, 1, 2], [4, 0, 1, 2, 3]]) ,
 Group('G1',
 'Group 1 of order 5',
 ['e1', 'a1_1', 'a1_2', 'a1_3', 'a1_4'],
 [[0, 1, 2, 3, 4], [1, 2, 4, 0, 3], [2, 4, 3, 1, 0], [3, 0, 1, 4, 2], [4, 3, 0, 2, 1]]) ,
 Group('G2',
 'Group 2 of order 5',
 ['e2', 'a2_1', 'a2_2', 'a2_3', 'a2_4'],
 [[0, 1, 2, 3, 4], [1, 3, 0, 4, 2], [2, 0, 4, 1, 3], [3, 4, 1, 2, 0], [4, 2, 3, 0, 1]]) ,
 Group('G3',
 'Group 3 of order 5',
 ['e3', 'a3_1', 'a3_2', 'a3_3', 'a3_4'],
 [[0, 1, 2, 3, 4], [1, 3, 4, 2, 0], [2, 4, 1, 0, 3], [3, 2, 0, 4, 1], [4, 0, 3, 1, 2]]) ,
 Group('G4',
 'Group 4 of order 5',
 ['e4', 'a4_1', 'a4_2', 'a4_3', 'a4_4'],
 [[0, 1, 2, 3, 4], [1, 4, 0, 2, 3], [2, 0, 3, 4, 1], [3, 2, 4, 1, 0], [4, 3, 1, 0, 2]]) ,
 Group('G5',
 'Group 5 of order 5',
 ['e5', 'a5_1', 'a5_2', 'a5_3', 'a5_4'],
 [[0, 1, 2, 3, 4], [1, 4, 3, 0, 2], [2, 3, 1, 4, 0], [3, 0, 4, 2, 1], [4, 2, 0, 1, 3]]) 

In [76]:
z5_iso_groups5 = [z5.isomorphic(grp) for grp in groups5]
z5_iso_groups5

[{'a': 'a0_1', 'a^2': 'a0_2', 'a^3': 'a0_3', 'a^4': 'a0_4', 'e': 'e0'},
 {'a': 'a1_1', 'a^2': 'a1_2', 'a^3': 'a1_4', 'a^4': 'a1_3', 'e': 'e1'},
 {'a': 'a2_1', 'a^2': 'a2_3', 'a^3': 'a2_4', 'a^4': 'a2_2', 'e': 'e2'},
 {'a': 'a3_1', 'a^2': 'a3_3', 'a^3': 'a3_2', 'a^4': 'a3_4', 'e': 'e3'},
 {'a': 'a4_1', 'a^2': 'a4_4', 'a^3': 'a4_3', 'a^4': 'a4_2', 'e': 'e4'},
 {'a': 'a5_1', 'a^2': 'a5_4', 'a^3': 'a5_2', 'a^4': 'a5_3', 'e': 'e5'}]

In [77]:
int_forms_5 = alg.get_int_forms(z5, z5_iso_groups5)
int_forms_5

[1234, 1243, 1342, 1324, 1432, 1423]

In [78]:
int_forms_5_ext = [int_form_to_tuple(x) for x in int_forms_5]
int_forms_5_ext

['(1, 2, 3, 4)',
 '(1, 2, 4, 3)',
 '(1, 3, 4, 2)',
 '(1, 3, 2, 4)',
 '(1, 4, 3, 2)',
 '(1, 4, 2, 3)']

In [79]:
s4 = alg.generate_symmetric_group(4, base=1)
print(s4.element_names)

['(1, 2, 3, 4)', '(1, 2, 4, 3)', '(1, 3, 2, 4)', '(1, 3, 4, 2)', '(1, 4, 2, 3)', '(1, 4, 3, 2)', '(2, 1, 3, 4)', '(2, 1, 4, 3)', '(2, 3, 1, 4)', '(2, 3, 4, 1)', '(2, 4, 1, 3)', '(2, 4, 3, 1)', '(3, 1, 2, 4)', '(3, 1, 4, 2)', '(3, 2, 1, 4)', '(3, 2, 4, 1)', '(3, 4, 1, 2)', '(3, 4, 2, 1)', '(4, 1, 2, 3)', '(4, 1, 3, 2)', '(4, 2, 1, 3)', '(4, 2, 3, 1)', '(4, 3, 1, 2)', '(4, 3, 2, 1)']


In [80]:
s4.closure(int_forms_5_ext)

['(1, 2, 3, 4)',
 '(1, 3, 4, 2)',
 '(1, 2, 4, 3)',
 '(1, 4, 2, 3)',
 '(1, 4, 3, 2)',
 '(1, 3, 2, 4)']

## Automorphisms and Conjugates

NOTE: Conjugation only changes elements when the group is non-abelian.

In [81]:
g6_4.pprint(True)  # Not abelian

Group('G4',
'Group 4 of order 6',
[['e4', 'a4_1', 'a4_2', 'a4_3', 'a4_4', 'a4_5'],
 ['a4_1', 'e4', 'a4_3', 'a4_2', 'a4_5', 'a4_4'],
 ['a4_2', 'a4_4', 'e4', 'a4_5', 'a4_1', 'a4_3'],
 ['a4_3', 'a4_5', 'a4_1', 'a4_4', 'e4', 'a4_2'],
 ['a4_4', 'a4_2', 'a4_5', 'e4', 'a4_3', 'a4_1'],
 ['a4_5', 'a4_3', 'a4_4', 'a4_1', 'a4_2', 'e4']]
)


In [82]:
grp = g6_4
ele = grp.element_names[1]
ele_inv = grp.inverse(ele)

print(f"Group: {grp.name}, Element: {ele}, Inverse: {ele_inv}")
print(f"Abelian: {grp.abelian()}")

conjugates = [grp.mult(grp.mult(ele, x), ele_inv) for x in grp]

conjugates

Group: G4, Element: a4_1, Inverse: a4_1
Abelian: False


['e4', 'a4_1', 'a4_5', 'a4_4', 'a4_3', 'a4_2']

In [83]:
g6_0.pprint(True)  # Abelian

Group('G0',
'Group 0 of order 6',
[['e0', 'a0_1', 'a0_2', 'a0_3', 'a0_4', 'a0_5'],
 ['a0_1', 'e0', 'a0_3', 'a0_2', 'a0_5', 'a0_4'],
 ['a0_2', 'a0_3', 'a0_4', 'a0_5', 'e0', 'a0_1'],
 ['a0_3', 'a0_2', 'a0_5', 'a0_4', 'a0_1', 'e0'],
 ['a0_4', 'a0_5', 'e0', 'a0_1', 'a0_2', 'a0_3'],
 ['a0_5', 'a0_4', 'a0_1', 'e0', 'a0_3', 'a0_2']]
)


In [84]:
grp = g6_0
ele = grp.element_names[1]
ele_inv = grp.inverse(ele)

print(f"Group: {grp.name}, Element: {ele}, Inverse: {ele_inv}")
print(f"Abelian: {grp.abelian()}")

conjugates = [grp.mult(grp.mult(ele, x), ele_inv) for x in grp]
conjugates

Group: G0, Element: a0_1, Inverse: a0_1
Abelian: True


['e0', 'a0_1', 'a0_2', 'a0_3', 'a0_4', 'a0_5']

## Finite Rings

"Consider any finite set. Then its power set with respect to symmetric difference (as 1st operation) and set intersection (as 2nd operation) is an example of a finite ring." -- [Quora](https://www.quora.com/What-are-examples-of-finite-rings#:~:text=Matrices%20over%20any%20ring%20make,a%20finite%20ring%20with%20elements.)

### Powerset Functions

In [85]:
n = 20
ints_n = set(list(range(n)))
ints_n

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19}

[Source of powerset code](https://docs.python.org/3/library/itertools.html#itertools-recipes)

In [86]:
# from itertools import chain, combinations

def powerset(iterable):
    "powerset([1,2,3]) --> () (1,) (2,) (3,) (1,2) (1,3) (2,3) (1,2,3)"
    s = list(iterable)
    return it.chain.from_iterable(it.combinations(s, r) for r in range(len(s)+1))

In [87]:
%time foo1 = [set(x) for x in list(powerset(ints_n))]
len(foo1)

CPU times: user 2.28 s, sys: 217 ms, total: 2.49 s
Wall time: 2.49 s


1048576

### Set Operations

In [88]:
A = {0, 2, 4, 6, 8}
B = {1, 2, 3, 4, 5}

print(f"               Union: {A | B}")
print(f"        Intersection: {A & B}")
print(f"          Difference: {A - B}")
print(f"Symmetric Difference: {A ^ B}")

               Union: {0, 1, 2, 3, 4, 5, 6, 8}
        Intersection: {2, 4}
          Difference: {0, 8, 6}
Symmetric Difference: {0, 1, 3, 5, 6, 8}


In [89]:
n = 3
set_of_n = set(list(range(n)))
print(set_of_n)

%time powerset_n = [set(x) for x in list(powerset(set_of_n))]
len(powerset_n)

{0, 1, 2}
CPU times: user 14 µs, sys: 1e+03 ns, total: 15 µs
Wall time: 16 µs


8

In [90]:
powerset_n

[set(), {0}, {1}, {2}, {0, 1}, {0, 2}, {1, 2}, {0, 1, 2}]

In [91]:
tuples_n = [tuple(x) for x in powerset_n]
tuples_n

[(), (0,), (1,), (2,), (0, 1), (0, 2), (1, 2), (0, 1, 2)]

In [92]:
powerset_n.index({0,1})

4

In [93]:
table = [[powerset_n.index(a ^ b) for b in powerset_n] for a in powerset_n]

In [94]:
table

[[0, 1, 2, 3, 4, 5, 6, 7],
 [1, 0, 4, 5, 2, 3, 7, 6],
 [2, 4, 0, 6, 1, 7, 3, 5],
 [3, 5, 6, 0, 7, 1, 2, 4],
 [4, 2, 1, 7, 0, 6, 5, 3],
 [5, 3, 7, 1, 6, 0, 4, 2],
 [6, 7, 3, 2, 5, 4, 0, 1],
 [7, 6, 5, 4, 3, 2, 1, 0]]

In [95]:
foo = alg.Group("PS3", "Group from powerset of 3 elements", tuples_n, table)

In [96]:
foo.pprint()

Group('PS3',
'Group from powerset of 3 elements',
[(), (0,), (1,), (2,), (0, 1), (0, 2), (1, 2), (0, 1, 2)],
[[0, 1, 2, 3, 4, 5, 6, 7],
 [1, 0, 4, 5, 2, 3, 7, 6],
 [2, 4, 0, 6, 1, 7, 3, 5],
 [3, 5, 6, 0, 7, 1, 2, 4],
 [4, 2, 1, 7, 0, 6, 5, 3],
 [5, 3, 7, 1, 6, 0, 4, 2],
 [6, 7, 3, 2, 5, 4, 0, 1],
 [7, 6, 5, 4, 3, 2, 1, 0]]
)


In [97]:
len(foo.proper_subgroups())

14

In [98]:
foo.identity

()

In [99]:
ps3 = alg.generate_powerset_group(3)
ps3.pprint()

Group('PS3',
'Autogenerated group on the powerset of 3 elements, with symmetric difference operator',
[(), (0,), (1,), (2,), (0, 1), (0, 2), (1, 2), (0, 1, 2)],
[[0, 1, 2, 3, 4, 5, 6, 7],
 [1, 0, 4, 5, 2, 3, 7, 6],
 [2, 4, 0, 6, 1, 7, 3, 5],
 [3, 5, 6, 0, 7, 1, 2, 4],
 [4, 2, 1, 7, 0, 6, 5, 3],
 [5, 3, 7, 1, 6, 0, 4, 2],
 [6, 7, 3, 2, 5, 4, 0, 1],
 [7, 6, 5, 4, 3, 2, 1, 0]]
)


In [100]:
ps4 = alg.generate_powerset_group(4)
ps4.pprint()

Group('PS4',
'Autogenerated group on the powerset of 4 elements, with symmetric difference operator',
[(), (0,), (1,), (2,), (3,), (0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3), (0, 1, 2), (0, 1, 3), (0, 2, 3), (1, 2, 3), (0, 1, 2, 3)],
[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
 [1, 0, 5, 6, 7, 2, 3, 4, 11, 12, 13, 8, 9, 10, 15, 14],
 [2, 5, 0, 8, 9, 1, 11, 12, 3, 4, 14, 6, 7, 15, 10, 13],
 [3, 6, 8, 0, 10, 11, 1, 13, 2, 14, 4, 5, 15, 7, 9, 12],
 [4, 7, 9, 10, 0, 12, 13, 1, 14, 2, 3, 15, 5, 6, 8, 11],
 [5, 2, 1, 11, 12, 0, 8, 9, 6, 7, 15, 3, 4, 14, 13, 10],
 [6, 3, 11, 1, 13, 8, 0, 10, 5, 15, 7, 2, 14, 4, 12, 9],
 [7, 4, 12, 13, 1, 9, 10, 0, 15, 5, 6, 14, 2, 3, 11, 8],
 [8, 11, 3, 2, 14, 6, 5, 15, 0, 10, 9, 1, 13, 12, 4, 7],
 [9, 12, 4, 14, 2, 7, 15, 5, 10, 0, 8, 13, 1, 11, 3, 6],
 [10, 13, 14, 4, 3, 15, 7, 6, 9, 8, 0, 12, 11, 1, 2, 5],
 [11, 8, 6, 5, 15, 3, 2, 14, 1, 13, 12, 0, 10, 9, 7, 4],
 [12, 9, 7, 15, 5, 4, 14, 2, 13, 1, 11, 10, 0, 8, 6, 3],
 [13, 10, 15, 7, 6, 1

TODO: Look for the paper by Carolyn Bean, "Group operations on the power set", Journal of Undergraduate Mathematics 8 #1 (March 1976), 13-17.

### Ring Definition

In [135]:
class Ring(alg.Group):
    
    def __init__(self, *args):
        
        if len(args) == 5:
            
            super().__init__(args[:4])
        
        self.rmult_table = args[4]
        
    def rmult_table_with_names(self):
        return [[self.element_names[elem_pos]
                 for elem_pos in row]
                for row in self.rmult_table]
        
    def pprint(self, use_element_names=False):
        print(f"{self.__class__.__name__}('{self.name}',")
        print(f"'{self.description}',")
        if use_element_names:
            pp.pprint(self.mult_table_with_names())
            pp.pprint(self.rmult_table_with_names())
        else:
            print(f"{self.element_names},")
            pp.pprint(self.mult_table.tolist())
            pp.pprint(self.rmult_table.tolist())
        print(")")
        return None


In [136]:
test = alg.Ring('RPS3',
                'Test Ring',
                ps3.element_names,
                ps3.mult_table,
                ps3.mult_table
               )

In [137]:
test.mult_table

array([[0, 1, 2, 3, 4, 5, 6, 7],
       [1, 0, 4, 5, 2, 3, 7, 6],
       [2, 4, 0, 6, 1, 7, 3, 5],
       [3, 5, 6, 0, 7, 1, 2, 4],
       [4, 2, 1, 7, 0, 6, 5, 3],
       [5, 3, 7, 1, 6, 0, 4, 2],
       [6, 7, 3, 2, 5, 4, 0, 1],
       [7, 6, 5, 4, 3, 2, 1, 0]])

In [138]:
test.rmult_table

AttributeError: 'Ring' object has no attribute 'rmult_table'

In [139]:
test.pprint(True)

Ring('RPS3',
'Test Ring',
[[(), (0,), (1,), (2,), (0, 1), (0, 2), (1, 2), (0, 1, 2)],
 [(0,), (), (0, 1), (0, 2), (1,), (2,), (0, 1, 2), (1, 2)],
 [(1,), (0, 1), (), (1, 2), (0,), (0, 1, 2), (2,), (0, 2)],
 [(2,), (0, 2), (1, 2), (), (0, 1, 2), (0,), (1,), (0, 1)],
 [(0, 1), (1,), (0,), (0, 1, 2), (), (1, 2), (0, 2), (2,)],
 [(0, 2), (2,), (0, 1, 2), (0,), (1, 2), (), (0, 1), (1,)],
 [(1, 2), (0, 1, 2), (2,), (1,), (0, 2), (0, 1), (), (0,)],
 [(0, 1, 2), (1, 2), (0, 2), (0, 1), (2,), (1,), (0,), ()]]
)


In [106]:
foo = [1, 2, 3, 4, 5]

In [107]:
foo[:4]

[1, 2, 3, 4]