# Regular Representation

<i>Version 2</i>

Let $G = \langle A, \circ \rangle$, be a group, where $A = \{a_0, a_1, \dots , a_{n - 1}\}$ is the set of the group's elements, and $\circ$ is its binary operator.

Also, let $B = \{\hat{b}_0, \hat{b}_1, \dots , \hat{b}_{n-1} \}$ be a set of $nx1$ vectors:

$\hat{b}_0 = \begin{bmatrix}
1 \\
0 \\
0 \\
\vdots \\
0 \end{bmatrix},
\hat{b}_1 = \begin{bmatrix}
0 \\
1 \\
0 \\
\vdots \\
0 \end{bmatrix},
\dots,
\hat{b}_{n-1} = \begin{bmatrix}
0 \\
0 \\
0 \\
\vdots \\
1 \end{bmatrix}$

And, define the following bijection between $A$ and $B$:

$V(a_i) = \hat{b}_i$ for $i = 0, \dots , n - 1$

Then, let $\cdot$ denote matrix-vector multiplication, and define the matrix, $C_k = (c^k_{ij})_{i,j=1,\dots,n-1}$, where $c^k_{ij} = \hat{b}_i \cdot V(a_k \circ V^{-1}(\hat{b}_j))$.

In [1]:
import numpy as np
import finite_algebras as alg

In [2]:
z4 = alg.make_finite_algebra(
    'Z4',
    'Cyclic group of order 4',
    ['R0', 'R90', 'R180', 'R270'],
    [[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]]
)

z4.about()


** Group **
Name: Z4
Instance ID: 4402881552
Description: Cyclic group of order 4
Order: 4
Identity: R0
Commutative? Yes
Cyclic?: Yes
  Generators: ['R270', 'R90']
Elements:
   Index   Name   Inverse  Order
      0      R0      R0       1
      1     R90    R270       4
      2    R180    R180       2
      3    R270     R90       4
Cayley Table (showing indices):
[[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]]


In [3]:
grp = z4
elems = grp.elements
n = grp.order

In [4]:
vecs = [np.zeros((n,1), dtype=int) for _ in range(n)]

i = 0
for vec in vecs:
    vec[i] = 1
    i += 1
    
vecs

[array([[1],
        [0],
        [0],
        [0]]),
 array([[0],
        [1],
        [0],
        [0]]),
 array([[0],
        [0],
        [1],
        [0]]),
 array([[0],
        [0],
        [0],
        [1]])]

In [5]:
mapping = dict(zip(grp.elements, vecs))
mapping

{'R0': array([[1],
        [0],
        [0],
        [0]]),
 'R90': array([[0],
        [1],
        [0],
        [0]]),
 'R180': array([[0],
        [0],
        [1],
        [0]]),
 'R270': array([[0],
        [0],
        [0],
        [1]])}

In [6]:
def to_tuple(vec):
    '''Turns a column vector into a tuple, for use as a dictionary key.'''
    return tuple(map(lambda x: x[0], list(vec)))

inv_mapping = {to_tuple(val): key for key, val in mapping.items()}
inv_mapping

{(1, 0, 0, 0): 'R0',
 (0, 1, 0, 0): 'R90',
 (0, 0, 1, 0): 'R180',
 (0, 0, 0, 1): 'R270'}

In [7]:
def B(elem):
    '''Given a group element name, return the corresponding vector.'''
    return mapping[elem]

def Binv(vec):
    '''Given a vector, return the corresponding element.'''
    return inv_mapping[to_tuple(vec)]

elem = elems[1]
vec = B(elem)
elem2 = Binv(vec)

print(elem)
print(vec)
print(elem2)

R90
[[0]
 [1]
 [0]
 [0]]
R90


In [11]:
# k(R)bj = B(f(R, Binv(bj)))

j = elems[1]

jvec = mapping[j]

print(j)
print(jvec)
print(B(grp.op(j, Binv(jvec))))

R90
[[0]
 [1]
 [0]
 [0]]
[[0]
 [0]
 [1]
 [0]]


In [13]:
# [B(grp.op(elem, Binv(vec))) for (elem, vec) in zip(elems, vecs)]

In [ ]:
rot_dict = {
    'R0': np.array([[1, 0, 0, 0],
                    [0, 1, 0, 0],
                    [0, 0, 1, 0],
                    [0, 0, 0, 1]]),
    'R90': np.array([[0, 0, 0, 1],
                     [1, 0, 0, 0],
                     [0, 1, 0, 0],
                     [0, 0, 1, 0]]),
    'R180': np.array([[0, 0, 1, 0],
                      [0, 0, 0, 1],
                      [1, 0, 0, 0],
                      [0, 1, 0, 0]]),
    'R270': np.array([[0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1],
                      [1, 0, 0, 0]])
}

def k(R):
    return rot_dict[R]

k('R90')  # Example