# Scratchwork

This notebook is only used for trying out ideas.

In [1]:
import algebras as alg
import json
import os
import numpy as np
import itertools as it
from pprint import pprint

In [2]:
# Path to this repo
aa_path = os.path.join(os.getenv('PYPROJ'), 'abstract_algebra')

# Path to a directory containing Algebra definitions in JSON
alg_dir = os.path.join(aa_path, "Algebras")

## Groups for Testing

### D4 - Dihedral Group on 4 Vertices

In [3]:
d4_path = os.path.join(alg_dir, "d4_dihedral_group_on_4_vertices.json")
!cat {d4_path}

{"type": "Group",
 "name": "D_4",
 "description": "Dihedral group on four vertices",
 "element_names": ["e", "r", "r^2", "r^3", "f", "fr", "r^2f", "rf"],
 "alt_elem_names": ["()", "(0 1 2 3)", "(0 2)(1 3)", "(0 3 2 1)",
                    "(0 1)(2 3)", "(1 3)", "(0 3)(1 2)", "(0 2)"],
 "mult_table": [[0, 1, 2, 3, 4, 5, 6, 7],
                [1, 2, 3, 0, 7, 4, 5, 6],
                [2, 3, 0, 1, 6, 7, 4, 5],
                [3, 0, 1, 2, 5, 6, 7, 4],
                [4, 5, 6, 7, 0, 1, 2, 3],
                [5, 6, 7, 4, 3, 0, 1, 2],
                [6, 7, 4, 5, 2, 3, 0, 1],
                [7, 4, 5, 6, 1, 2, 3, 0]]
}

In [4]:
d4 = alg.Group(d4_path)
d4.print_info()


Group : D_4 : Dihedral group on four vertices
  Element Names: ['e', 'r', 'r^2', 'r^3', 'f', 'fr', 'r^2f', 'rf']
  Is Abelian? False
  Inverses:  (** - indicates that it is its own inverse)
    inv(e) = e   **
    inv(r) = r^3 
    inv(r^2) = r^2   **
    inv(r^3) = r 
    inv(f) = f   **
    inv(fr) = fr   **
    inv(r^2f) = r^2f   **
    inv(rf) = rf   **
Element Orders:
{1: ['e'], 2: ['r^2', 'f', 'fr', 'r^2f', 'rf'], 4: ['r', 'r^3']}
  Is associative? True
  Cayley Table:
[['e', 'r', 'r^2', 'r^3', 'f', 'fr', 'r^2f', 'rf'],
 ['r', 'r^2', 'r^3', 'e', 'rf', 'f', 'fr', 'r^2f'],
 ['r^2', 'r^3', 'e', 'r', 'r^2f', 'rf', 'f', 'fr'],
 ['r^3', 'e', 'r', 'r^2', 'fr', 'r^2f', 'rf', 'f'],
 ['f', 'fr', 'r^2f', 'rf', 'e', 'r', 'r^2', 'r^3'],
 ['fr', 'r^2f', 'rf', 'f', 'r^3', 'e', 'r', 'r^2'],
 ['r^2f', 'rf', 'f', 'fr', 'r^2', 'r^3', 'e', 'r'],
 ['rf', 'f', 'fr', 'r^2f', 'r', 'r^2', 'r^3', 'e']]


### V4 - Klein 4 Group

In [5]:
v4_path = os.path.join(alg_dir, "v4_klein_4_group.json")
!cat {v4_path}

{"type": "Group",
 "name": "V4",
 "description": "Klein-4 group",
 "element_names": ["e", "h", "v", "hv"],
 "mult_table": [[0, 1, 2, 3],
                [1, 0, 3, 2],
                [2, 3, 0, 1],
                [3, 2, 1, 0]]
}


In [6]:
v4 = alg.Group(v4_path)
v4.print_info()


Group : V4 : Klein-4 group
  Element Names: ['e', 'h', 'v', 'hv']
  Is Abelian? True
  Inverses:  (** - indicates that it is its own inverse)
    inv(e) = e   **
    inv(h) = h   **
    inv(v) = v   **
    inv(hv) = hv   **
Element Orders:
{1: ['e'], 2: ['h', 'v', 'hv']}
  Is associative? True
  Cayley Table:
[['e', 'h', 'v', 'hv'],
 ['h', 'e', 'hv', 'v'],
 ['v', 'hv', 'e', 'h'],
 ['hv', 'v', 'h', 'e']]


## Changing the Order of Elements

<b>Observation</b>: If the group is abelian, then changing the order of the elements does <b>not</b> affect the order of the indices in the <i>mult_table</i>.  <b>Why?</b>

In [7]:
# new_elem_order = v4.element_names
# new_v4_elem_order = ['e', 'v', 'h', 'hv']
new_v4_elem_order = ["e", "hv", "h", "v"]

In [8]:
#table_from_reordered_elements(v4, new_v4_elem_order)
v4_reordered = v4.reorder_elements(new_v4_elem_order)
v4_reordered

Group('V4_REORDERED',
'Klein-4 group (elements reordered)',
['e', 'hv', 'h', 'v'],
[[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 0, 1], [3, 2, 1, 0]]) 

In [9]:
pprint(v4_reordered.mult_table_with_names())

[['e', 'hv', 'h', 'v'],
 ['hv', 'e', 'v', 'h'],
 ['h', 'v', 'e', 'hv'],
 ['v', 'h', 'hv', 'e']]


In [10]:
v4_reordered.mult_table

array([[0, 1, 2, 3],
       [1, 0, 3, 2],
       [2, 3, 0, 1],
       [3, 2, 1, 0]])

In [11]:
pprint(v4.mult_table_with_names())

[['e', 'h', 'v', 'hv'],
 ['h', 'e', 'hv', 'v'],
 ['v', 'hv', 'e', 'h'],
 ['hv', 'v', 'h', 'e']]


In [12]:
v4.mult_table

array([[0, 1, 2, 3],
       [1, 0, 3, 2],
       [2, 3, 0, 1],
       [3, 2, 1, 0]])

In [13]:
new_d4_elem_order = ["e", "r", "r^2", "f", "r^3", "fr", "r^2f", "rf"]

In [14]:
d4_reordered = d4.reorder_elements(new_d4_elem_order)
d4_reordered

Group('D_4_REORDERED',
'Dihedral group on four vertices (elements reordered)',
['e', 'r', 'r^2', 'f', 'r^3', 'fr', 'r^2f', 'rf'],
[[0, 1, 2, 3, 4, 5, 6, 7], [1, 2, 4, 7, 0, 3, 5, 6], [2, 4, 0, 6, 1, 7, 3, 5], [3, 5, 6, 0, 7, 1, 2, 4], [4, 0, 1, 5, 2, 6, 7, 3], [5, 6, 7, 4, 3, 0, 1, 2], [6, 7, 3, 2, 5, 4, 0, 1], [7, 3, 5, 1, 6, 2, 4, 0]]) 

In [15]:
d4_reordered.mult_table

array([[0, 1, 2, 3, 4, 5, 6, 7],
       [1, 2, 4, 7, 0, 3, 5, 6],
       [2, 4, 0, 6, 1, 7, 3, 5],
       [3, 5, 6, 0, 7, 1, 2, 4],
       [4, 0, 1, 5, 2, 6, 7, 3],
       [5, 6, 7, 4, 3, 0, 1, 2],
       [6, 7, 3, 2, 5, 4, 0, 1],
       [7, 3, 5, 1, 6, 2, 4, 0]])

In [16]:
d4.mult_table

array([[0, 1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 0, 7, 4, 5, 6],
       [2, 3, 0, 1, 6, 7, 4, 5],
       [3, 0, 1, 2, 5, 6, 7, 4],
       [4, 5, 6, 7, 0, 1, 2, 3],
       [5, 6, 7, 4, 3, 0, 1, 2],
       [6, 7, 4, 5, 2, 3, 0, 1],
       [7, 4, 5, 6, 1, 2, 3, 0]])

In [17]:
d4.element_orders()

{'e': 1, 'r': 4, 'r^2': 2, 'r^3': 4, 'f': 2, 'fr': 2, 'r^2f': 2, 'rf': 2}

In [18]:
d4_reordered.element_orders()

{'e': 1, 'r': 4, 'r^2': 2, 'f': 2, 'r^3': 4, 'fr': 2, 'r^2f': 2, 'rf': 2}

## Generating Possible Multiplication Tables

In [19]:
foo = alg.generate_all_group_tables(4)
foo

[([0, 1, 2, 3], (1, 0, 3, 2), (2, 3, 0, 1), (3, 2, 1, 0)),
 ([0, 1, 2, 3], (1, 0, 3, 2), (2, 3, 1, 0), (3, 2, 0, 1)),
 ([0, 1, 2, 3], (1, 2, 3, 0), (2, 3, 0, 1), (3, 0, 1, 2)),
 ([0, 1, 2, 3], (1, 3, 0, 2), (2, 0, 3, 1), (3, 2, 1, 0))]

In [20]:
order = 4

In [21]:
row0 = list(range(order))
row0

[0, 1, 2, 3]

In [22]:
# all_perms = list(map(lambda perm: list(perm), permutations(row0)))
all_perms = permutations(row0)
all_perms

NameError: name 'permutations' is not defined

In [23]:
rows1a = filter(permutations(row0), row0, 1)
rows1a

NameError: name 'permutations' is not defined

In [ ]:
rows2a = filter(permutations(row0), row0, 2)
rows2a

In [ ]:
rows3a = filter(permutations(row0), row0, 3)
rows3a

In [ ]:
x = [[row0], rows1a, rows2a, rows3a]
x

In [ ]:
ts = list(product(*x))

In [ ]:
foo = ts[0]
foo

In [ ]:
for combo in combinations(foo, 2):
    print(combo, _no_conflict(combo[0], combo[1]))

In [ ]:
def _no_conflicts(items):
    return all(_no_conflict(combo[0], combo[1]) for combo in combinations(items, 2))

In [ ]:
_no_conflicts(foo)

In [ ]:
for t in ts:
    if _no_conflicts(t):
        print(t)

In [ ]:
[t for t in ts if _no_conflicts(t)]