# Regular Representation

Experimenting with the <i>regular representation</i> of Groups

In [1]:
import os
aa_path = os.path.join(os.getenv("PYPROJ"), "abstract_algebra")
alg_dir = os.path.join(aa_path, "Algebras")

import finite_algebras as alg
ex = alg.Examples(alg_dir)

                           Example Algebras
----------------------------------------------------------------------
  17 example algebras are available.
  Use "Examples[INDEX]" to retrieve a specific example,
  where INDEX is the first number on each line below:
----------------------------------------------------------------------
0: A4 -- Alternating group on 4 letters (AKA Tetrahedral group)
1: D3 -- https://en.wikipedia.org/wiki/Dihedral_group_of_order_6
2: D4 -- Dihedral group on four vertices
3: Pinter29 -- Non-abelian group, p.29, 'A Book of Abstract Algebra' by Charles C. Pinter
4: RPS -- Rock, Paper, Scissors Magma
5: S3 -- Symmetric group on 3 letters
6: S3X -- Another version of the symmetric group on 3 letters
7: V4 -- Klein-4 group
8: Z4 -- Cyclic group of order 4
9: F4 -- Field with 4 elements (from Wikipedia)
10: mag_id -- Magma with Identity
11: Example 1.4.1 -- See: Groupoids and Smarandache Groupoids by W. B. Vasantha Kandasamy
12: Ex6 -- Example 6: http://www-groups.m

In [2]:
z4 = alg.generate_cyclic_group(4)
z4

Group(
'Z4',
'Autogenerated cyclic Group of order 4',
['e', 'a', 'a^2', 'a^3'],
[[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]]
)

In [3]:
z4x = alg.make_finite_algebra(
    'Z4',
    'Cyclic group of order 4',
    ['R0', 'R90', 'R180', 'R270'],
    [[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]]
)

In [4]:
z4x.about()


** Group **
Name: Z4
Instance ID: 4455469904
Description: Cyclic group of order 4
Order: 4
Identity: R0
Commutative? Yes
Cyclic?: Yes
  Generators: ['R270', 'R90']
Elements:
   Index   Name   Inverse  Order
      0      R0      R0       1
      1     R90    R270       4
      2    R180    R180       2
      3    R270     R90       4
Cayley Table (showing indices):
[[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]]


In [5]:
import numpy as np

In [6]:
rot_dict = {
    'R0': np.array([[1, 0, 0, 0],
                    [0, 1, 0, 0],
                    [0, 0, 1, 0],
                    [0, 0, 0, 1]]),
    'R90': np.array([[0, 0, 0, 1],
                     [1, 0, 0, 0],
                     [0, 1, 0, 0],
                     [0, 0, 1, 0]]),
    'R180': np.array([[0, 0, 1, 0],
                      [0, 0, 0, 1],
                      [1, 0, 0, 0],
                      [0, 1, 0, 0]]),
    'R270': np.array([[0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1],
                      [1, 0, 0, 0]])
}

def k(R):
    return rot_dict[R]

k('R90')  # Example

array([[0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [7]:
b1 = np.array([[1], [0], [0], [0]])
b2 = np.array([[0], [1], [0], [0]])
b3 = np.array([[0], [0], [1], [0]])
b4 = np.array([[0], [0], [0], [1]])

b_dict = {'R0': b1, 'R90': b2, 'R180': b3, 'R270': b4}

def B(R):
    return b_dict[R]

# Example:
print(B('R90'))

[[0]
 [1]
 [0]
 [0]]


In [29]:
def b_tuple(b):
    '''Turns a column vector into a tuple, for use as a dictio22nary key.'''
    return tuple(map(lambda x: x[0], list(b)))

b_inv_dict = {b_tuple(val): key for key, val in b_dict.items()}

def B_inv(b):
    return b_inv_dict[b_tuple(b)]

print(B_inv(b2))
print(B_inv(B('R90')))
print(B(B_inv(b2)))
print(b_inv_dict)

R90
R90
[[0]
 [1]
 [0]
 [0]]
{(1, 0, 0, 0): 'R0', (0, 1, 0, 0): 'R90', (0, 0, 1, 0): 'R180', (0, 0, 0, 1): 'R270'}


In [30]:
# k(R)bj = B(f(R, Binv(bj)))

print(np.dot(k('R90'), b3))

print(B(z4x.op('R90', B_inv(b3))))

[[0]
 [0]
 [0]
 [1]]
[[0]
 [0]
 [0]
 [1]]


In [9]:
def mul3(v1, M, v2):
    '''Return the scalar value defined by: transpose(v1) * M * v2'''
    return np.dot(np.transpose(v1), np.dot(M, v2))[0][0]

mul3(b2, k('R270'), b3)  # Example

1