# Different Ways to Create a Group

This notebook features the different ways that a group can be created with the <b>algebras</b> module.

## Imports and Paths

In [1]:
import algebras as alg
import numpy as np
import json
import os

In [2]:
# Path to this repo
aa_path = os.path.join(os.getenv('PYPROJ'), 'abstract_algebra')

# Path to a directory containing Algebra definitions in JSON
alg_dir = os.path.join(aa_path, "Algebras")

## Method 1

This method of instantiation provides four inputs:

1. Name of group (string)
1. Description of group (string)
1. List of element names (list of strings)
1. Addition table (list of lists of integers)

In [12]:
g1 = alg.Group('V4',
               'Klein-4 group',
               ['e',  'h',  'v', 'hv'],
               [[0, 1, 2, 3],
                [1, 0, 3, 2],
                [2, 3, 0, 1],
                [3, 2, 1, 0]]
              )
g1

Group('V4', 'Klein-4 group', ['e', 'h', 'v', 'hv'], [[0 1 2 3]
 [1 0 3 2]
 [2 3 0 1]
 [3 2 1 0]]) 

## Method 2

This alternative method of instantiation is similar to the one above.

Note that this method does not require a list of element names, since it is already provided by the first row of the table.

1. Name of group (string)
1. Description of group (string)
1. Addition table (list of lists of strings)

In [14]:
g2 = alg.Group('V4',
               'Klein-4 group',
               [[ 'e', 'h' ,  'v', 'hv'],
                [ 'h', 'e' , 'hv', 'v' ],
                [ 'v', 'hv',  'e', 'h' ],
                ['hv', 'v' ,  'h', 'e' ]]
              )
g2

Group('V4', 'Klein-4 group', ['e', 'h', 'v', 'hv'], [[0 1 2 3]
 [1 0 3 2]
 [2 3 0 1]
 [3 2 1 0]]) 

## Method 3

The group definition can be stored in a file in JSON format and then read-in to instantiate a group.

Here's a path to such a file and a look at what the file contains:

In [17]:
v4_path = os.path.join(alg_dir, "v4_klein_4_group.json")

!cat {v4_path}

{"type": "Group",
 "name": "V4",
 "description": "Klein-4 group",
 "element_names": ["e", "h", "v", "hv"],
 "addition_table": [[0, 1, 2, 3],
                    [1, 0, 3, 2],
                    [2, 3, 0, 1],
                    [3, 2, 1, 0]]
}


In [19]:
g3 = alg.Group(v4_path)
g3

Group('V4', 'Klein-4 group', ['e', 'h', 'v', 'hv'], [[0 1 2 3]
 [1 0 3 2]
 [2 3 0 1]
 [3 2 1 0]]) 

## Method 4

In [20]:
v4_path_VERS2 = os.path.join(alg_dir, "v4_klein_4_group_VERS2.json")

!cat {v4_path_VERS2}

{"type": "Group",
 "name": "V4",
 "description": "Klein-4 group, Version 2",
 "addition_table": [[ "e", "h" ,  "v", "hv"],
                    [ "h", "e" , "hv", "v" ],
                    [ "v", "hv",  "e", "h" ],
                    ["hv", "v" ,  "h", "e" ]]
}


In [21]:
g4 = alg.Group(v4_path_VERS2)
g4

Group('V4', 'Klein-4 group, Version 2', ['e', 'h', 'v', 'hv'], [[0 1 2 3]
 [1 0 3 2]
 [2 3 0 1]
 [3 2 1 0]]) 

## Method 5

In [24]:
v4_dict = {'name': 'V4',
           'description': 'Klein-4 group',
           'element_names': ['e', 'h', 'v', 'hv'],
           'addition_table': [[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 0, 1], [3, 2, 1, 0]]}

In [26]:
g5 = alg.Group(v4_dict)
g5

Group('V4', 'Klein-4 group', ['e', 'h', 'v', 'hv'], [[0 1 2 3]
 [1 0 3 2]
 [2 3 0 1]
 [3 2 1 0]]) 

In [3]:
simp = alg.Group("Simple",
                 "A very simple group",
                 ["1", "-1"],
                 [[0, 1],
                  [1, 0]])

In [4]:
simp.print_info()


Group : Simple : A very simple group
  Element Names: ['1', '-1']
  Is Abelian? True
  Inverses:  (** - indicates that it is its own inverse)
    inv(1) = 1   **
    inv(-1) = -1   **
  Is associative? True
  Cayley Table:
     1  -1
    -1   1


### Klein-4 Group

See this [definition at GitHub](https://github.com/nathancarter/group-explorer/blob/master/groups/V_4.group).

In [5]:
v4_json = os.path.join(alg_dir, "v4_klein_4_group.json")

!cat {v4_json}

{"type": "Group",
 "name": "V4",
 "description": "Klein-4 group",
 "element_names": ["e", "h", "v", "hv"],
 "addition_table": [[0, 1, 2, 3],
                    [1, 0, 3, 2],
                    [2, 3, 0, 1],
                    [3, 2, 1, 0]]
}


In [6]:
v4 = alg.Group(v4_json)
v4

Group('V4', 'Klein-4 group', ['e', 'h', 'v', 'hv'], [[0 1 2 3]
 [1 0 3 2]
 [2 3 0 1]
 [3 2 1 0]]) 

The group can also be created at the command line:

In [7]:
v4x = alg.Group('V4x',
                'Klein-4 group',
                ['e',  'h',  'v', 'hv'],
                [[0, 1, 2, 3],
                 [1, 0, 3, 2],
                 [2, 3, 0, 1],
                 [3, 2, 1, 0]]
               )

v4x

Group('V4x', 'Klein-4 group', ['e', 'h', 'v', 'hv'], [[0 1 2 3]
 [1 0 3 2]
 [2 3 0 1]
 [3 2 1 0]]) 

In [8]:
v4.add('h','v')

'hv'

In [9]:
v4.print_info()


Group : V4 : Klein-4 group
  Element Names: ['e', 'h', 'v', 'hv']
  Is Abelian? True
  Inverses:  (** - indicates that it is its own inverse)
    inv(e) = e   **
    inv(h) = h   **
    inv(v) = v   **
    inv(hv) = hv   **
  Is associative? True
  Cayley Table:
     e   h   v  hv
     h   e  hv   v
     v  hv   e   h
    hv   v   h   e


In [10]:
v4.to_dict()

{'type': 'Group',
 'name': 'V4',
 'description': 'Klein-4 group',
 'element_names': ['e', 'h', 'v', 'hv'],
 'addition_table': [[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 0, 1], [3, 2, 1, 0]]}

In [11]:
v4json = json.dumps(v4.to_dict())
v4json

'{"type": "Group", "name": "V4", "description": "Klein-4 group", "element_names": ["e", "h", "v", "hv"], "addition_table": [[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 0, 1], [3, 2, 1, 0]]}'

### Cyclic group of order 4

See this [definition at GitHub](https://github.com/nathancarter/group-explorer/blob/master/groups/Z_4.group).

In [12]:
z4_json = os.path.join(alg_dir, "z4_cyclic_group_of_order_4.json")

!cat {z4_json}

{"type": "Group",
 "name": "Z4",
 "description": "Cyclic group of order 4",
 "element_names": ["e", "a", "a^2", "a^3"],
 "addition_table": [[0, 1, 2, 3],
                    [1, 2, 3, 0],
                    [2, 3, 0, 1],
                    [3, 0, 1, 2]]
}


In [13]:
z4 = alg.Group(z4_json)

z4.print_info()


Group : Z4 : Cyclic group of order 4
  Element Names: ['e', 'a', 'a^2', 'a^3']
  Is Abelian? True
  Inverses:  (** - indicates that it is its own inverse)
    inv(e) = e   **
    inv(a) = a^3 
    inv(a^2) = a^2   **
    inv(a^3) = a 
  Is associative? True
  Cayley Table:
      e    a  a^2  a^3
      a  a^2  a^3    e
    a^2  a^3    e    a
    a^3    e    a  a^2


In [14]:
z4.add('a^2','a^2')

'e'

In [15]:
z4.add('a^2', 'a^3')

'a'

### Symmetric group on 3 letters

See this [definition at GitHub](https://github.com/nathancarter/group-explorer/blob/master/groups/S_3.group). "Another name for this group is "Dihedral group on 3 vertices."

In [16]:
s3_json = os.path.join(alg_dir, "s3_symmetric_group_on_3_letters.json")

!cat {s3_json}

{"type": "Group",
 "name": "S3",
 "description": "Symmetric group on 3 letters",
 "element_names": ["e", "r", "r^2", "f", "fr", "rf"],
 "addition_table": [[0, 1, 2, 3, 4, 5],
                    [1, 2, 0, 5, 3, 4],
                    [2, 0, 1, 4, 5, 3],
                    [3, 4, 5, 0, 1, 2],
                    [4, 5, 3, 2, 0, 1],
                    [5, 3, 4, 1, 2, 0]]
}


In [17]:
s3 = alg.Group(s3_json)

s3.print_info()


Group : S3 : Symmetric group on 3 letters
  Element Names: ['e', 'r', 'r^2', 'f', 'fr', 'rf']
  Is Abelian? False
  Inverses:  (** - indicates that it is its own inverse)
    inv(e) = e   **
    inv(r) = r^2 
    inv(r^2) = r 
    inv(f) = f   **
    inv(fr) = fr   **
    inv(rf) = rf   **
  Is associative? True
  Cayley Table:
      e    r  r^2    f   fr   rf
      r  r^2    e   rf    f   fr
    r^2    e    r   fr   rf    f
      f   fr   rf    e    r  r^2
     fr   rf    f  r^2    e    r
     rf    f   fr    r  r^2    e


In [18]:
s3.add('fr', 'r^2')

'f'

In [19]:
s3.add('r^2', 'fr')

'rf'

### Symmetric Group, S3 (not same as S3, above)

This is the [Symmetric group, S3, as specified at Groupprops](https://groupprops.subwiki.org/wiki/Symmetric_group:S3).

W.r.t., how to interpret the addition table, the following quote helps:

[[from Wikipedia](https://groupprops.subwiki.org/wiki/Symmetric_group:S3)] "We portray elements as permutations on the set \{ 1,2,3 \} using the cycle decomposition. The row element is added on the left and the column element on the right, with the assumption of functions written on the left. This means that the column element is applied first and the row element is applied next."

In [20]:
s3x = alg.Group('S3X',
           'Another version of the symmetric group on 3 letters',
           ['()', '(1,2)', '(2,3)', '(1,3)', '(1,2,3)', '(1,3,2)'],
           [[0, 1, 2, 3, 4, 5],
            [1, 0, 4, 5, 2, 3],
            [2, 5, 0, 4, 3, 1],
            [3, 4, 5, 0, 1, 2],
            [4, 3, 1, 2, 5, 0],
            [5, 2, 3, 1, 0, 4]]
          )

In [21]:
s3x.dumps()

'{"type": "Group", "name": "S3X", "description": "Another version of the symmetric group on 3 letters", "element_names": ["()", "(1,2)", "(2,3)", "(1,3)", "(1,2,3)", "(1,3,2)"], "addition_table": [[0, 1, 2, 3, 4, 5], [1, 0, 4, 5, 2, 3], [2, 5, 0, 4, 3, 1], [3, 4, 5, 0, 1, 2], [4, 3, 1, 2, 5, 0], [5, 2, 3, 1, 0, 4]]}'

In [22]:
s3x_json = os.path.join(alg_dir, "s3x_symmetric_group_OTHER.json")

!cat {s3x_json}

{"type": "Group",
 "name": "S3X",
 "description":"Another version of the symmetric group on 3 letters",
 "element_names": ["()", "(1,2)", "(2,3)", "(1,3)", "(1,2,3)", "(1,3,2)"],
 "addition_table": [[0, 1, 2, 3, 4, 5],
                    [1, 0, 4, 5, 2, 3],
                    [2, 5, 0, 4, 3, 1],
                    [3, 4, 5, 0, 1, 2],
                    [4, 3, 1, 2, 5, 0],
                    [5, 2, 3, 1, 0, 4]]
}


In [23]:
s3x = alg.Group(s3x_json)

s3x.print_info()


Group : S3X : Another version of the symmetric group on 3 letters
  Element Names: ['()', '(1,2)', '(2,3)', '(1,3)', '(1,2,3)', '(1,3,2)']
  Is Abelian? False
  Inverses:  (** - indicates that it is its own inverse)
    inv(()) = ()   **
    inv((1,2)) = (1,2)   **
    inv((2,3)) = (2,3)   **
    inv((1,3)) = (1,3)   **
    inv((1,2,3)) = (1,3,2) 
    inv((1,3,2)) = (1,2,3) 
  Is associative? True
  Cayley Table:
         ()    (1,2)    (2,3)    (1,3)  (1,2,3)  (1,3,2)
      (1,2)       ()  (1,2,3)  (1,3,2)    (2,3)    (1,3)
      (2,3)  (1,3,2)       ()  (1,2,3)    (1,3)    (1,2)
      (1,3)  (1,2,3)  (1,3,2)       ()    (1,2)    (2,3)
    (1,2,3)    (1,3)    (1,2)    (2,3)  (1,3,2)       ()
    (1,3,2)    (2,3)    (1,3)    (1,2)       ()  (1,2,3)


In [24]:
s3x.add('(1,2)', '(2,3)')

'(1,2,3)'

#### Write out group to JSON file

In [25]:
s3x_test_json_dump = os.path.join(alg_dir, "s3x_TEST_JSON_DUMP.json")

s3x.dump(s3x_test_json_dump)

## Z_2 x Z_2 x Z_2

In [26]:
Z2xZ2xZ2 = alg.Group('Z_2 x Z_2 x Z_2',
                 'no description',
                 ['eee', 'aee', 'eae', 'aae', 'eea', 'aea', 'eaa', 'aaa'],
                 [[0, 1, 2, 3, 4, 5, 6, 7],
                  [1, 0, 3, 2, 5, 4, 7, 6],
                  [2, 3, 0, 1, 6, 7, 4, 5],
                  [3, 2, 1, 0, 7, 6, 5, 4],
                  [4, 5, 6, 7, 0, 1, 2, 3],
                  [5, 4, 7, 6, 1, 0, 3, 2],
                  [6, 7, 4, 5, 2, 3, 0, 1],
                  [7, 6, 5, 4, 3, 2, 1, 0]]
                )

In [27]:
Z2xZ2xZ2.dumps()

'{"type": "Group", "name": "Z_2 x Z_2 x Z_2", "description": "no description", "element_names": ["eee", "aee", "eae", "aae", "eea", "aea", "eaa", "aaa"], "addition_table": [[0, 1, 2, 3, 4, 5, 6, 7], [1, 0, 3, 2, 5, 4, 7, 6], [2, 3, 0, 1, 6, 7, 4, 5], [3, 2, 1, 0, 7, 6, 5, 4], [4, 5, 6, 7, 0, 1, 2, 3], [5, 4, 7, 6, 1, 0, 3, 2], [6, 7, 4, 5, 2, 3, 0, 1], [7, 6, 5, 4, 3, 2, 1, 0]]}'

## Direct Products

In [28]:
z2 = alg.Group('Z2',
           'Cyclic group of order 2',
           ['E', 'A'],
           [[0, 1],
            [1, 0]]
          )

z3 = alg.Group('Z3',
           'Cyclic group of order 3',
           ['E', 'A', 'B'],
           [[0, 1, 2],
            [1, 2, 0],
            [2, 0, 1]]
          )

In [29]:
z3_x_z3 = z3 * z3
z3_x_z3

Group('Z3_x_Z3', 'Direct product of Z3 & Z3', ['E,E', 'E,A', 'E,B', 'A,E', 'A,A', 'A,B', 'B,E', 'B,A', 'B,B'], [[0 1 2 3 4 5 6 7 8]
 [1 2 0 4 5 3 7 8 6]
 [2 0 1 5 3 4 8 6 7]
 [3 4 5 6 7 8 0 1 2]
 [4 5 3 7 8 6 1 2 0]
 [5 3 4 8 6 7 2 0 1]
 [6 7 8 0 1 2 3 4 5]
 [7 8 6 1 2 0 4 5 3]
 [8 6 7 2 0 1 5 3 4]]) 

In [30]:
z3_x_z3.element_names

['E,E', 'E,A', 'E,B', 'A,E', 'A,A', 'A,B', 'B,E', 'B,A', 'B,B']

In [31]:
z3_x_z3.addition_table

array([[0, 1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 0, 4, 5, 3, 7, 8, 6],
       [2, 0, 1, 5, 3, 4, 8, 6, 7],
       [3, 4, 5, 6, 7, 8, 0, 1, 2],
       [4, 5, 3, 7, 8, 6, 1, 2, 0],
       [5, 3, 4, 8, 6, 7, 2, 0, 1],
       [6, 7, 8, 0, 1, 2, 3, 4, 5],
       [7, 8, 6, 1, 2, 0, 4, 5, 3],
       [8, 6, 7, 2, 0, 1, 5, 3, 4]])

In [32]:
z3_x_z3.addition_table_with_names()

[['E,E', 'E,A', 'E,B', 'A,E', 'A,A', 'A,B', 'B,E', 'B,A', 'B,B'],
 ['E,A', 'E,B', 'E,E', 'A,A', 'A,B', 'A,E', 'B,A', 'B,B', 'B,E'],
 ['E,B', 'E,E', 'E,A', 'A,B', 'A,E', 'A,A', 'B,B', 'B,E', 'B,A'],
 ['A,E', 'A,A', 'A,B', 'B,E', 'B,A', 'B,B', 'E,E', 'E,A', 'E,B'],
 ['A,A', 'A,B', 'A,E', 'B,A', 'B,B', 'B,E', 'E,A', 'E,B', 'E,E'],
 ['A,B', 'A,E', 'A,A', 'B,B', 'B,E', 'B,A', 'E,B', 'E,E', 'E,A'],
 ['B,E', 'B,A', 'B,B', 'E,E', 'E,A', 'E,B', 'A,E', 'A,A', 'A,B'],
 ['B,A', 'B,B', 'B,E', 'E,A', 'E,B', 'E,E', 'A,A', 'A,B', 'A,E'],
 ['B,B', 'B,E', 'B,A', 'E,B', 'E,E', 'E,A', 'A,B', 'A,E', 'A,A']]

In [33]:
z3_x_z3.pretty_print_addition_table()

  E,E  E,A  E,B  A,E  A,A  A,B  B,E  B,A  B,B
  E,A  E,B  E,E  A,A  A,B  A,E  B,A  B,B  B,E
  E,B  E,E  E,A  A,B  A,E  A,A  B,B  B,E  B,A
  A,E  A,A  A,B  B,E  B,A  B,B  E,E  E,A  E,B
  A,A  A,B  A,E  B,A  B,B  B,E  E,A  E,B  E,E
  A,B  A,E  A,A  B,B  B,E  B,A  E,B  E,E  E,A
  B,E  B,A  B,B  E,E  E,A  E,B  A,E  A,A  A,B
  B,A  B,B  B,E  E,A  E,B  E,E  A,A  A,B  A,E
  B,B  B,E  B,A  E,B  E,E  E,A  A,B  A,E  A,A


In [34]:
for elem in z3_x_z3.element_names:
    print(f"inv({elem}) = {z3_x_z3.inverse(elem)}")

inv(E,E) = E,E
inv(E,A) = E,B
inv(E,B) = E,A
inv(A,E) = B,E
inv(A,A) = B,B
inv(A,B) = B,A
inv(B,E) = A,E
inv(B,A) = A,B
inv(B,B) = A,A


In [35]:
z3_x_z3.abelian()

True

In [36]:
z3_x_z3.associative()

True

In [37]:
z2_x_z2_x_z2 = z2 * z2 * z2

In [38]:
z2_x_z2_x_z2.element_names

['E,E,E', 'E,E,A', 'E,A,E', 'E,A,A', 'A,E,E', 'A,E,A', 'A,A,E', 'A,A,A']

In [39]:
z2_x_z2_x_z2.addition_table

array([[0, 1, 2, 3, 4, 5, 6, 7],
       [1, 0, 3, 2, 5, 4, 7, 6],
       [2, 3, 0, 1, 6, 7, 4, 5],
       [3, 2, 1, 0, 7, 6, 5, 4],
       [4, 5, 6, 7, 0, 1, 2, 3],
       [5, 4, 7, 6, 1, 0, 3, 2],
       [6, 7, 4, 5, 2, 3, 0, 1],
       [7, 6, 5, 4, 3, 2, 1, 0]])

In [40]:
for elem in z2_x_z2_x_z2.element_names:
    print(f"inv({elem}) = {z2_x_z2_x_z2.inverse(elem)}")

inv(E,E,E) = E,E,E
inv(E,E,A) = E,E,A
inv(E,A,E) = E,A,E
inv(E,A,A) = E,A,A
inv(A,E,E) = A,E,E
inv(A,E,A) = A,E,A
inv(A,A,E) = A,A,E
inv(A,A,A) = A,A,A


## Tesseract group

This group has 384 elements and was converted to JSON from [this definition](https://github.com/nathancarter/group-explorer/blob/master/groups/Tesseract.group).

In [41]:
tesseract_path = os.path.join(alg_dir, "tesseract.json")
tesseract = alg.Group(tesseract_path)
print(tesseract)

<Group: Tesseract, The symmetries of the hypercube>


In [42]:
tesseract.abelian()

False

In [43]:
#tesseract.associative() # True

In [44]:
len(tesseract.element_names)

384

Here are the first n elements:

In [45]:
n = 25
tesseract.element_names[:n]

['e',
 'a',
 'b',
 'ba',
 'bb',
 'bba',
 'ab',
 'aba',
 'bab',
 'baba',
 'bbab',
 'abababba',
 'abb',
 'abba',
 'babb',
 'abababbab',
 'ababa',
 'abab',
 'abbab',
 'acabababbac',
 'babbab',
 'ababbab',
 'ababb',
 'ababba',
 'c']

In [46]:
tesseract.add('abab', 'baba')

'babbab'

## Scratch Work

In [47]:
!cat {s3_json}

{"type": "Group",
 "name": "S3",
 "description": "Symmetric group on 3 letters",
 "element_names": ["e", "r", "r^2", "f", "fr", "rf"],
 "addition_table": [[0, 1, 2, 3, 4, 5],
                    [1, 2, 0, 5, 3, 4],
                    [2, 0, 1, 4, 5, 3],
                    [3, 4, 5, 0, 1, 2],
                    [4, 5, 3, 2, 0, 1],
                    [5, 3, 4, 1, 2, 0]]
}


In [48]:
s3x = alg.Group(s3x_json)
s3x

Group('S3X', 'Another version of the symmetric group on 3 letters', ['()', '(1,2)', '(2,3)', '(1,3)', '(1,2,3)', '(1,3,2)'], [[0 1 2 3 4 5]
 [1 0 4 5 2 3]
 [2 5 0 4 3 1]
 [3 4 5 0 1 2]
 [4 3 1 2 5 0]
 [5 2 3 1 0 4]]) 

In [49]:
s3x.element_names

['()', '(1,2)', '(2,3)', '(1,3)', '(1,2,3)', '(1,3,2)']

In [50]:
s3x.pretty_print_addition_table()

       ()    (1,2)    (2,3)    (1,3)  (1,2,3)  (1,3,2)
    (1,2)       ()  (1,2,3)  (1,3,2)    (2,3)    (1,3)
    (2,3)  (1,3,2)       ()  (1,2,3)    (1,3)    (1,2)
    (1,3)  (1,2,3)  (1,3,2)       ()    (1,2)    (2,3)
  (1,2,3)    (1,3)    (1,2)    (2,3)  (1,3,2)       ()
  (1,3,2)    (2,3)    (1,3)    (1,2)       ()  (1,2,3)


In [51]:
s3x.addition_table

array([[0, 1, 2, 3, 4, 5],
       [1, 0, 4, 5, 2, 3],
       [2, 5, 0, 4, 3, 1],
       [3, 4, 5, 0, 1, 2],
       [4, 3, 1, 2, 5, 0],
       [5, 2, 3, 1, 0, 4]])

In [52]:
# my_array[:, [2, 0]] = my_array[:, [0, 2]]

s3x.addition_table[:, [5, 4]] = s3x.addition_table[:, [4, 5]]
s3x.addition_table[[5, 4], :] = s3x.addition_table[[4, 5], :]
s3x.element_names[5], s3x.element_names[4] = s3x.element_names[4], s3x.element_names[5]

In [53]:
s3x.element_names

['()', '(1,2)', '(2,3)', '(1,3)', '(1,3,2)', '(1,2,3)']

In [54]:
s3x.addition_table

array([[0, 1, 2, 3, 5, 4],
       [1, 0, 4, 5, 3, 2],
       [2, 5, 0, 4, 1, 3],
       [3, 4, 5, 0, 2, 1],
       [5, 2, 3, 1, 4, 0],
       [4, 3, 1, 2, 0, 5]])

In [55]:
s3x.pretty_print_addition_table()

       ()    (1,2)    (2,3)    (1,3)  (1,3,2)  (1,2,3)
    (1,2)       ()  (1,3,2)  (1,2,3)    (2,3)    (1,3)
    (2,3)  (1,2,3)       ()  (1,3,2)    (1,3)    (1,2)
    (1,3)  (1,3,2)  (1,2,3)       ()    (1,2)    (2,3)
  (1,3,2)    (1,3)    (1,2)    (2,3)  (1,2,3)       ()
  (1,2,3)    (2,3)    (1,3)    (1,2)       ()  (1,3,2)


### Algebra from Pinter's book, top of page 29

In [56]:
foo = ["IABCDK", "AICBKD", "BKDAIC", "CDKIAB", "DCIKBA", "KBADCI"]

In [57]:
table = list(map(list, foo))
table

[['I', 'A', 'B', 'C', 'D', 'K'],
 ['A', 'I', 'C', 'B', 'K', 'D'],
 ['B', 'K', 'D', 'A', 'I', 'C'],
 ['C', 'D', 'K', 'I', 'A', 'B'],
 ['D', 'C', 'I', 'K', 'B', 'A'],
 ['K', 'B', 'A', 'D', 'C', 'I']]

In [58]:
alg.index_table_from_name_table(table)

[[0, 1, 2, 3, 4, 5],
 [1, 0, 3, 2, 5, 4],
 [2, 5, 4, 1, 0, 3],
 [3, 4, 5, 0, 1, 2],
 [4, 3, 0, 5, 2, 1],
 [5, 2, 1, 4, 3, 0]]

In [59]:
foo = alg.Group("Test", "yada, yada, yada, ...", table)

In [60]:
foo

Group('Test', 'yada, yada, yada, ...', ['I', 'A', 'B', 'C', 'D', 'K'], [[0 1 2 3 4 5]
 [1 0 3 2 5 4]
 [2 5 4 1 0 3]
 [3 4 5 0 1 2]
 [4 3 0 5 2 1]
 [5 2 1 4 3 0]]) 

In [61]:
foo.dumps()

'{"type": "Group", "name": "Test", "description": "yada, yada, yada, ...", "element_names": ["I", "A", "B", "C", "D", "K"], "addition_table": [[0, 1, 2, 3, 4, 5], [1, 0, 3, 2, 5, 4], [2, 5, 4, 1, 0, 3], [3, 4, 5, 0, 1, 2], [4, 3, 0, 5, 2, 1], [5, 2, 1, 4, 3, 0]]}'

In [62]:
pinter_p29_path = os.path.join(alg_dir, "Pinter_page_29.json")
pinter_p29 = alg.Group(pinter_p29_path)
pinter_p29

Group('Non-Abelian_Example', 'Example on page 29 of 'A Book of Abstract Algebra' by Charles C. Pinter', ['I', 'A', 'B', 'C', 'D', 'K'], [[0 1 2 3 4 5]
 [1 0 3 2 5 4]
 [2 5 4 1 0 3]
 [3 4 5 0 1 2]
 [4 3 0 5 2 1]
 [5 2 1 4 3 0]]) 

In [64]:
pinter_p29.print_info()


Group : Non-Abelian_Example : Example on page 29 of 'A Book of Abstract Algebra' by Charles C. Pinter
  Element Names: ['I', 'A', 'B', 'C', 'D', 'K']
  Is Abelian? False
  Inverses:  (** - indicates that it is its own inverse)
    inv(I) = I   **
    inv(A) = A   **
    inv(B) = D 
    inv(C) = C   **
    inv(D) = B 
    inv(K) = K   **
  Is associative? True
  Cayley Table:
    I  A  B  C  D  K
    A  I  C  B  K  D
    B  K  D  A  I  C
    C  D  K  I  A  B
    D  C  I  K  B  A
    K  B  A  D  C  I


### Check Table

In [101]:
from collections import Counter

def duplicates(lst):
    return [item for item, count in Counter(lst).items() if count > 1]

[1, 2, 5]

In [141]:
def check_addition_table(element_names, addition_table):
    """Check that each row and column in the table has a unique number of elements equal to the
    expected number of elements.  Basically, each element should appear exactly once in each row
    and each column. Returns True if the table is OK."""
    
    # Check for duplicate element names
    #element_set = set(element_names)
    dups = duplicates(element_names)
    if len(dups) == 0:
        pass
    else:
        raise ValueError(f"Duplicate element names: {dups}")

    # Check that table is square
    rows, cols = addition_table.shape
    if (rows == cols):
        pass
    else:
        raise ValueError(f"The table is not square: {rows}x{cols}")
        
    # Check that the row-col dimensions are the same as the number of elements

    num_elements = len(element_names)
    if (rows == num_elements):
        pass
    else:
        raise ValueError(f"Number of elements is {num_elements}, but table size is {rows}x{cols}")

    # Check that each table row contains the correct values for a Cayley table
    correct_indices = set(range(num_elements))  # {0, 1, 2, ..., n-1}
    row_number = -1
    for row in addition_table:
        row_number += 1
        if (set(row) == correct_indices):
            pass
        else:
            raise ValueError(f"A row {row_number} does not contain the correct values")

    # Check that each table col contains the correct values for a Cayley table
    for col_number in range(num_elements):
        if (set(addition_table[:, col_number]) == correct_indices):
            pass
        else:
            raise ValueError(f"Column {col_number} does not contain the correct values")

    return True

In [131]:
# Everything is OK for this case
check_addition_table(['()', '(1,2)', '(2,3)', '(1,3)', '(1,2,3)', '(1,3,2)'],
                     np.array([[0, 1, 2, 3, 4, 5],
                               [1, 0, 4, 5, 2, 3],
                               [2, 5, 0, 4, 3, 1],
                               [3, 4, 5, 0, 1, 2],
                               [4, 3, 1, 2, 5, 0],
                               [5, 2, 3, 1, 0, 4]]
                             )
                    )

True

In [132]:
# Duplicate element names
check_addition_table(['()', '(1,2)', '(2,3)', '(1,3)', '(1,3,2)', '(1,3,2)'],
                     np.array([[0, 1, 2, 3, 4, 5],
                               [1, 0, 4, 5, 2, 3],
                               [2, 5, 0, 4, 3, 1],
                               [3, 4, 5, 0, 1, 2],
                               [4, 3, 1, 2, 5, 0],
                               [5, 2, 3, 1, 0, 4]]
                             )
                    )

ValueError: Duplicate element names: ['(1,3,2)']

In [133]:
# Too many elements in element list
check_addition_table(['()', '(1,2)', '(2,3)', '(1,3)', '(1,2,3)', '(1,3,2)', 'FUBAR'],
                     np.array([[0, 1, 2, 3, 4, 5],
                               [1, 0, 4, 5, 2, 3],
                               [2, 5, 0, 4, 3, 1],
                               [3, 4, 5, 0, 1, 2],
                               [4, 3, 1, 2, 5, 0],
                               [5, 2, 3, 1, 0, 4]]
                             )
                    )

ValueError: Number of elements is 7, but table size is 6x6

In [134]:
# Too few elements in element list
check_addition_table(['()', '(1,2)', '(2,3)', '(1,3)', '(1,2,3)'],
                     np.array([[0, 1, 2, 3, 4, 5],
                               [1, 0, 4, 5, 2, 3],
                               [2, 5, 0, 4, 3, 1],
                               [3, 4, 5, 0, 1, 2],
                               [4, 3, 1, 2, 5, 0],
                               [5, 2, 3, 1, 0, 4]]
                             )
                    )

ValueError: Number of elements is 5, but table size is 6x6

In [135]:
# Duplicate index number in row 2
check_addition_table(['()', '(1,2)', '(2,3)', '(1,3)', '(1,2,3)', '(1,3,2)'],
                     np.array([[0, 1, 2, 3, 4, 5],
                               [1, 0, 4, 5, 2, 3],
                               [2, 5, 0, 4, 0, 1],  # Second 0 should be a 3
                               [3, 4, 5, 0, 1, 2],
                               [4, 3, 1, 2, 5, 0],
                               [5, 2, 3, 1, 0, 4]]
                             )
                    )

ValueError: A row 2 does not contain the correct values

In [136]:
# Missing row
check_addition_table(['()', '(1,2)', '(2,3)', '(1,3)', '(1,2,3)', '(1,3,2)'],
                     np.array([[0, 1, 2, 3, 4, 5],
                               [1, 0, 4, 5, 2, 3],
                               #[2, 5, 0, 4, 3, 1],
                               [3, 4, 5, 0, 1, 2],
                               [4, 3, 1, 2, 5, 0],
                               [5, 2, 3, 1, 0, 4]]
                             )
                    )

ValueError: The table is not square: 5x6

In [137]:
# Extra row
check_addition_table(['()', '(1,2)', '(2,3)', '(1,3)', '(1,2,3)', '(1,3,2)'],
                     np.array([[0, 1, 2, 3, 4, 5],
                               [1, 0, 4, 5, 2, 3],
                               [2, 5, 0, 4, 3, 1],
                               [3, 4, 5, 0, 1, 2],
                               [3, 4, 5, 0, 1, 2],
                               [4, 3, 1, 2, 5, 0],
                               [5, 2, 3, 1, 0, 4]]
                             )
                    )

ValueError: The table is not square: 7x6

In [138]:
# Missing column
check_addition_table(['()', '(1,2)', '(2,3)', '(1,3)', '(1,2,3)', '(1,3,2)'],
                     np.array([[0, 1, 2, 4, 5],
                               [1, 0, 4, 2, 3],
                               [2, 5, 0, 3, 1],
                               [3, 4, 5, 1, 2],
                               [4, 3, 1, 5, 0],
                               [5, 2, 3, 0, 4]]
                             )
                    )

ValueError: The table is not square: 6x5

In [139]:
# Invalid entry in table
check_addition_table(['()', '(1,2)', '(2,3)', '(1,3)', '(1,2,3)', '(1,3,2)'],
                     np.array([[0, 1, 2, 3, 4, 5],
                               [1, 0, 4, 5, 2, 3],
                               [2, 5, 0, 444, 3, 1],  # Invalid value here
                               [3, 4, 5, 0, 1, 2],
                               [4, 3, 1, 2, 5, 0],
                               [5, 2, 3, 1, 0, 4]]
                             )
                    )

ValueError: A row 2 does not contain the correct values

In [140]:
# Elements switched in row 2
check_addition_table(['()', '(1,2)', '(2,3)', '(1,3)', '(1,2,3)', '(1,3,2)'],
                     np.array([[0, 1, 2, 3, 4, 5],
                               [1, 0, 4, 5, 2, 3],
                               [2, 4, 0, 5, 3, 1],  # Items 1 & 3 switched here
                               [3, 4, 5, 0, 1, 2],
                               [4, 3, 1, 2, 5, 0],
                               [5, 2, 3, 1, 0, 4]]
                             )
                    )

ValueError: A column 1 does not contain the correct values