# Experiments Changing the Element Ordering

This notebook is only used for trying out ideas.

In [1]:
import algebras as alg
import json
import os
import numpy as np
import itertools as it
# from pprint import pprint
import pprint as pp

# from itertools import combinations, permutations, product
import itertools as it

In [2]:
# Path to this repo
aa_path = os.path.join(os.getenv('PYPROJ'), 'abstract_algebra')

# Path to a directory containing Algebra definitions in JSON
alg_dir = os.path.join(aa_path, "Algebras")

## Groups for Testing

### D4 - Dihedral Group on 4 Vertices

In [3]:
d4_path = os.path.join(alg_dir, "d4_dihedral_group_on_4_vertices.json")
!cat {d4_path}

{"type": "Group",
 "name": "D_4",
 "description": "Dihedral group on four vertices",
 "element_names": ["e", "r", "r^2", "r^3", "f", "fr", "r^2f", "rf"],
 "alt_elem_names": ["()", "(0 1 2 3)", "(0 2)(1 3)", "(0 3 2 1)",
                    "(0 1)(2 3)", "(1 3)", "(0 3)(1 2)", "(0 2)"],
 "mult_table": [[0, 1, 2, 3, 4, 5, 6, 7],
                [1, 2, 3, 0, 7, 4, 5, 6],
                [2, 3, 0, 1, 6, 7, 4, 5],
                [3, 0, 1, 2, 5, 6, 7, 4],
                [4, 5, 6, 7, 0, 1, 2, 3],
                [5, 6, 7, 4, 3, 0, 1, 2],
                [6, 7, 4, 5, 2, 3, 0, 1],
                [7, 4, 5, 6, 1, 2, 3, 0]]
}

In [4]:
d4 = alg.Group(d4_path)
d4.about()


Group: D_4
Dihedral group on four vertices
Abelian? False
Elements:
   Index   Name   Inverse  Order
      0       e       e       1
      1       r     r^3       4
      2     r^2     r^2       2
      3     r^3       r       4
      4       f       f       2
      5      fr      fr       2
      6    r^2f    r^2f       2
      7      rf      rf       2
Cayley Table (showing indices):
[[0, 1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 0, 7, 4, 5, 6],
 [2, 3, 0, 1, 6, 7, 4, 5],
 [3, 0, 1, 2, 5, 6, 7, 4],
 [4, 5, 6, 7, 0, 1, 2, 3],
 [5, 6, 7, 4, 3, 0, 1, 2],
 [6, 7, 4, 5, 2, 3, 0, 1],
 [7, 4, 5, 6, 1, 2, 3, 0]]


### V4 - Klein 4 Group

In [5]:
v4_path = os.path.join(alg_dir, "v4_klein_4_group.json")
!cat {v4_path}

{"type": "Group",
 "name": "V4",
 "description": "Klein-4 group",
 "element_names": ["e", "h", "v", "hv"],
 "mult_table": [[0, 1, 2, 3],
                [1, 0, 3, 2],
                [2, 3, 0, 1],
                [3, 2, 1, 0]]
}


In [6]:
v4 = alg.Group(v4_path)
v4.about()


Group: V4
Klein-4 group
Abelian? True
Elements:
   Index   Name   Inverse  Order
      0       e       e       1
      1       h       h       2
      2       v       v       2
      3      hv      hv       2
Cayley Table (showing indices):
[[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 0, 1], [3, 2, 1, 0]]


In [7]:
z2 = alg.generate_cyclic_group(2)
z2

Group('Z2',
'Autogenerated cyclic group of order 2',
['e', 'a'],
[[0, 1], [1, 0]]) 

In [8]:
z2_x_z2 = z2 * z2
z2_x_z2

Group('Z2_x_Z2',
'Direct product of Z2 & Z2',
['e:e', 'e:a', 'a:e', 'a:a'],
[[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 0, 1], [3, 2, 1, 0]]) 

In [9]:
z4 = alg.generate_cyclic_group(4)
z4

Group('Z4',
'Autogenerated cyclic group of order 4',
['e', 'a', 'a^2', 'a^3'],
[[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]]) 

## Changing the Order of Elements

<b>Observation</b>: If the group is abelian, then changing the order of the elements does <b>not</b> affect the order of the indices in the <i>mult_table</i>.  <b>Why?</b>

In [10]:
# new_elem_order = v4.element_names
# new_v4_elem_order = ['e', 'v', 'h', 'hv']
new_v4_elem_order = ["e", "hv", "h", "v"]

In [11]:
#table_from_reordered_elements(v4, new_v4_elem_order)
v4_reordered = v4.reorder_elements(new_v4_elem_order)
v4_reordered

Group('V4_REORDERED',
'Klein-4 group (elements reordered)',
['e', 'hv', 'h', 'v'],
[[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 0, 1], [3, 2, 1, 0]]) 

In [12]:
pp.pprint(v4_reordered.mult_table_with_names())

[['e', 'hv', 'h', 'v'],
 ['hv', 'e', 'v', 'h'],
 ['h', 'v', 'e', 'hv'],
 ['v', 'h', 'hv', 'e']]


In [13]:
v4_reordered.mult_table

array([[0, 1, 2, 3],
       [1, 0, 3, 2],
       [2, 3, 0, 1],
       [3, 2, 1, 0]])

In [14]:
pp.pprint(v4.mult_table_with_names())

[['e', 'h', 'v', 'hv'],
 ['h', 'e', 'hv', 'v'],
 ['v', 'hv', 'e', 'h'],
 ['hv', 'v', 'h', 'e']]


In [15]:
v4.mult_table

array([[0, 1, 2, 3],
       [1, 0, 3, 2],
       [2, 3, 0, 1],
       [3, 2, 1, 0]])

In [16]:
new_d4_elem_order = ["e", "r", "r^2", "f", "r^3", "fr", "r^2f", "rf"]

In [17]:
d4_reordered = d4.reorder_elements(new_d4_elem_order)
d4_reordered

Group('D_4_REORDERED',
'Dihedral group on four vertices (elements reordered)',
['e', 'r', 'r^2', 'f', 'r^3', 'fr', 'r^2f', 'rf'],
[[0, 1, 2, 3, 4, 5, 6, 7], [1, 2, 4, 7, 0, 3, 5, 6], [2, 4, 0, 6, 1, 7, 3, 5], [3, 5, 6, 0, 7, 1, 2, 4], [4, 0, 1, 5, 2, 6, 7, 3], [5, 6, 7, 4, 3, 0, 1, 2], [6, 7, 3, 2, 5, 4, 0, 1], [7, 3, 5, 1, 6, 2, 4, 0]]) 

In [18]:
d4_reordered.mult_table

array([[0, 1, 2, 3, 4, 5, 6, 7],
       [1, 2, 4, 7, 0, 3, 5, 6],
       [2, 4, 0, 6, 1, 7, 3, 5],
       [3, 5, 6, 0, 7, 1, 2, 4],
       [4, 0, 1, 5, 2, 6, 7, 3],
       [5, 6, 7, 4, 3, 0, 1, 2],
       [6, 7, 3, 2, 5, 4, 0, 1],
       [7, 3, 5, 1, 6, 2, 4, 0]])

In [19]:
d4.mult_table

array([[0, 1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 0, 7, 4, 5, 6],
       [2, 3, 0, 1, 6, 7, 4, 5],
       [3, 0, 1, 2, 5, 6, 7, 4],
       [4, 5, 6, 7, 0, 1, 2, 3],
       [5, 6, 7, 4, 3, 0, 1, 2],
       [6, 7, 4, 5, 2, 3, 0, 1],
       [7, 4, 5, 6, 1, 2, 3, 0]])

In [20]:
d4.element_orders()

{'e': 1, 'r': 4, 'r^2': 2, 'r^3': 4, 'f': 2, 'fr': 2, 'r^2f': 2, 'rf': 2}

In [21]:
d4_reordered.element_orders()

{'e': 1, 'r': 4, 'r^2': 2, 'f': 2, 'r^3': 4, 'fr': 2, 'r^2f': 2, 'rf': 2}